### ISSUE TITLE
Bug: Installer generates app.php and .htaccess with '\' instead of '/' in Windows

### ISSUE THREAD

**Issue by Darunada** [anchorcms/anchor-cms#1002]
Doing a new install of anchor CMS in Windows 10 using XAMPP, the installer generates the config file as such: 

```
<?php

return array(
    'url' => '\',
    'index' => '',
    'timezone' => 'America/Denver',
    'key' => '[key-replaced]',
    'language' => 'en_GB',
    'encoding' => 'UTF-8'
);
```

Obviously the ```'url' => '\'```, escapes the closing quotation mark, causing a syntax error in the file.

Additionally, the same problem is apparent during the install process when the .htaccess file it generates contains ```RewriteBase \``` which is also invalid, causing an apache 500 error.

**Comment by TheBrenny** [comment]
Right as Anchor initialises, it sets the directory separator to use. I'll follow this up, and we'll see what I find...
