### ISSUE TITLE
How to change the Twitter URL into the Metas in the sidebar

### ISSUE THREAD

**Issue by AlexL777** [anchorcms/anchor-cms#1007]
Hello Developers,

I have been working today with Anchor CMS and find it quite good. How can I change the Twitter URL in "Meta" in the right sidebar? It's somewhere in the system a strange Twitter name deposited and this I have to change times.

My Anchor blog is under http://internetblogger.at/cms/anchorcms

How can I change?

Thanks in advance.

**Comment by TheBrenny** [comment]
You should be able to change it in the meta tab of the admin panel, or it could be hardcoded into the theme you're using?

**Comment by AlexL777** [comment]
In the aside.php file is following:

    <Li> <a href="<?php echo rss_url(); ?> "> RSS code </ li>
                                         <? Php if (twitter_account ()):?>
                                         <Li> <a href="<?php echo twitter_url(); ?> "> @ <? Php echo  twitter_account (); ?> Code </ li>
                                         <? Php endif; ?>
                                         <Li> <a href="<?php echo base_url('admin'); ?> "title =" Administer your site! "> Admin area code </ li>
                                         <Li> <a href="<?php echo base_url(); ?> "title =" Return to my website. "> Home code </ li>


But if I with "@" entries my Twitter name on the site, still does not change the frontend.

In the backend I find nowhere a statement on the Twitter account. Apparently it is installed somewhere in the current theme.

**Comment by TheBrenny** [comment]
Most likely in the theme's `functions.php` file is a function called `twitter_account()`. If not, an error would be thrown. Have a look at that function. And it most likely will call for a site meta with a specific key. That key should be a meta variable in your extend tab, in your admin panel.

**Comment by AlexL777** [comment]
Thanks for the quick help. I have now replaced in the functions.php against my Twitter account. Now everything works.

**Comment by TheBrenny** [comment]
No worries. Issue closed! :D

**Comment by daviddarnes** [comment]
@TheBrenny nice work!
