### ISSUE TITLE
BUG: Stored XSS in Category Name

### ISSUE THREAD

**Issue by matt-** [anchorcms/anchor-cms#1009]
The Category Name can contain HTML characters including javascript tags, and is stored and reflected to all other users.

1. Browse to /admin/categories
2. Create a category with with the name "&lt;script>alert(1)&lt;/script>". 
3. Notice the alert on many of the admin pages. 

This is only possible by logged in users, and currently it looks like all users basically have the same access. However this could be used at some point if an "editor" could edit / create a category and wanted Admin access. The javascript could be used to force the next logged in "admin" to update the privileges of the "attacker / editor".

To fix: Validate user input if you do not want special chars in the category name. Also always HTML encode the category name before displaying it. 

Note: Outside of the security issue you may want to resolve this to prevent formatting issues this may cause. 

Also consider adding [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/Using_Content_Security_Policy) headers as well to help mitigate this type of attack.

**Comment by CraigChilds94** [comment]
Fixed this now :dancer:
