### ISSUE TITLE
BUG: Stored XSS in User "Real Name" Field. 

### ISSUE THREAD

**Issue by matt-** [anchorcms/anchor-cms#1010]
A (non admin) user can edit his "Real Name" and add html tags including "script" tags. The user could add custom javascript when viewed by an admin, could execute any admin action (including updating the non admin user to an admin). 

1. Create a non admin user and log in. 
2. Click on "Users" -> Your User
3. Edit the "Real Name" and add: &lt;script>alert(1)&lt;/script>
4. Log in as admin and click on "Users". You will see an alert box created by the non admin user. 

To fix: HTML encode all values created by users before displaying them to the screen.

**Comment by TheBrenny** [comment]
Which version of Anchor are you using, because this bug should've been squashed in 0.9-dev.

**Comment by matt-** [comment]
"Powered by Anchor, version 0.10"

**Comment by CraigChilds94** [comment]
@matt- @TheBrenny I'll look into this to make sure it hasn't made it's way in somehow, if it's fixed I'll close this issue.

**Comment by CraigChilds94** [comment]
This is fixed :)
