### ISSUE TITLE
Version 0.11 Prompts for Update

### ISSUE THREAD

**Issue by joshvickerson** [anchorcms/anchor-cms#1013]
### Summary

The version number in Anchor doesn't appear to have been updated for the new 0.11 release, so when logging in to the admin interface it prompts for an update.

### Expected Behaviour

The most recent version should not prompt for an update.

### Actual Behaviour

- Sign in to admin interface
- Good news, an update is available! (But shouldn't be)

### Context details (if applicable)

- Anchor version: 0.11
- Server setup: Ubuntu 14.04

**Comment by CraigChilds94** [comment]
Thanks for picking up on this, I'll try and get this sorted tomorrow, I'll also be looking at making another release with some more fixes and features.

**Comment by CraigChilds94** [comment]
@joshvickerson what do you get if you go to https://anchorcms.com/version ? we're thinking that the version is maybe cached.

**Comment by TheBrenny** [comment]
Might be worthwhile to `dd()` the two values that are used for version
checking: our saved value, and the value grabbed from the Anchor Server.

**Comment by CraigChilds94** [comment]
I'm hoping this is no longer an issue as I've bumped the version numbers on the site

**Comment by joshvickerson** [comment]
I see 0.12 when I visit anchorcms.com/version.

I tried updating from 0.11 to 0.12 and now my entire site doesn't work because of PHP errors (about to file an issue) so I can't verify if this is happening still or not.

**Comment by CraigChilds94** [comment]
@joshvickerson  Was this through manual update? (The update system is a little broken at the minute and needs a complete overhaul)

**Comment by CraigChilds94** [comment]
@joshvickerson Also if you're not pulling it from Packagist then you'll need to run `composer install`

**Comment by joshvickerson** [comment]
I did a manual update. I had no idea composer was even added to anchor (is there documentation you can point me to on this?)

**Comment by CraigChilds94** [comment]
I've updated the readme :p

**Comment by joshvickerson** [comment]
Readme only notes how to create a new project. Is the process the same for updating? I've never worked with composer before.

I installed it and "composer install" isn't a valid command as you noted before.

**Comment by CraigChilds94** [comment]
I'll produce some docs on updating tomorrow.
