### ISSUE TITLE
Uncaught exception when accessing admin interface after 0.12 upgrade

### ISSUE THREAD

**Issue by joshvickerson** [anchorcms/anchor-cms#1014]
### Summary

I manually upgraded from 0.11 to 0.12 and now I'm having problems accessing the admin interface (the rest of the site appears to be working fine). I was able to successfully run `composer install` and received the following output from it:
```
composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
```

Now when I visit /admin I get the following exception:

<h4>Uncaught Exception</h4>
Class 'RandomLib\Factory' not found
<h4>Origin</h4>
system/helpers.php on line 58
<h4>Trace</h4>
 /anchor/anchor/libraries/csrf.php(18): noise(64)
 /anchor/anchor/routes/admin.php(45): Csrf::token()
 [internal function]: {closure}()
 /anchor/system/route.php(152): call_user_func_array(Object(Closure), Array)
 /anchor/system/router.php(152): System\Route->run()
 /anchor/system/start.php(46): System\Router->dispatch()
 /anchor/index.php(33): require('/home/josh/publ...')
 {main}

### Expected Behaviour

- I should be able to log in

### Actual Behaviour

- Go to /admin
- Find that RandomLib\Factory is missing

### Context details (if applicable)

- Anchor version: 0.12
- Server setup: Ubuntu 14.04
- URL: blog.joshvickerson.com/admin

If there's anything more I can do to help let me know!

**Comment by CraigChilds94** [comment]
Try deleting `composer.lock` and make sure the `vendor` folder exists. Otherwise try running `composer dump-autoload`, I hope these solve your issues

**Comment by joshvickerson** [comment]
Vendor folder exists, tried deleting `composer.lock` and `composer dump-autoload` but still getting the exception.

**Comment by CraigChilds94** [comment]
Can you please confirm that the contents of the `composer.json` file are the same as the current `master` version

**Comment by joshvickerson** [comment]
`composer.json` contains:
```json
{
	"name": "anchorcms/anchor-cms",
	"authors": [
		{
			"name": "Idiot",
			"email": "iam@visualidiot.com"
		},
		{
			"name": "Kieron",
			"email": "rwarasaurus@gmail.com"
		}
	],
	"require": {
		"php": ">=5.3.6"
	},
	"extra": {
		"installer-paths": {
			"anchor/vendor/{$name}": ["vendor/package"]
		}
	}
}
```

Which is different than `master`. Replacing `composer.json` with the version on master fixes the issue.

**Comment by CraigChilds94** [comment]
@joshvickerson yeah that's correct; weird. How did you "update" ?

**Comment by joshvickerson** [comment]
I did a manual update following what I thought was still the procedure (just manually copying `/anchor` and `/system`). If I had copied `composer.json` as well when I updated then I don't think I would have run into this issue.

I just re-ran `composer install` after replacing the json file to resolve the issue.

**Comment by CraigChilds94** [comment]
Yeah that would've been why. :D

**Comment by mischa2002k2** [comment]
Hi,

I experience the very same error: "system/helpers.php on line 58" (on admin/login).

I tried the command "php composer.phar dump-autoload" and also this is how I installed composer: "php composer.phar install"

After the install these are the messages I see in the console:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
```

This is what my composer.json looks like:
```
{
	"name": "anchorcms/anchor-cms",
	"description": "Anchor is a free, lightweight, faster-than-a-bullet, simple blogging system, made for art–directed posts.",
	"type": "CMS",
	"keywords": ["CMS", "anchor", "anchorcms"],
	"license": "GPL-3.0",
	"authors": [
		{
			"name": "Idiot",
			"email": "iam@visualidiot.com"
		},
		{
			"name": "Kieron",
			"email": "rwarasaurus@gmail.com"
		},
		{
			"name": "Craig",
			"email": "childscraig17@gmail.com"
		},
		{
			"name": "David",
			"email": "me@daviddarnes.com"
		}
	],
	"require": {
		"php": ">=5.3.6",
		"ircmaxell/random-lib": "^1.1",
		"ircmaxell/password-compat": "^1.0",
		"indigophp/hash-compat": "^1.1"
	}
}
```

Did I miss something?

**Comment by mischa2002k2** [comment]
My bad... had some folder missmatch... :(
