### ISSUE TITLE
Uncaught exception when updating from 0.9.2 to 0.12

### ISSUE THREAD

**Issue by agodlydeciple** [anchorcms/anchor-cms#1015]
### Summary

Upgraded from 0.92 to 0.12 following instrutions located [here](https://anchorcms.com/docs/getting-started/upgrading).

After upgrading when I try to go to my blogs admin login page I get:
![image](https://cloud.githubusercontent.com/assets/683837/13360950/78bac65c-dc81-11e5-9d22-c6160b24752b.png)

### Expected Behaviour

- go to admin page
- see login form 
- able to login

### Actual Behaviour

- go to admin page
- receive exception
- cannot login

### Context details (if applicable)

- Anchor version: 0.12
- Server setup: Cent OS 7, PHP 7 
- URL: [https://blog.oerkfitz.com/admin](https://blog.oerkfitz.com/admin)

**Comment by agodlydeciple** [comment]
didn't check closed section. See there is already a fix. Sorry for duplicate ticket.

**Comment by CraigChilds94** [comment]
Hey dude,  

No worries, I need to update the upgrade docs to suite the more recent usage of composer.
