### ISSUE TITLE
Page "posts" issue

### ISSUE THREAD

**Issue by thany** [anchorcms/anchor-cms#1018]
### Summary

By default there's a page called "Posts". There's text in it that isn't displayed anywhere, and it can't be deleted. It also can't be removed from the menu using that checkbox. Pleae note that this is a virgin installation, i.e. this server has never seen another version of Anchor before, and it's been set up just today.

### Expected Behaviour

Either the page is superfluous, or broken. I expect it to be deletable, hidable, or at least be able to show its text somehow.

### Actual Behaviour

It doesn't appear to matter what you do in the "Posts" page, it always does the same thing. It spews out pretty much identical HTML output as the homepage, which is very bad for findability (duplicate content woes).

### Context details (if applicable)

- Anchor version: 0.21.1
- Server setup: XAMPP on Win10, with Apache 2.4.12 & PHP 5.6.8 & MySQL 5.6.24
- URL: Not public

**Comment by CraigChilds94** [comment]
@thany You're required to have  a page for posts, as this page is the default and selected as such page, you cannot remove it.

The fact that it's not outputting text worries me though. What happens if you save the page?

**Comment by daviddarnes** [comment]
@thany @CraigChilds94 this is down to the theme, not the CMS itself. Note that the posts.php template doesn't not have an output for the page content https://github.com/anchorcms/anchor-cms/blob/master/themes/default/posts.php I think this part of the design, but we can change this quite easily.

**Comment by thany** [comment]
Then I say the default theme (which I'm using, hence a virgin installation) should display that text somewhere. It does still worry me that it's outputting content that's pretty much a duplicate of the homepage, which may be penalised by Google and others.

Still, I'm not entirely sure why that page must be there... Isn't it weird to require the existence of a page that technically does the same as the homepage?

**Comment by CraigChilds94** [comment]
@thany It only does the same as the home page if you have that page set as both the home page and the posts page. I personally don't think this is an issue. It's more of an implementation choice.

**Comment by thany** [comment]
Blogs usually have the posts as the homepage. Or at least first few. It's the default setting as well.

At any rate, it's a duplicate content issue. And to be frank, personally I do think it's a problem.

One solution would be to do away with the "posts" link in the header. If posts are on the homepage (the default, mind you) the link serves no purpose. But it happens to not respect the setting for that. If nothing else, at least that should be fixed.
