### ISSUE TITLE
Installation: htaccess not writable

### ISSUE THREAD

**Issue by thany** [anchorcms/anchor-cms#1019]
### Summary

The installation said my htaccess isn't writable. My server is running as the same user as I'm logged in with, so the htaccees _can't not_ be writable.

### Expected Behaviour

My htaccess is perfectly writable.

### Actual Behaviour

I had to do it myself. Perhaps the check for a file if it's writable or not, is too agrressive, or broken.

### Context details (if applicable)

- Anchor version: 0.21.1
- Server setup: XAMPP on Win10, with Apache 2.4.12 & PHP 5.6.8 & MySQL 5.6.24
- URL: Not public

**Comment by CraigChilds94** [comment]
@thany  I'll have to look into this but I can only think it's got to be a permissions issue on your end.

**Comment by thany** [comment]
well, like I said, the server is running under my own user account, and I can write to everything. So it can't possibly be a permissions problem.

FYI, wordpress has a similar problem: it too checks too agrresively for writability of a file. It checks if the current user is also the owner, and fails if it's not. That not the problem in this case, but I'm just saying a custom made writable-check might fail for a file that's perfectly writable.

**Comment by saucytomato** [comment]
I've installed anchor three times, and have had the exact same issue that @thany had

_I've installed it on DigitalOcean, AWS, and Localy_

**Comment by daviddarnes** [comment]
This does seem to be a problem, however I didn't encounter it when I tried installing it. Also, it does provide you with the option to create the .htaccess file yourself.

**Comment by thany** [comment]
Just to be clear: the problem isn't that htaccess is nonwritable. The problem is that it's falsely detected as nonwritable.

Maybe it helps to know that I tried it on Win10, with UAC enabled, and the user I'm logged in as, is a local administrator (but not _the_ administrator). XAMPP and therefor Apache and MySQL are not running as a service but just as a program, and running as the same user like any other program would. Hopefully this helps.

**Comment by daviddarnes** [comment]
@thany I understand your issue. I'm just clarifying to viewers of this issue that there is a way around this problem.

**Comment by CraigChilds94** [comment]
This is the function which handles writing the `.htaccess`. It lives in `install/libraries/installer.php`. Could you try adding an `else` statement to see if `mod_rewrite` wasn't detected as I feel thats the case.


```php
    private static function rewrite($settings) {
		if(mod_rewrite() or (is_apache() and $settings['metadata']['rewrite'])) {
			$htaccess = Braces::compile(APP . 'storage/htaccess.distro', array(
				'base' => $settings['metadata']['site_path'],
				'index' => (is_cgi() ? 'index.php?/$1' : 'index.php/$1')
			));

			if(isset($htaccess) and is_writable($filepath = PATH . '.htaccess')) {
				file_put_contents($filepath, $htaccess);
			}
			else {
				Session::put('htaccess', $htaccess);
			}
		}
	}
```

**Comment by thany** [comment]
The culprit looks to be `is_writable`. Besides it returning false positives on Windows where ACLs determine writableness, it also checks if the file _exists_. It looks like if a file doesn't exist, `is_writable` should return false:

> Returns TRUE if the filename exists and is writable.

In a virgin installation of Anchor, there isn't a htaccess to begin with. So my reasoning is that 'installing' the htaccess automatically will only ever work if there's already an htaccess (and it's writable). So it will never work if a htaccess doesn't already exist.

All reasoning, nothing tested ;)

**Comment by CraigChilds94** [comment]
Thanks @thany I'll swap this out for something that will check correctly. Hopefully I can get a new release out tonight.

**Comment by CraigChilds94** [comment]
@thany Okay no worries, thanks for bringing this up though :P
