### ISSUE TITLE
Feature: tags instead of categories

### ISSUE THREAD

**Issue by thany** [anchorcms/anchor-cms#1021]
### Summary

I'd like to assign a post to multiple categories, essentially making them into tags. This makes sense for many blog, and currently makes categories too restrictive without that being much of an advantage.

### Expected Behaviour

Categories are currently a 1-to-n relation with posts, but n-to-m would make it more flexible.

### Context details (if applicable)

- Anchor version: 0.21.1
- Server setup: XAMPP on Win10, with Apache 2.4.12 & PHP 5.6.8 & MySQL 5.6.24
- URL: Not public

**Comment by daviddarnes** [comment]
This is a duplicate of this issue https://github.com/anchorcms/anchor-cms/issues/537#issuecomment-110842503

**Comment by thany** [comment]
Sorry, should've searched. My bad.

**Comment by daviddarnes** [comment]
@thany no worries :smile_cat:
