### ISSUE TITLE
Bug: The Infinite Loop

### ISSUE THREAD

**Issue by saucytomato** [anchorcms/anchor-cms#1022]
### Summary
Any page can be looped in the slug:
http://inkler.ga/test-page/test-page/test-page/test-page/test-page 
is the same as
http://inkler.ga/test-page

### Expected Behavior
The page only accessible on the slug I set. 

### Actual Behavior

The page loops indefinitely.

- Anchor version: 0.12.1
- Server setup: Probably Ubuntu, Host Doesn't Say
- URL: http://inkler.ga

**Comment by saucytomato** [comment]
When I try to nest a page under the original with the same slug, it won't allow me to.
Example: I can't create a ./about different than ./about/about

**Comment by daviddarnes** [comment]
Sorry @saucytomato, but the demo link you supplied is giving a 404.

As for the page slugs, are you typing these in manually? It seems wrong that you're creating a parent and child page of the same name.

**Comment by saucytomato** [comment]
It should work now.

**Comment by daviddarnes** [comment]
@saucytomato still getting 404 on both links :/

**Comment by saucytomato** [comment]
@daviddarnes should work now...

**Comment by CraigChilds94** [comment]
@saucytomato both load for me. What seems to be the  problem?

**Comment by CraigChilds94** [comment]
@saucytomato Oh I see, `/test-page/test-page...` should 404 but `/test-page` shouldn't.
