### ISSUE TITLE
Bug: Feed Won't Load

### ISSUE THREAD

**Issue by saucytomato** [anchorcms/anchor-cms#1024]
In the version of Anchor which is on the website http://blog.anchorcms.com, the Feed button gives an error:
```
Fatal error: Call to a member function take() on a non-object in /var/www/blog.anchorcms.com/public/anchor/routes/site.php on line 204
Uncaught Exception

Call to a member function take() on a non-object

Origin

anchor/routes/site.php on line 204

Trace

#0 [internal function]: System\Error::shutdown()
#1 {main}
```
And this is not my website, so I have no idea why this is happening.

**Comment by CraigChilds94** [comment]
It's using an old version where this bug was present. I'm planning on updating it at some point soon
