### ISSUE TITLE
Discussion: Features move to The Feathub

### ISSUE THREAD

**Issue by saucytomato** [anchorcms/anchor-cms#1025]
I think that the feathub should be a bit more prominent on the homepage because it just looks like an image and not a website. 
Even though I suggested that features should be put under the feathub, I'm submitting an issue so that this gets noticed. Even though tons of people check the issues tab, not enough check the feathub. _Information based on the lack of votes and additions in the past weeks. The first was added 10 months ago, the second 14 days ago._

**Comment by TimohStudios** [comment]
I absolutely agree. A line in commenting on what it is in the README, updating the CONTRIBUTING.

**Comment by CraigChilds94** [comment]
Thanks @saucytomato I already had planned to move them over anyway, but I'm glad you had the same idea! xD I'm going to update the files so that it's clearer to everyone.

**Comment by TimohStudios** [comment]
Thanks Craig! I want to let you know that I really appreciate the work you've been putting in lately to organize everything! you've spammed my inbox like crazy twice, but I love it.

**Comment by CraigChilds94** [comment]
Haha no problem @TimohStudios after a long period of not doing anything, I thought I better put some effort in lol.

**Comment by CraigChilds94** [comment]
@saucytomato @TimohStudios @daviddarnes  I've updated the `contributing.md`, `issue_template.md` and `readme.md` accordingly.

**Comment by saucytomato** [comment]
Looks Great @CraigChilds94

**Comment by CraigChilds94** [comment]
Indeed @saucytomato. It makes everything easier to manage.

**Comment by daviddarnes** [comment]
@CraigChilds94 thanks for updating those files!

**Comment by saucytomato** [comment]
Just one question. Should we close milestones 0.10 and 0.9 now that they're fully developed?

**Comment by CraigChilds94** [comment]
@saucytomato yeah probably a good idea

**Comment by TheBrenny** [comment]
Should we also close this issue, seeing as it's fully matured and people are now using Feathub?

**Comment by daviddarnes** [comment]
@TheBrenny correct! Thanks
