### ISSUE TITLE
Bug: Graphical Issue On Develop Branch

### ISSUE THREAD

**Issue by saucytomato** [anchorcms/anchor-cms#1027]
### Summary

When I go to the categories tab on the develop branch, there seems to be a CSS issue:

### Expected Behaviour

Expected the tab to have the same design and background as the other tabs.

### Actual Behaviour

This:
![screen shot 2016-03-03 at 11 34 12 am](https://cloud.githubusercontent.com/assets/7997954/13503221/e1fa5f9a-e133-11e5-8a5b-2ccfa49479ff.png)

### Context details (if applicable)

- Anchor version: The Develop Branch
- Server setup: CentOS 6.5 64Bit, PHP 7
- URL: Not Public

**Comment by daviddarnes** [comment]
I'm closing this issue as the development branch is still being worked on, hence missing CSS.
