### ISSUE TITLE
This program has re install vulnerability

### ISSUE THREAD

**Issue by Strikersb** [anchorcms/anchor-cms#1030]
### Summary

This system in the install installation, not validated, if you do not delete the `install` directory, you can arbitrarily reinstall the system.

### Details

Visit the `install` directory can be re installed

### Bug fixes

 -  Add the following code in the `/install/routes.php` line 6:

```
    /* Check if you have installed  by Striker */
    if(file_exists(APP.'install.lock')){
        die('AnchorCMS is already installed!');
    }
```

As shown in the figure

![qq 20160304101844](https://cloud.githubusercontent.com/assets/14834081/13516145/74795e98-e1f2-11e5-8440-1d17d91c2b9c.png)

 - Insert the code in the `/install/routes.php` line 277:

```
file_put_contents(APP.'install.lock','');
```

As shown in the figure

![qq 20160304102921](https://cloud.githubusercontent.com/assets/14834081/13516311/ebaee3f6-e1f3-11e5-8900-2a91ca1c507c.png)

 - Finshed!

After the installation of install `AnchorCMS is already installed!` will return again to visit

**Comment by daviddarnes** [comment]
You're right, we do need to remove this directory for the user so it can't happen again. However just to clarify, removing `install` manually will also stop people gaining access.

**Comment by Radiergummi** [comment]
I don't think removing the `install` folder all together is a user friendly
solution. What if I made a mistake or there is an error and want to
reinstall? Have to download again. No, creating a lock file is the way to
go here...

David Darnes <notifications@github.com> schrieb am Fr., 4. März 2016 um
08:55:

**Comment by daviddarnes** [comment]
@Radiergummi that's a great idea! However I'd recommend a full reinstall if you do though, just to keep things up to date.

**Comment by Radiergummi** [comment]
@daviddarnes I' always do a full install, but I'm a full-time developer which you cannot expect of all anchor users ;)

**Comment by daviddarnes** [comment]
@Radiergummi of course, I'd agree with that. Just giving a recommendation.

**Comment by CraigChilds94** [comment]
I've implemented this
