### ISSUE TITLE
Issue: The Confirmation Window

### ISSUE THREAD

**Issue by saucytomato** [anchorcms/anchor-cms#1031]
I _personally_ don't like the look of the conformation window when deleting a post/page/user.
<img width="487" alt="screen shot 2016-03-04 at 5 29 13 pm" src="https://cloud.githubusercontent.com/assets/7997954/13543232/eaae1bda-e22e-11e5-91b7-c0ebb53ff56a.png">
It doesn't really fit the style that Anchor uses. (Based on the Butterfly UI kit by @idiot)
Here's my test case:
![newui](https://cloud.githubusercontent.com/assets/7997954/13543519/7c27a7aa-e231-11e5-86d7-ebd510b559ea.png)
Now here's what you should probably change from my design:

- The model background is slightly blue (Oops)
- The edges might be slightly too rounded
- Match the buttons to the rest of the interface
- The font is completely wrong
- Shrink the text size and give it more of a margin

This model was a quick mockup. If you want to change it, go right ahead. 

> I made an issue because I really don't know where to report/file this

**Comment by CraigChilds94** [comment]
@saucytomato I'm a bit confused here; what is it you're referencing? which version? is this even relevant?

If it's from the `develop` branch then we can close this as the UI for that is still being worked on.

**Comment by daviddarnes** [comment]
I would close this as I'm pretty sure there isn't such a dialog in 0.12.1, I think they're just the default alert window.

**Comment by saucytomato** [comment]
Sorry, If you click delete button on a post, that appears.
Anchor Version: 0.12.1

**Comment by daviddarnes** [comment]
Really? That's odd, never seen a dialog in Anchor like that before. Can we get this changed to a js alert? It's not the prettiest but it's how it's done everywhere else.

**Comment by saucytomato** [comment]
I'm so sorry, it is a js alert. For some reason, my computer interprets it in an odd way.

**Comment by daviddarnes** [comment]
Ah I see, what OS are you using?

**Comment by saucytomato** [comment]
OSX 10.11.4 - Safari
