### ISSUE TITLE
Bug: Migration Issue

### ISSUE THREAD

**Issue by saucytomato** [anchorcms/anchor-cms#1034]
### Summary

I don't really know what to make of this:

### Expected Behaviour

- The site to load normally

### Actual Behaviour

 ```
Uncaught Exception

Class 'Migration_insert_default_dashboard_meta_key' not found

Origin

anchor/libraries/migrations.php on line 52

Trace

#0 /home/u698317652/public_html/anchor/libraries/anchor.php(119): Migrations->up(212)
#1 /home/u698317652/public_html/anchor/libraries/anchor.php(27): anchor::migrations()
#2 /home/u698317652/public_html/anchor/run.php(41): anchor::setup()
#3 /home/u698317652/public_html/system/start.php(26): require('/home/u69831765...')
#4 /home/u698317652/public_html/index.php(35): require('/home/u69831765...')
#5 {main}
```

### Context details (if applicable)

- Anchor version: 0.12.1
- Server setup: Apache On Ubuntu Linux
- URL: inkler.ga

**Comment by saucytomato** [comment]
#

**Comment by daviddarnes** [comment]
@CraigChilds94 @saucytomato should this issue be closed if it's being covered in #1035?

**Comment by saucytomato** [comment]
@daviddarnes I would think that since #1035 is two separate bug reports, it should be two separate issues. The fact that's it being covered in #1035 and not here means that this issue should be closed; I'll let you decide.

**Comment by daviddarnes** [comment]
@saucytomato good call, since this is scoped to one issue we'll keep this one going. The other one can cover the other issue.

**Comment by elenachoi** [comment]
Not sure if this has been addressed, but as I see it the required migrations class names are taken from iterating through the anchor/migrations files (line 15). Following this and the fact that the class name has to coincide with the filename, in file anchor/migrations/212_insert_default_dashboard_meta_key.php on line 2, the class should be renamed from **Migration_insert_dashboard_page_meta_key** to **Migration_insert_default_dashboard_meta_key**.

**Comment by CraigChilds94** [comment]
This should be now fixed
