### ISSUE TITLE
Uncaught Exception: Undefined Variable - $vars in /install/routes.php

### ISSUE THREAD

**Issue by Prkns** [anchorcms/anchor-cms#1035]
### Uncaught Exception when installing

I don't know if this is purely down to this version being the most up to date version of Anchor, but i thought i'd do a fresh install and see if i could get involved in the bug fixing. Once i'd passed the database install screen, i am presented with an Uncaught Exception stating an Undefined Variable of $vars in the /install/routes.php file?

It could be just my mess up (in which case i apologise) but i didn't know if this was something that might need to be fixed?

![screen shot 2016-03-09 at 3 38 29 pm](https://cloud.githubusercontent.com/assets/1788197/13640571/140a753c-e60d-11e5-9ef4-82c389ad85b7.png)

I'm not skilled enough with PHP to be able to offer any help fixing it so again, i apologise. If this is something that i can fix myself, please let me know and i'll give it a punt.

- Anchor version: 0.12.1
- Server setup: MacBook Air - 10.11.3 - MAMP

**Comment by daviddarnes** [comment]
What version of PHP are you using? It should say in MAMP.

**Comment by Prkns** [comment]
5.6.2

**Comment by protomorph** [comment]
It looks like this line `$vars['messages'] = Notify::read();` is missing from line 181

**Comment by Prkns** [comment]
@protomorph i added that line to the routes.php file and it fixed it perfectly... thank you kindly!

The issue now is that once i've setup the username and password, i'm getting another uncaught exception from anchor/config/error.php.

![screen shot 2016-03-09 at 8 35 01 pm](https://cloud.githubusercontent.com/assets/1788197/13649633/843faede-e636-11e5-9aa7-67788146c7ed.png)

**Comment by daviddarnes** [comment]
Awesome, thanks @protomorph. Do you mind making a PR for this? cc @CraigChilds94

**Comment by protomorph** [comment]
@Prkns no problem, happy to help. As for other error, could you post the contents of your errors.log?

BTW it looks like that line is missing in both the master and pre-1.0-develop branches

**Comment by Prkns** [comment]
@protomorph It hadn't created an errors.log file. I created one manually, set the permissions to 777 and then refreshed. The errors.log file then had this inside it:

`{"date":"2016-03-09 21:09:30","message":"Class 'Migration_insert_default_dashboard_meta_key' not found","trace":[{"function":"shutdown","class":"System\\error","type":"::","args":[]}],"line":61,"file":"\/Users\/DavidPerkins\/Sites\/anchor-cms-master\/anchor\/libraries\/migrations.php"}`

and the uncaught exception had changed to...

![screen shot 2016-03-09 at 9 11 19 pm](https://cloud.githubusercontent.com/assets/1788197/13650635/7edc3098-e63b-11e5-8298-8b37dd86f73d.png)

**Comment by protomorph** [comment]
@Prkns what version of anchor are you using?

**Comment by Prkns** [comment]
@protomorph 0.12.1... i only downloaded the master copy this afternoon to see what it was like?

**Comment by protomorph** [comment]
@Prkns is it the master version you are trying to install?

**Comment by Prkns** [comment]
@protomorph yea, i just wanted to try it out to see if there were any issues that i could help with.

**Comment by protomorph** [comment]
@Prkns it look like the file anchor is trying to load is a new addition and is not in version 0.12.1. It seems that it's not iterating through all the files.

**Comment by Prkns** [comment]
@protomorph ah ok... i've just tried cloning the repo again, added line 181 as per your previous comment. I had to still manually create an errors.log file (is this a bug too btw?... would a user manually have to create an errors.log file when installing or should it be part of the install?)

I then got to the same point as previously and it showed the same Uncaught Exception.

The install has been successful because the database has been populated with the sample content and i've got a user name and password, but it's just hanging at the same point in the install as i posted earlier.


Apologies if this bug reporting is garbage...

**Comment by Prkns** [comment]
I've also just realised that this issue is now the same as #1034 by @saucytomato

**Comment by protomorph** [comment]
@Prkns the errors.log should be created automatically when there's an error, that would be a permmisions issue, you might need to change the chmod of the directory.

In that case it's a bug.

**Comment by saucytomato** [comment]
Thanks @protomorph for the fix. I'll close #1034 .

**Comment by dblencowe** [comment]
I've created a pull request for the first issue mentioned here, I'm going to create separate issues for the other stuff to keep the list clear

**Comment by CraigChilds94** [comment]
I believe these issues have been fixed in PR's, please let me know if this continues.
