### ISSUE TITLE
Class 'Migration_insert_default_dashboard_meta_key' not found

### ISSUE THREAD

**Issue by progammer-rkt** [anchorcms/anchor-cms#1036]
I am getting this error, after I completed installation process and then try to access frontend or backend.

<pre>[Class 'Migration_insert_default_dashboard_meta_key' not found
The error has been logged in /anchor/errors.log

Uncaught Exception

Class 'Migration_insert_default_dashboard_meta_key' not found
Origin

anchor/libraries/migrations.php on line 61
Trace

#0 [internal function]: System\error::shutdown()
#1 {main}](url)</pre>

It seems like a migration issue for me. I can turn off this error and access both frontend and backend if I comment out following line

    static::migrations();

in `/anchor/libraries/anchor.php` .

But this is what triggers database migration in anchorcms I guess. So the solution fully turn off migration feature if I comment out this.

So some one has a work around, please let me know

**Comment by daviddarnes** [comment]
Hi @progammer-rkt, see issue #1034 for more on this.
