### ISSUE TITLE
Bug: Re-uploading cover images

### ISSUE THREAD

**Issue by frozenpandaman** [anchorcms/anchor-cms#1037]
After upgrading to 0.12.1, I've had to re-upload my cover images on all posts as as the variable/field was cleared after updating an article (by clicking "Save"). Sometimes, when trying to upload the image, I received the following error:

![screen shot 2016-03-10 at 11 49 52](https://cloud.githubusercontent.com/assets/7245874/13667528/1b977a5c-e6b7-11e5-9355-2c8608c49727.png)

After receiving the error, repeating the process/trying to upload the image again resulted in success.

- Anchor version: 0.12.1

**Comment by daviddarnes** [comment]
Just to check, is it the theme that's causing the error? Maybe try switching themes and then uploading the image.

**Comment by frozenpandaman** [comment]
I didn't think that would be related, as it's in the admin panel and the theme wouldn't determine how the image is uploaded (right?) but I'll try to test this. May be hard to recreate, though, as it seemed to only be occurring with previously-published posts at the time of upgrade.

**Comment by daviddarnes** [comment]
@frozenpandaman I think you're right, but I just wanted to eliminate all other possibilities just incase.

**Comment by frozenpandaman** [comment]
@daviddarnes To confirm, it happened once again while using a different theme.

**Comment by daviddarnes** [comment]
@frozenpandaman cool, thanks for testing that!

**Comment by frozenpandaman** [comment]
@daviddarnes Weird... a cover image got cleared again, somehow, so I switched back to the default theme and re-uploaded it. No error, but it uploaded as C:/fakepath/[filename].jpg and didn't display in the article correctly. Re-uploading it/trying again it worked—odd.

**Comment by daviddarnes** [comment]
@frozenpandaman that's is weird. Could you detail your setup? E.g. PHP version, local or remote, MAMP or command line.

**Comment by frozenpandaman** [comment]
@daviddarnes PHP version 5.5.32, remote (http://elifessler.com/games/blog/). Not sure about the last one as I'm not too familiar with PHP/MySQL/all that stuff, but I could give you the output of phpinfo() if that'd help.

**Comment by frozenpandaman** [comment]
Just realized that the cover field/image upload is technically a custom field. Not sure if this helps to diagnose the issue, but thought it was worth noting here.

![screen shot 2016-03-17 at 15 51 37](https://cloud.githubusercontent.com/assets/7245874/13849909/49f78ec2-ec58-11e5-9ea7-324b3757f0af.png)

![screen shot 2016-03-17 at 15 51 40](https://cloud.githubusercontent.com/assets/7245874/13849911/4d60b8ae-ec58-11e5-87c9-1b2dbc15065f.png)

**Comment by mrmnmly** [comment]
I've got same issue - on every edit I have to re-upload image file (which is a custom field)

**Comment by ramon-villain** [comment]
@frozenpandaman Did you setup the File Types? Cause I'm getting a similar error, when I upload an incorret file type.

**Comment by frozenpandaman** [comment]
No, my custom field allows all field types. @ramon-villain

**Comment by CraigChilds94** [comment]
I've added what I believe is a fix, would someone mind ensuring it works for them? @frozenpandaman ?
