### ISSUE TITLE
Bug: HTML not parsing in post descriptions

### ISSUE THREAD

**Issue by frozenpandaman** [anchorcms/anchor-cms#1038]
After upgrading to 0.12.1, HTML tags in post descriptions do not get parsed and instead just display as HTML tags. (Using markdown syntax does not work either. Thus, there is no way to add formatting to description apart from manually updating table entries.)

Expected behavior: Description of article/post reads "An article about the movie _Airplane!_"

Actual behavior: Description of article/post reads "An article about the movie &lt;i&gt;Airplane!&lt;/i&gt;"

- Anchor version: 0.12.1

**Comment by saucytomato** [comment]
The way the markdown/html works in posts is that Anchor saves it to the database as two separate boxes: one for what you typed (the markdown mixed with html tags) and the pre-rendered html (it speeds up rendering when viewing the post.) The description **doesn't** render markdown. I think it's outputting plain text **that escapes special characters** to the front-end therefore not parsing the html. For example:` <i>test</i>` in the description renders as `&lt;i&gt;test&lt;/i&gt;`

**Comment by TimohStudios** [comment]
It seems to me your experiencing different behavior, correct?

**Comment by saucytomato** [comment]
To clarify: The page says `<i>test</i>` and the code says `&lt;i&gt;test&lt;/i&gt;`. You would see <i>test</i>.

**Comment by frozenpandaman** [comment]
@TimohStudios This is what I am getting as well. What I want/expect to see is *``test``* (with the code reading ``<i>test</i>``). Instead, I see ``<i>test</i>`` with the code reading ``&lt;i&gt;test&lt;/i&gt;`` as @saucytomato said.

**Comment by CraigChilds94** [comment]
Would you expect html in a posts description though? Remember this is the same field that you would use for the meta tag in the head of the document.

If you want to make use of a parsed field I'm sure you could add a custom field for this.

What do you guys think?

@frozenpandaman @saucytomato @TimohStudios

**Comment by frozenpandaman** [comment]
I would, as given in my original example. Another example is that I have a blog post about my reactions to playing a game, and I want the description to read "Thoughts on the ending to _Firewatch_." It's [convention](https://owl.english.purdue.edu/engagement/2/1/45/) to italicize book names, movie titles, etc.

In the previous version of Anchor users were able to do this, but I don't see how it's beneficial *not* to do it. If you want your description to include an HTML tag (much rarer than my above example) without it being parsed (e.g. ``<i>``), why not just write the code ``&lt;i&gt;``? And if you wanted *that* in your description, you could write ``&amp;lt;i&amp;gt;``… etc.

@CraigChilds94

**Comment by CraigChilds94** [comment]
@frozenpandaman Why not have a custom field called "Description" or "Tagline" and put html inside that. Then when outputting it, do something like the following.

```
<?php echo html_entity_decode(article_custom_field('tagline')); ?>
```

**Comment by frozenpandaman** [comment]
@CraigChilds94 I think that workaround would work, yes—thanks. However, I find it easier to simply manually change the table entry as I generally won't be editing already-published posts that much. Previous versions of Anchor CMS didn't do this, though, so if this is indeed a bug I'm hoping it'll go back to working like before (i.e. parsing HTML in the description field).

**Comment by daviddarnes** [comment]
A while ago I needed something like this in a WordPress site. I ended up creating a custom field called `subtitle` that allowed me to add a slightly more descriptive title to articles. There was a few benefits to this:

1. I knew exactly what it did and I had control over it
2. It didn't mix with the page description in the `<head>` and didn't break the markup
3. It didn't give the page a poor meta description

Thankfully it's a lot easier to create custom fields in Anchor than in WordPress, so I don't see why this isn't a good use case for it. Using the page description for both your page meta description _and_ tagline might leave you in a difficult spot later one.

**Comment by TheBrenny** [comment]
There were [quite a few issues concerning Stored XSS](https://github.com/anchorcms/anchor-cms/issues?utf8=%E2%9C%93&q=is%3Aissue%20stored%20XSS) which led to a lot of things being encoded. I agree it's not that nice to need to create a custom field to fix this, but @CraigChilds94's answer is viable. Even if you don't want to create a new field, just decode the description of the post - works pretty much the exact same way, no?

**Comment by TheBrenny** [comment]
@frozenpandaman, I know I'm coming back to something old, but why can't you create a function in the `functions.php` file of your theme that grabs the first 150 characters or so from `article_html` and append an ellipses on the end? This way you get the HTML, *AND* it's a nice small description. Of course, a better algorithm would be to split at the nearest whitespace, but that's something for you to solve...

**Comment by daviddarnes** [comment]
@TheBrenny I think that would be a good fallback if the user doesn't add a description, but I don't think it's a good substitute for a proper description. We don't want to lock the user out from creating good meta information for their articles.

**Comment by frozenpandaman** [comment]
@TheBrenny Yeah, like @daviddarnes said, I use the Description field more like a short tagline to say what the article/post is about. Thank you for the suggestion, though!

**Comment by TheBrenny** [comment]
I sort of use it as a tagline as well, but it ends up becoming the whole first paragraph anyway by mistake. :joy_cat:

I'll see where @CraigChilds94 is at with it (seeing as he's been assigned) and I'll see if I can shuffle an implementation in somehow if I manage to find some spare time...

**Comment by frozenpandaman** [comment]
Hey @TheBrenny – just curious, did you ever end up looking into this? :) If not no worries. I just change my site table manually to edit in the HTML. :P (A custom field could also work but I find it easier my way, haha.)

**Comment by frozenpandaman** [comment]
Hey @TheBrenny – just curious, did you ever end up looking into this? :) If not no worries. I just change my site table manually to edit in the HTML. :P (A custom field could also work but I find it easier my way, haha.)

Maybe it could be changed to allow Markdown syntax in this field?
