### ISSUE TITLE
Bug: "Show all posts" option not saving

### ISSUE THREAD

**Issue by frozenpandaman** [anchorcms/anchor-cms#1039]
The option is off (red X) by default. Clicking it to turn on: 
![screen shot 2016-03-10 at 12 13 42](https://cloud.githubusercontent.com/assets/7245874/13667957/9b19c616-e6b9-11e5-884e-e32392f6f2aa.png)

Clicking Save at the bottom…
![screen shot 2016-03-10 at 12 16 00](https://cloud.githubusercontent.com/assets/7245874/13667990/de170d8e-e6b9-11e5-8770-a70ef5fc3576.png)

But as seen after the page refreshes, the option is not saved – it's still turned off:
![screen shot 2016-03-10 at 12 13 46](https://cloud.githubusercontent.com/assets/7245874/13667958/9b1af180-e6b9-11e5-8275-0b82ba9ce89b.png)

- Anchor version: 0.12.1

**Comment by saucytomato** [comment]
I've run into this issue: It seems that the backend is not writing the change to the database. I've had to go into the database and fix it myself

**Comment by frozenpandaman** [comment]
@saucytomato What/where in the database did you make the change? Guess I'll have to do this for now (fine by me—it works!) Thanks.

**Comment by CraigChilds94** [comment]
There's probably something slightly wrong in the logic of this; shouldn't be a hard issue to fix=.

**Comment by blados** [comment]
In case someone need it:
UPDATE 'meta` SET `value` = '1' WHERE `meta`.`key` = 'show_all_posts';

**Comment by Bibliofile** [comment]
Simple fix for this, not sure if it is the root of the problem though: 

In `anchor/routes/metadata.php` change 

```PHP
foreach($input as $key => $value) {
	$value = is_null($value) ? '0' : $value;
	Query::table(Base::table('meta'))->where('key', '=', $key)->update(array('value' => $value));
}
```

To 

```PHP
foreach($input as $key => $value) {
	$value = is_null($value) ? '0' : $value;
	Query::table(Base::table('meta'))->where('key', '=', $key)->update(array('value' => $value));
	unset($value);
}
```

**Comment by CraigChilds94** [comment]
I'm unable to replicate this so I believe it's been fixed since this issue was made.

**Comment by dwatzke** [comment]
This is not fixed in 0.12.1

**Comment by Tarpsvo** [comment]
Still not fixed. Same version as above. PHP 7.1.

**Comment by mackdata** [comment]
Miss this feature! A-lot! .. the default theme looks so empty without more posts showing.

**Comment by Tarpsvo** [comment]
I just edited the source and printed out all the posts anyway, regardless of the option.

https://github.com/Tarpsvo/tarps-pairby-blog/blob/3427145131db2b62fdc27ce2683c793dfad9ac8d/themes/default/posts.php

**Comment by mackdata** [comment]
@Tarpsvo : nice hack. - does the job. :)
