### ISSUE TITLE
Bug: Published on (GMT) field won't save

### ISSUE THREAD

**Issue by frozenpandaman** [anchorcms/anchor-cms#1040]
Same as #1039 but with the "Published on (GMT)" field on edit post pages. Always updates to current time/date (ignores entered time/date) when clicking Save.

- Anchor version: 0.12.1

**Comment by saucytomato** [comment]
Same as with my reply on #1039, the backend isn't writing to the database

**Comment by saucytomato** [comment]
#1032

**Comment by saucytomato** [comment]
#1032

**Comment by saucytomato** [comment]
And isn't this the same issue as #1032?

**Comment by daviddarnes** [comment]
@saucytomato it is, good spot. I'll close this, issue can be tracked in #1032.

**Comment by frozenpandaman** [comment]
Sorry, should have seen the other issue. Thanks for the catch.
