### ISSUE TITLE
The requested URL /admin/login was not found on this server

### ISSUE THREAD

**Issue by generita** [anchorcms/anchor-cms#1047]
So I'm trying to install Anchor CMS (the version doesn't matter, I've tried about five releases and the result is the same). Everything goes OK, and when I try to log in after installation, it shows me the login page, but after typing the login & password I get this message:

_The requested URL /admin/login was not found on this server._

When installing, I leave a field 'Site path' as it is by default ("/"). I've also tried to put there "/index.php". Admin panel worked well, but CSS and other files didn't load. 
I understand that the problem is in the Anchor's folder, but I don't know how to fix it. Also, I suppose that I've just done something wrong, because seems like I'm the only one with such a problem.

**Comment by protomorph** [comment]
Is this on a live or development server, if it's live, do you have a url to the site?

**Comment by daviddarnes** [comment]
Sorry you're having issues with Anchor @generita, however these such queries should be posted [on the official forums](http://forums.anchorcms.com/).
