### ISSUE TITLE
Bug: DragLeave not firing an event

### ISSUE THREAD

**Issue by ramon-villain** [anchorcms/anchor-cms#1048]
### Summary

![uploader](https://cloud.githubusercontent.com/assets/1520006/14061556/8937d19a-f361-11e5-9a56-8e1db6e53763.gif)
 Also the span area "Upload your file" should be a background image, it'll avoid the dragleave event in that region.

### Expected Behaviour

- Fire the body.removeClass('draggy') when the user give up uploading a file

### Actual Behaviour

- The event it's not fired, so the uploading mask still visible

*PS: It's firing a Cancel's event before the Open's event

**Comment by daviddarnes** [comment]
Yea, this a pretty annoying usability bug. Thanks for reporting.

**Comment by frozenpandaman** [comment]
This has been present for a number of versions. Makes uploading images very troublesome, especially if dragging a file elsewhere and it just happens to pass over the page. I'll have to navigate via tab to save my changes, or disable it with via Inspect Element so I can save what I've been working on…

**Comment by TheBrenny** [comment]
Closeable. #1061 is merged.
