### ISSUE TITLE
Bug: after saving changes of post or page custom field data is lost

### ISSUE THREAD

**Issue by f30d0r** [anchorcms/anchor-cms#1050]
### Summary

If you want to change existed post or page, when you save changes files or images in custom fields are lost.

### Context details

In my local installation i fix that bug by adding **$data != '[]'** condition in **/anchor/models/extend.php** in line [261](https://github.com/anchorcms/anchor-cms/blob/master/anchor/models/extend.php#L261)

after adding its looks like
`if( ! is_null($data) and $data != '[]') `

- Anchor version: 0.12.1

**Comment by frozenpandaman** [comment]
Same as #1037?

**Comment by f30d0r** [comment]
@frozenpandaman in #1037 you described two bugs. It's same as first.

**Comment by Trysystems** [comment]
Addition fix:

Added selector Page type on page edit reload fields according to type. And it load empty fields. If your fields have data - its loose.

Solution - change file anchor/admin/routes/admin.php on line 218 to:
$vars['fields'] = Extend::fields('page', $input['id'], $input['pagetype']);

**Comment by upabove** [comment]
So what about that? When we can expect update? It looks like Saving Changes not working for anything - pages, articles, custom fields, custom variables, nothing.

**Comment by TheBrenny** [comment]
I think #1052 fixed this? And it's merged.

**Comment by daviddarnes** [comment]
@TheBrenny closing unless someone thinks it's still an issue
