### ISSUE TITLE
On change Page type loaded fields is empty, loosing data.

### ISSUE THREAD

**Issue by Trysystems** [anchorcms/anchor-cms#1055]
### Summary

Added selector Page type on page edit reload fields according to type. And it load empty fields. If your fields have data - its loose. 

Solution - change file anchor/admin/routes/admin.php on line 218 to:
$vars['fields'] = Extend::fields('page', $input['id'], $input['pagetype']);

### Context details (if applicable)

- Anchor version: 0.12.1

**Comment by ramon-villain** [comment]
Same https://github.com/anchorcms/anchor-cms/issues/1050

**Comment by Trysystems** [comment]
This solution is better, because its load fields with data, so you can normally edit it.

**Comment by daviddarnes** [comment]
Thanks for the solution @Trysystems. Could you copy it into issue #1050 please? We're trying to stop duplicate issues.
