### ISSUE TITLE
posts paginator's bug

### ISSUE THREAD

**Issue by maojindao55** [anchorcms/anchor-cms#1067]
### Summary
In the paginator.php file, the `function prev_link()` and `function next_link() ` work wrong, and each works complete opposite!
```
	public function prev_link($text = null, $default = '', $attrs = array()) {
		if(is_null($text)) $text = $this->next;

		$pages = ceil($this->count / $this->perpage);

		if($this->page < $pages) {
			$page = $this->page + 1;

			return $this->link($text, array_merge(
				array('href' => $this->url . '/' . $page), $attrs
			));
		}

		return $default;
	}

	public function next_link($text = null, $default = '', $attrs = array()) {
		if(is_null($text)) $text = $this->prev;

		if($this->page > 1) {
			$page = $this->page - 1;

			return $this->link($text, array_merge(
				array('href' => $this->url . '/' . $page), $attrs
			));
		}

		return $default;
	}

```

### Expected Behaviour

- Change each name.

### Actual Behaviour

- A list of steps you actually encountered

### Context details (if applicable)

- Anchor version:last
- Server setup:
- URL

**Comment by joshvickerson** [comment]
Someone can correct me if I'm wrong, but I believe since posts are listed in reverse chronological order (i.e. newest post is listed first), as page numbers increase the posts get older and thus are "previous" posts.

The functions are named to reflect the age of posts, rather than whether or you are moving to a higher or lower page number.

That is confusing for sure, but I think the current naming scheme makes more sense than the alternative.

**Comment by daviddarnes** [comment]
@joshvickerson that's right. I'm not sure how you're expecting pagination urls to work @maojindao55?

- `prev_link()`: shows previous posts as you go back in time, and as you do so the page number gets higher
- `next_link()`: shows the next post and the next until you get to now, with the numbers going down as to arrive to now

**Comment by maojindao55** [comment]
@joshvickerson  @daviddarnes  oh yeah , Mybe it is my custom as most of chinese, look like the footer of [my blog](http://okrd.cn), `next->` means the next pages rather than the next posts, and `<-previous` means opposite.

**Comment by daviddarnes** [comment]
@maojindao55 well you can change the label if you like 😄

**Comment by maojindao55** [comment]
@daviddarnes  done!
