### ISSUE TITLE
fields edit  bug

### ISSUE THREAD

**Issue by maojindao55** [anchorcms/anchor-cms#1068]
### Summary

When I edit fields in extends channel, it exported a warning：
![pic](http://7d9q38.com1.z0.glb.clouddn.com/anchor.bug.png)

And I find the source code `routes/fields.php`:
```
Route::post('admin/extend/fields/edit/(:num)', function($id) {
		$input = Input::get(array('type', 'field', 'key', 'label', 'attributes', 'pagetype'));
		
		if(empty($input['key'])) {
			$input['key'] = $input['label'];
		}
		
		$input['key'] = slug($input['key'], '_');
		
		foreach($input as $key => &$value) {
			$value = eq($value);
		}
```
But, the fields add function works well, the code:
```
	Route::post('admin/extend/fields/add', function() {
		$input = Input::get(array('type', 'field', 'key', 'label', 'attributes', 'pagetype'));
		
		if(empty($input['key'])) {
			$input['key'] = $input['label'];
		}
		
		$input['key'] = slug($input['key'], '_');
		
		// an array of items that we shouldn't encode - they're no XSS threat
		$dont_encode = array('attributes');
		
		foreach($input as $key => &$value) {
			if(in_array($key, $dont_encode)) continue;
			$value = eq($value);
		}
```

So, we can see the different code, `$dont_encode = array('attributes');` and `if(in_array($key, $dont_encode)) continue;`
### Expected Behaviour

- Add the two line code as fileds add post function 

### Actual Behaviour

- A list of steps you actually encountered

### Context details (if applicable)

- Anchor version:master branch
- Server setup:php 5.6
- URL

**Comment by daviddarnes** [comment]
Thanks for reporting this. Could you fill out the issue in full please? AKA the version, server setup and any other information that might be of help.

**Comment by maojindao55** [comment]
@daviddarnes added!

**Comment by dylmye** [comment]
Hey, still getting this error on 0.12. Haven't tested 0.12.1 - how do I add the patch?
See #1143
