### ISSUE TITLE
Can't save post with image without JavaScript 

### ISSUE THREAD

**Issue by sashahohloma** [anchorcms/anchor-cms#1070]
I found some bug in Anchor 0.12 - if Javascript disabled in browser I can't save posts with image custom field

Missing argument 2 for Extend::resizeImage(), called in /Applications/MAMP/htdocs/testanch12/anchor/models/extend.php on line 172 and defined

### There's some solution
in _/anchor/models/extend.php_ replace functions:
- upload
- process_image
- resizeImage

to older function from version 0.9 - 
- upload
- process_image

I think JS is cool, but there's should be some way to save post without JS

**Comment by daviddarnes** [comment]
Thanks for reporting this. Feel free to make a pull request, making sure you follow the contribution guidelines. However I don't think it's that much of a problem. There's a few other things in the editor that require JavaScript anyway.

**Comment by BalzySte** [comment]
I'm having the same issue, though I'm not blocking javascript at all.

` argument 2 for Extend::resizeImage(), called in /usr/share/nginx/html/AnchorCMS/anchor/models/extend.php on line 179 and defined`

I couldn't find anything useful online except this issue. I get this error with Anchor CMS 0.12.1 when saving a post with a custom picture field.

**Comment by sashahohloma** [comment]
@BalzySte, I founded solution [here](https://github.com/anchorcms/anchor-cms/issues/1050)

**Comment by TheBrenny** [comment]
Closeable thanks to #1125. They're exactly the same...
