### ISSUE TITLE
quotes don't handle text very well

### ISSUE THREAD

**Issue by poserman** [anchorcms/anchor-cms#1071]
### Summary

quotes and text

### Expected Behaviour

I expect a piece of text to be formatted properly inside a quote. 

### Actual Behaviour

`After a  > symbol it doesn't ignore characters and everything inside a block quote is seen as one line. I can't put a new line character in there because it ignores it. So when I put a script or a large amount of lines with information there, I end up with one single line instead. When using > it also messes up the formatting if the line starts with an # for example. What I currently do, is start every line of a code with ``` and ending with ```<br> just to solve this issue. If I don't do that, the whole layout is messed up and it's unreadable. I end up with tens or hundreds of lines that I start and end with that. Makes the whole markdown part a "bit" less user friendly`

### Context details (if applicable)

- Anchor version: latest
- Server setup:
- URL

**Comment by daviddarnes** [comment]
Thanks for posting this, could you copy an example of the markup that is outputted? Also it helps to give the actual version number you are using :)

**Comment by poserman** [comment]
For example, if I put the following text in a quote:

$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                20
On-line CPU(s) list:   0-19
Thread(s) per core:    1
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Stepping:              4
CPU MHz:               3000.000
BogoMIPS:              5985.44
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-9
NUMA node1 CPU(s):     10-19

I end up seeing this: 

`$ lscpu Architecture: x86_64 CPU op-mode(s): 32-bit, 64-bit Byte Order: Little Endian CPU(s): 20 On-line CPU(s) list: 0-19 Thread(s) per core: 1 Core(s) per socket: 10 Socket(s): 2 NUMA node(s): 2 Vendor ID: GenuineIntel CPU family: 6 Model: 62 Stepping: 4 CPU MHz: 3000.000 BogoMIPS: 5985.44 Virtualization: VT-x L1d cache: 32K L1i cache: 32K L2 cache: 256K L3 cache: 25600K NUMA node0 CPU(s): 0-9 NUMA node1 CPU(s): 10-19`

Inside a block quote I can't use new line characters. It ignores it, but it also ignores end of lines. So the end result is what you see here, as a quote. It does the same with scripts and other stuff I put in quotes. So I can only bypass this by making every line a single quote and then use an end of line character. 

I found the version, it's 0.12.1

**Comment by daviddarnes** [comment]
Ah I see now. Well for new lines in markdown quotes you're meant to add ">" to every new line in the quote. So something like this:
```
> $ lscpu
> Architecture: x86_64
> CPU op-mode(s): 32-bit, 64-bit
> Byte Order: Little Endian
> CPU(s): 20
```
turns into a quote like this:
> $ lscpu
> Architecture: x86_64
> CPU op-mode(s): 32-bit, 64-bit
> Byte Order: Little Endian
> CPU(s): 20

**Comment by daviddarnes** [comment]
Also I noticed you mentioned code blocks as well. I'd recommend using \` for single line code, and \``` for multiline quotes.

**Comment by poserman** [comment]
Yes, but that doesn't ignore things I put in there. For example, I put quotes in bash scripts and it used the '#' header to capitalize the line instead of ignoring that. So adding #!/bin/bash after a > it says !/bin/bash as header 1.

**Comment by poserman** [comment]
Ok for some reason, the ``` now seems to work. that is strange.

**Comment by daviddarnes** [comment]
@poserman glad you got it working at least!

**Comment by poserman** [comment]
Yeah strange that it didn't work before but oh well. Now I can at least use it properly and output the content from /dev/head to /var/www :)
