### ISSUE TITLE
pt_PT Grammar and Spelling Mistakes.

### ISSUE THREAD

**Issue by FerrazzzZ** [anchorcms/anchor-cms#1073]
(I posted this here because I saw other comments in the language repo that took almost a year to get a reply.)
I tried to create a new pull request but seems its disabled at the moment. Below are some things I spotted that are not Portuguese (pt_PT) or are grammatically wrong.

comments.php
1. 'nocomments_desc' should be 'Sem comentários', the current translates to "No comments yet.", the new translates to "No comments".

global.php
1. 'save' should be 'Guardar', the current translates to "Record", the new translates to "save"
2. 'editing' should be 'Editando', the current is correct but why have to words when you can have one?
3. 'inactive' should be 'Inativo', the current is not Portuguese but Spanish.
3. 'active' should be 'Ativo', the current is not Portuguese but Spanish.

I hope this helps.

**Comment by daviddarnes** [comment]
Thanks for this! Would you be able to make a pull request to our translations repo? https://github.com/anchorcms/anchor-translations

**Comment by FerrazzzZ** [comment]
@daviddarnes it does not allow me to push a branch for then to do a PR

**Comment by daviddarnes** [comment]
@FerrazzzZ oh, sorry about that. I didn't realise forks had been turned off, maybe we're maintaining translations differently now. @CraigChilds94?

**Comment by FerrazzzZ** [comment]
Any update on this?

**Comment by ramon-villain** [comment]
@FerrazzzZ https://github.com/anchorcms/anchor-translations is allowing PR

**Comment by TheBrenny** [comment]
Does this get closed then, @daviddarnes, @CraigChilds94?

**Comment by daviddarnes** [comment]
I guess so!
