### ISSUE TITLE
Checkboxes saving incorrect values

### ISSUE THREAD

**Issue by Bibliofile** [anchorcms/anchor-cms#1074]
### Summary

When changing some settings in my new install of Anchor, I realized I was unable to set some values correctly. 

##### Admin settings
- Go to /admin/extend/metadata
- Uncheck "Show all posts"
- Save
- "Show all posts" should be deselected. 

##### Pages
- Go to /pages/edit/1
- Uncheck "Show in menu"
- Save
- "Show in menu" should be deselected.

### Actual Behaviour

In both cases, the checkboxes automatically recheck themselves. 

Additionally, in the "Show all posts" case, the value in the anchor.anchor_meta table contains the same value as comment_moderation_keys (which is correct) 

![capture](https://cloud.githubusercontent.com/assets/6462247/14939819/03581344-0f15-11e6-80d3-cbe571bb15b5.PNG)

### Context details (if applicable)

- Anchor version: 0.12.1
- Server setup: 
  * Debian
  * PHP version 5.5 
  * MySQL version 5.5.44

**Comment by frozenpandaman** [comment]
Was just about to post about the "Show In Menu" bug. Happening here too.

**Comment by jnki** [comment]
Yups! same bug as in this https://github.com/anchorcms/anchor-cms/issues/1063 I think

**Comment by Bibliofile** [comment]
Shoot, I missed that bug when looking to see if it had been reported. Closing this in favor of the original. Thanks!

**Comment by daviddarnes** [comment]
Thanks for reporting, and checking for duplicates, @Bibliofile!
