### ISSUE TITLE
 Timezone for Dhaka is incorrect

### ISSUE THREAD

**Issue by thenanobel** [anchorcms/anchor-cms#1089]
### Summary

Timezone for Asia/Dhaka is incorrect. How to solve this problem?

### Expected Behaviour

- Timezone for Dhaka should be GMT+6

### Actual Behaviour

- Timezone for Dhaka is given GMT+5

### Context details (if applicable)

- Anchor version: 0.12.1
- Server setup: Apache 2.4.7 on Ubuntu 14.04

![screenshot from 2016-05-08 02 34 18](https://cloud.githubusercontent.com/assets/9353047/15410235/82c5171a-1e3a-11e6-92ef-00ca71637242.png)

**Comment by CraigChilds94** [comment]
This is fixed
