### ISSUE TITLE
Core Update Process

### ISSUE THREAD

**Issue by JamesGeiger** [anchorcms/anchor-cms#1109]
A current problem I can envision for users is the update process. Is there a plan to at least send over the air updates automatically for security releases, or is this not possible? e.g. we have 1.0.x releases update core files automatically and then major releases require manual work. Thoughts?

**Comment by daviddarnes** [comment]
This seems like what we're doing with composer. Also we do have an update process in the UI when there's a new version. So I think we have this covered?

**Comment by JamesGeiger** [comment]
@daviddarnes Hmm ok - but shouldn't security point releases be installed automatically? Like 1.0.1, 1.0.2, etc.?

**Comment by daviddarnes** [comment]
Not really, some people don't want their CMS to automatically write files to their server.

**Comment by JamesGeiger** [comment]
@daviddarnes I guess I could just write a script that does that for me so it's not a huge deal. Thanks for you feedback :)
