### ISSUE TITLE
Custom CSS field does nothing on default theme

### ISSUE THREAD

**Issue by magne4000** [anchorcms/anchor-cms#1110]
### Summary

Custom CSS field content doesn't appear anywhere in resulting HTML with default theme.

### Expected Behaviour
```css
article{
  text-align: justify;
}
```
With this, I should have it somewhere in the resulting HTML, and have my article justified

### Actual Behaviour

Nothing happens, as if the Custom CSS field were empty.

### Context details (if applicable)

- Anchor version: 0.12.1

**Comment by daviddarnes** [comment]
Good spot, I believe this is something missing from the theme. The code that outputs the inline CSS is missing.

**Comment by Gerrit0** [comment]
It [looks like](https://github.com/anchorcms/anchor-cms/blob/master/themes/default/header.php#L34-L40) the theme has this to me, I can't seem to reproduce the problem...

**Comment by daviddarnes** [comment]
Good find @Gerrit0, I was recalling from memory. Would you be able to check if this code is in your version @magne4000?

**Comment by magne4000** [comment]
I do have this piece of code
![image](https://cloud.githubusercontent.com/assets/1098371/16259266/114c2302-3862-11e6-83b2-b0e46320a8e6.png)

And if I replace `if(customised()):` by `if(!customised()):`, the block shows up, so it seems that this function doesn't return the correct information.

**Comment by daviddarnes** [comment]
Oh wow, a single character bug fix. One can only dream of this. Would you be able to make a PR for this @magne4000? Which branch should this go to @rwarasaurus?

**Comment by magne4000** [comment]
I don't think that's that simple :), `if customised()` seems the good test to do, the internals of the function should be modified instead

**Comment by Gerrit0** [comment]
I agree with Magne, this isn't a fix, it's a workaround. I'm not sure why it fails yet...

Are you using a vanilla 0.12.1 install Magne? Was it updated from an older version?

**Comment by magne4000** [comment]
It's a fresh 0.12.1 install I just started using it

**Comment by magne4000** [comment]
Some analyze on the issue, `Registry::get('article');` returns NULL

**Comment by magne4000** [comment]
I think I found what's going on. It works on article page but not on home page, since there is no article context (or multiple ones) on home page

**Comment by daviddarnes** [comment]
Ah sorry all, I'm ill and not on form at the moment 😷 . I thought it was a reverse conditional, "if not customised do this, otherwise do this".

**Comment by TheBrenny** [comment]
It's the idea that each article may have a different style attached to it. For a style to be applied across all pages, you'd need to alter the CSS of your theme. But you've already gotten to this answer.. :smile:

> I think I found what's going on. **It works on article page but not on home page**, since there is no article context (or multiple ones) on home page

Makes this closeable, @daviddarnes?

**Comment by daviddarnes** [comment]
@TheBrenny 👍
