### ISSUE TITLE
Call to undefined method Error::log()

### ISSUE THREAD

**Issue by joshvickerson** [anchorcms/anchor-cms#1111]
### Summary

I updated my PHP version from 7.0 to 7.0.7 and now my Anchor sites all fail with an exception:
```
Uncaught Exception
Call to undefined method Error::log()
Origin
anchor/run.php on line 50
```

### Expected Behaviour

- Small PHP update should not have broken Anchor

### Actual Behaviour

- A small PHP update broke Anchor

### Context details (if applicable)

- Anchor version: 0.12.1
- Server setup: Apache 2.4.7, Ubuntu 14.04, PHP 7.0.7
- URL: blog.joshvickerson.com

I did have to change the PPA I was pulling PHP from. Is it possible that this caused something in my PHP configuration to break that needs to be changed?

**Comment by Gerrit0** [comment]
I'm not entirely sure what went wrong, it sure doesn't help that the error reporting class seems to be broken. 

Can you add
```PHP
require PATH . 'system/error' . EXT;
```
Before the try...catch block so that we can see what error actually occurred? I'm betting something with autoloading changed and broke Anchor.

**Comment by joshvickerson** [comment]
So I was going to go in and do this, but when I logged into my server I saw that there were a couple package updates available. One of them was "kept back", `php-pear`. I installed `php-pear` and now it's working.

I think you were right in that the autoloading was broken. As noted above, I had to change the PPA I was getting PHP from as my previous source was 404ing. My guess is changing that messed up a PHP config or something? I'm not really sure how that works.

**Comment by Gerrit0** [comment]
It looks like one of the libraries Anchor uses by ircmaxell requires pear, so that would be the issue. I'm glad you were able to figure it out!

**Comment by kmetto** [comment]
had the same problem, maybe you need to check ypur connection to database

**Comment by kmetto** [comment]
or try to change in run.php
`try {
	Anchor::setup();
} catch(Exception $e) {

	if(ini_get('display_errors') != "1") {
		echo "<h1>Something went wrong, please notify the owner of the site</h1>";
	} else {
		Error::exception($e);
	}

	Error::log($e);
	die();
}`

to

`
	Anchor::setup();
`

and get error directly, dont forget to change this back? when you find error

**Comment by joshvickerson** [comment]
The problem was a change in my PHP installation (getting it from a new source) left me with `php-pear` either not installed or with an incompatible version. It's a dependency of one of the packages Anchor uses. Installing `php-pear` resolved my issue.

**Comment by prubini87** [comment]
Installing [Pear](https://pear.php.net/manual/en/installation.getting.php) fixed it for me. Thanks @joshvickerson!

**Comment by fynekut** [comment]
@kmetto Database Error: SQLSTATE[42S02]
