### ISSUE TITLE
Develop vs Pre-Develop

### ISSUE THREAD

**Issue by JamesGeiger** [anchorcms/anchor-cms#1112]
Hi,

Simple question/issue - what is the dev branch for? The codebase looks radically different than Pre-Develop?

**Comment by Gerrit0** [comment]
This is explained in the [contributing guidelines](https://github.com/anchorcms/anchor-cms/blob/master/.github/CONTRIBUTING.md). 

Even the explanation is rather confusing though, I only really understood it after reading it a few times. 

I believe the branches have somewhat fallen out of this ideal, but what is proposed is:

Master Branch - Has the most current *release* of anchor. Bug fixes are merged into this branch. 
Pre 1.0 Develop Branch - Where new features are proposed and created. Bug fixes merged into the master branch are also copied to this branch. 
Develop Branch - Where the in progress 1.0 version exists. It looks like a rewrite from the ground up is happening.

**Comment by JamesGeiger** [comment]
Yeah I had to read that a few times but was still confused. It seems that Anchor versions < 1 will use the "old" codebase and all versions >= 1 will use the new, rewritten version. I think, lol.

**Comment by CraigChilds94** [comment]
You're spot on @JamesGeiger and @Gerrit0 sorry If it's poorly written, I'll take a look and see if I can re-word it.
