### ISSUE TITLE
Anchor doesn't even try to Compose for dependencies

### ISSUE THREAD

**Issue by TheBrenny** [anchorcms/anchor-cms#1115]
### Summary

During the loading of Anchor, we pass through the `composer_check.php` file, but all Anchor does is look for a folder and die upon not being able to find the folder.

### Expected Behaviour

- Execute `composer install` without the need for human intervention. Speed up installation time.

### Actual Behaviour

- Must manually execute `composer install`. This is an issue for users who are not terminal savy.

### Context details (if applicable)

- Anchor version: Latest
- Server setup: Ubuntu
- URL: null.

**Comment by CraigChilds94** [comment]
@TheBrenny I've merged this in now 💃
