### ISSUE TITLE
Table 'mydatabase.anchor_meta' doesn't exist on fresh install

### ISSUE THREAD

**Issue by alecjstew** [anchorcms/anchor-cms#1122]
### Summary

When doing a fresh install of AnchorCMS from the master branch, I get the following error after I have connected to my database, created an account, and clicked on the link to visit my site:

```
Database Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydatabase.anchor_meta' doesn't exist

SQL: SELECT * FROM `anchor_meta`
The error has been logged in /anchor/errors.log
Origin

system/database/connector.php on line 53
Trace

#0 /home/ajs/blog/system/database/query.php(191): System\database\connector->ask('SELECT * FROM `...', Array)
#1 /home/ajs/blog/anchor/libraries/anchor.php(47): System\database\query->get()
#2 /home/ajs/blog/anchor/libraries/anchor.php(21): anchor::meta()
#3 /home/ajs/blog/anchor/run.php(41): anchor::setup()
#4 /home/ajs/blog/system/start.php(26): require('/home/ajs...')
#5 /home/ajs/blog/index.php(35): require('/home/ajs...')
#6 {main}
```

### Expected Behaviour

- This error should not be appearing after performing a fresh install

### Actual Behaviour

- Again, a fresh install causes this error. I can't view any part of my site that uses AnchorCMS because of this error.

### Context details (if applicable)

- Anchor version: master branch
- I've deleted my database and tried to do everything over from scratch and have had no luck with getting rid of this error.
- However, an install of version 0.12.1 doesn't have this issue. It's only downloading and installing from the master branch that causes this error.

**Comment by daviddarnes** [comment]
Thanks for reporting the bug, we normally recommend you use the version that you can download directly from [anchorcms.com](http://anchorcms.com)

**Comment by CraigChilds94** [comment]
@alecjstew The master branch is not a stable release, please only use the provided tagged releases, (unless you're contributing).

**Comment by thistehneisen** [comment]
Had the exact same problem now just by using the "composer create-project anchorcms/anchor-cms anchor"
