### ISSUE TITLE
Can't update post time in 0.12.1

### ISSUE THREAD

**Issue by xadz** [anchorcms/anchor-cms#1124]
### Summary

Update post time/date field in post editor.

### Expected Behaviour

- Alter value and hit save, will update in editor and reflect on front-end.

### Actual Behaviour

- The value does not save, it reverts as soon as page is refreshed and database is not updated.

### Context details (if applicable)

Anchor version: 0.12.1
Server setup: MediaTemple Grid
URL adamgreenough.com

**Comment by TheBrenny** [comment]
I know this doesn't help towards the issue, but I think we should change how we update the dates? Having a `published` field and an `updated` field would be more ideal?

But more on-topic, looking at code on a mobile device isn't excellent, but I'll have a look at what's going on. Can you confirm that this only affects a post, or does this affect pages as well?

**Comment by xadz** [comment]
I like the idea of having published and updated dates, I actually use a custom field to add an updated date but automatically would be great!

**Comment by TheBrenny** [comment]
@xadz, Are you sure you're not deviating from the format that you need to follow? It's working fine on my [Cloud9 Theme Testing Site](http://anchor-templates-mastercork889.c9users.io/posts) (you might need to log in to see it. :confused:). I've changed the date to be 10 Jul 16...
