### ISSUE TITLE
Doc : Custom Template for all posts inside category

### ISSUE THREAD

**Issue by lowpez** [anchorcms/anchor-cms#1127]
Hello guys,
I know this is more a Theming thing,
but i'll be very happy if you could give an idea how to acomplish this.

### Summary
I'm trying to build a portafolio section inside my website.
I Look at docs https://anchorcms.com/docs/theming/custom-templates  and I saw how simple it was to handle the templates for posts, articles and even categories !. 
Now the problem I have is that I want to apply to each post within the category "portfolio" a custom design / diagramming, different than the rest of the posts.
I thought I could get it via .htaccess,
concatenating $ 1 & $ 2 vars, but all I got was a 500 error: D.
The format was used as filename was:
category-portfolio-article.php. I was close?

### Context details (if applicable)

- Anchor version: 0.12.1
- Server setup: Apache, MySQL 5.7, and PHP 5.6
- URL : Running Local

Cheers.

**Comment by daviddarnes** [comment]
This is basically what custom post types are designed for, which we don't have as of yet 😞 . It would be really good to get on the case for this feature, or a plugin that does the same thing.

As for theming a list of posts within a certain category, I'm not sure it's possible. Maybe @kieronwilson knows?

**Comment by TheBrenny** [comment]
[Custom page and article templates](https://github.com/anchorcms/anchor-cms/blob/030117a60fae333e970e60740337fe7bc8d58298/anchor/libraries/template.php#L12) shouldn't have an issue. If there is something wrong with this, it could be your slug in either the title of your custom template file, or the URL of the page/article that is live on your installation (in your DB).

Even [custom category templates](https://github.com/anchorcms/anchor-cms/blob/030117a60fae333e970e60740337fe7bc8d58298/anchor/libraries/template.php#L27) should work, it's built in, in almost the exact same way...

But I *think* what you're trying to do is create a custom page for each *"article"* of your portfolio, except you don't want to flood your themes folder? Create a custom field for your articles, called something like `portfolioID`, and modify your `article.php` file to detect if this field is present, and control the flow of your template; as in show a specific portion of your template dependent on the ID of this portfolio. Then you can always go back and change the IDs in your Admin Panel. The only downside I can see to this is that you might get a pretty big `article.php` file - but again, depends on what you're making. :stuck_out_tongue_winking_eye:

**Comment by lowpez** [comment]
@daviddarnes @TheBrenny You totally got it.

And what about this?
Can i check if the post It is within the category?.  For example: "portfolio" has the cat ID "1".
So my idea is apply an **IF statement**, if the post is related/inside to the category, then show some text,  ifs not then display normal entry format.

For **custom fields** I do it this way: `$featuredimage = article_custom_field('featured');` but how can i achieve this for posts?

**Comment by lowpez** [comment]
@TheBrenny @daviddarnes,
Guys I know this is unorthodox
We create a *.php file called article-portfolio (article-portfolio.php) inside our theme folder. This could be called whatever you want, just make sure that is the same inside ' ' in theme_include('article-portfolio') sentence. Later we make a backlup of our article.php and replace the content inside the original with this:

```
<?php 
theme_include('header');
$post_cat = article_category_slug();
          if($post_cat == "portfolio") { 
		theme_include('article-portfolio'); 
	  }else { ?> 
HERE GOES THE REST OF THE NORMAL CODE. 
    <? } ?>
<?php theme_include('footer'); ?>
```
I really hope it helps.
Cheers.

**Comment by TheBrenny** [comment]
@lowpez nice feature! However, this doesn't really follow the nature of Anchor's core idea of being minimalistic. Plus, what if you want a portfolio, but someone else wants it for an image gallery? Then the category "portfolio" doesn't really suit. This is the great thing of Anchor though, that you can change your theme slightly to allow more customisation for someone who isn't so PHP savvy, such as implement meta tags, an check for that instead. Or if your keen on keeping it as a portfolio theme, I'm sure it'd get showcased at AnchorThemes! If you've created the whole theme yourself, then [submit it](https://anchorthemes.com/submit)]! :smile_cat: 

@daviddarnes closeable.

**Comment by Radiergummi** [comment]
This is exactly the use case I impemented in [PR #919](
https://github.com/anchorcms/anchor-cms/pull919) :grin:

It allows you to create page type templates. Just name your template file
like your custom page type.
David Darnes <notifications@github.com> schrieb am Sa., 16. Juli 2016 um
19:37:
