### ISSUE TITLE
The requested URL /admin/login was not found on this server.

### ISSUE THREAD

**Issue by zh-wowtv** [anchorcms/anchor-cms#1128]
I installed anchor-cms successfully and the login page shown at:

http://myweburl/index.php/admin/login

The login view shown correctly. But after key in the user id and password, I got the error message:

> The requested URL /admin/login was not found on this server.
> 
> Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
> 

I noticed if I change my login url to: http://myweburl/admin/login, I got the same problem. It seems the index.php is in my url.

What's wrong with it?

**Comment by zh-wowtv** [comment]
Fixed the issue by add .htaccess:

```
Options -indexes

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /

  # Allow any files or directories that exist to be displayed directly
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d

  # Rewrite all other URLs to index.php/URL
  RewriteRule ^(.*)$ index.php?/$1 [L]
</IfModule>

<IfModule !mod_rewrite.c>
  ErrorDocument 404 index.php
</IfModule>

```

**Comment by TheBrenny** [comment]
During installation, did a message show up saying that the `.htaccess` file couldn't be written to? If so, you may have not updated it. [This](https://github.com/anchorcms/anchor-cms/blob/master/install/storage/htaccess.distro) is what should be in your `.htaccess`, but if that's what you started off with, then something *is* wrong...
