### ISSUE TITLE
How to upload video, audio, image?

### ISSUE THREAD

**Issue by zh-wowtv** [anchorcms/anchor-cms#1129]
I'm wondering if there is a plugin to upload image, audio and video files? Any plugin for editor? Thanks

**Comment by lowpez** [comment]
Hi @zh-wowtv ,
I dont know any plugin, and maybe you dont even need it. Anchor is very customizable.
But maybe this link http://andrewmiguelez.com/blog/add-featured-images-to-anchor-cms-posts PLUS some **_tags_** will put you in the right direction ;)

Cheers.

**Comment by daviddarnes** [comment]
Thanks @lowpez, I should think this is a sufficient reply 👍
