### ISSUE TITLE
Feature: Markdown on comments

### ISSUE THREAD

**Issue by redrails** [anchorcms/anchor-cms#1131]
Comments should allow markdown formatting.

Currently I am using [Parsedown](http://parsedown.org/) to show the comments with markdown applied. 

`$Parsedown->text(html_entity_decode(comment_text()));` which seems to do the job but is quite hacky. It would be nice to have the markdown option available. 

Also as another side request, it would also be nice to implement syntax highlighting because as I tested it, code fencing with back-tick and specifying language doesn't highlight code. I'm using [highlightjs](https://highlightjs.org/) to do this currently but again, would be a nice feature to have by default.

**Comment by daviddarnes** [comment]
Hi there, thanks for this but like I said in https://github.com/anchorcms/anchor-cms/issues/210#issuecomment-232734185 can you request for features on [FeatHub](http://feathub.com/anchorcms/anchor-cms) please? This is where we manage all new features that are added to Anchor.

**Comment by redrails** [comment]
@daviddarnes The FeatHub page looks really out of date with posts dating back months, thus I thought it would be better to post here. Sorry about that.

**Comment by Gerrit0** [comment]
@redrails, 

Be careful with that markdown formatting. It will allow XXS. Instead, do this:

```PHP
$Parsedown->setMarkupEscaped(true)->text(html_entity_decode(comment_text()));
```
