### ISSUE TITLE
Editing post lose image from custom field

### ISSUE THREAD

**Issue by BastienMottier** [anchorcms/anchor-cms#1132]
If you create an article (with a custom field to upload) and we upload an image, it is there. But if the item is edited, then the image is not preserved during backup.

- Anchor version: 0.12.1
- Server setup: PHP 5.5.12, MySQL 5.6.17

**Comment by lowpez** [comment]
Hello @BastienMottier,
Please check this thread https://github.com/anchorcms/anchor-cms/issues/1125 or directly go to https://github.com/anchorcms/anchor-cms/issues/1050
Remember that you always can use the searchbox ;)

I hope it helps.
Cheers.

**Comment by BastienMottier** [comment]
Sorry, I'm French, so I have not tried the right keywords :/

**Comment by lowpez** [comment]
@BastienMottier no problem my friend.
I write like tarzan talks, but it's ok, we're cool people :D
If you need more help, just drop a note.

**Comment by TheBrenny** [comment]
@BastienMottier I'm not getting any issues with this... Are you sure you've updated to the very latest version of Anchor?

**Comment by BastienMottier** [comment]
@TheBrenny I'm on 0.12.1. I recorded a video of the error :
https://drive.google.com/file/d/0Bx8PrSn_m81iMm92SmRhZ1REa0k/view?usp=sharing

**Comment by lowpez** [comment]
@BastienMottier Are using the bundled version?. 
Greetings.

**Comment by BastienMottier** [comment]
Yes, I have the bundled.
Greetings.

**Comment by lowpez** [comment]
@BastienMottier, I had the same issues with bundled.
Try a different one. That solved all my problems.

@daviddarnes @TheBrenny guys, please could you update the code in bundled version?.
It seems to be giving more than a headache to users.

Cheers.

**Comment by daviddarnes** [comment]
@lowpez I wish I could help but I can't, this type of bug isn't my strong point. I'm front-end

**Comment by sleepymonday** [comment]
Hi. Was this issue fixed? I'm getting the same error and also, when selecting an image to upload, it gives the url C:/fakepath/... so not uploading at all. 
I downloaded "anchor-cms-0.12.1-bundled.zip" which I think is the last version. 

Thanks in advanced.
