### ISSUE TITLE
Database credentials are HTML-escaped

### ISSUE THREAD

**Issue by Larivact** [anchorcms/anchor-cms#1135]
Try to use a password containing `'`, `"`, `&`, `<` or `>`. It doesn't work since it gets escaped.

**Comment by TheBrenny** [comment]
@CraigChilds94, probably ban these characters from being entered?

I don't like the idea of having someone's password as `<script>alert("h4xd);</script>`...

**Comment by Larivact** [comment]
@TheBrenny If the password is never output (which it shouldn't be anyway) it doesn't matter what the password is.

**Comment by TheBrenny** [comment]
Good point. I'll look into this fairly soon, and have a chat to Craig to see if he's done a lot of work creating something of a fix. We'll determine the best method from there, but I like your idea. I don't know why I didn't think of that in the first place? :joy_cat:

**Comment by Bibliofile** [comment]
This should be fixed with the merge of #1102.

**Comment by CraigChilds94** [comment]
@Bibliofile I've merged the PR will check to make sure it's fixed. Hoping to make a release soon

**Comment by TheBrenny** [comment]
@Larivact Well... I just realised that having a password as a stored XSS can't work. It turns into a hash anyway. 🤣

**Comment by TheBrenny** [comment]
Just checked this as well, and it seems like it's working. A heads up if people stumble upon this and think it hasn't been fixed, make sure you change the status of the account to Active.
