### ISSUE TITLE
HTML not escaped when marked as code. 

### ISSUE THREAD

**Issue by TinkerFu** [anchorcms/anchor-cms#1136]
Anchor version - 0.12.1
OS - Debian

Fresh install of anchor.  Everything worked fine.  First post I made had a code snippet in it.   Code was marked as code.

```
<html>
    <head>
        <meta HTTP-EQUIV="REFRESH" content="0; url=/mail/">
    </head>
</html>
```

Published post. Then as you can guess homepage redirected.  Had to change to draft in db.

**Comment by daviddarnes** [comment]
How did you wrap your code? With 3 backticks?

**Comment by TinkerFu** [comment]
Highlighted the snipped and clicked the "Code" link.   So that's a single tick.

**Comment by daviddarnes** [comment]
Ah I see, I think it's single backticks for inline and 3 for multiline. This might be why it didn't like it, however that's not the best solution as it should execute that code anyway

Thanks for reporting it

**Comment by TinkerFu** [comment]
No prob.  Thanks

**Comment by TheBrenny** [comment]
Issue is fixed. Thanks for pointing this one out! :smile_cat:
