### ISSUE TITLE
Uncaught exception when updating Custom Field label

### ISSUE THREAD

**Issue by dylmye** [anchorcms/anchor-cms#1143]
### Summary

Editing the label on a custom field I've made throws un unhandled exception.

### Expected Behaviour

- Enter updated label, press "Update"  
- Label is updated in db, returns to list of Custom Fields  

### Actual Behaviour

- Enter updated label, press "Update" (see [me](https://i.sli.mg/tRru61.png))  
- Get error `htmlspecialchars() expects parameter 1 to be string, array given` from `system\helpers.php on line 83` (see [me](https://i.sli.mg/cgKRh7.png))

### Context details (if applicable)
- Anchor version: 0.12
- Server setup: localhost testing on UniServer / Uniform Server 0
- URL: n/a

Scrubbed log attached:
[anchor-2016-08-11_001.log](https://github.com/anchorcms/anchor-cms/files/413996/anchor-2016-08-11_001.log.txt)

**Comment by Gerrit0** [comment]
Dupe of #1118 - though I believe my fix only partially fixed the issue...

**Comment by dylmye** [comment]
Sorry, didn't see that (searched for htmlspecialchars I think?)
