### ISSUE TITLE
Unable to install anchor-cms - database error

### ISSUE THREAD

**Issue by staticfrost** [anchorcms/anchor-cms#1144]
### Summary

Unable to install anchorcms- getting a database error

### Expected Behaviour

'm trying to do a fresh install on a new site, but i'm getting this error:

SQLSTATE[HY000] [1045] Access denied for user 'DATABASEUSER'@'localhost' (using password: YES)

the password is correct and i can see a blank database is ready for it to be added to.

### Actual Behaviour

Press - Run Installer. - Get the above error message.

### Context details (if applicable)

- Anchor version: 0.12.1 
- Server setup: Shared Cpanel Site
- URL: scottbailey.net

**Comment by staticfrost** [comment]
The issue can be closed found the problem is to do with my random generated password containing '%,&,^' 

Which was discussed in Issue 1135

**Comment by TheBrenny** [comment]
Thank you for bringing this to our attention. Now we know that this affects more than just the login credentials for the admin area! :smile_cat:
