### ISSUE TITLE
Feature request: Disable cookies only for visitors

### ISSUE THREAD

**Issue by Swabek** [anchorcms/anchor-cms#1146]
Yes it is possible to disable cookies for all. But if cookies are disabled you're unable to login in.
So may a feature to disable the cookies for all visitors would be nice...

**Comment by daviddarnes** [comment]
@Swabek thanks for suggesting this. We handle features on Feathub though https://github.com/anchorcms/anchor-cms/blob/master/.github/CONTRIBUTING.md#how-to-submit-feature-requests
