### ISSUE TITLE
Feature: Add Tinymce to text editing

### ISSUE THREAD

**Issue by gianmaria88** [anchorcms/anchor-cms#1147]
Hi there,
I am a back-end developer and I would like to contribute to integrate some plugins to Anchor.
About the page/post composer, is there any chance to commit a Github version with Tinymce editor? 
I integrated it thus i tested it and it worked well.
Thank you

**Comment by daviddarnes** [comment]
Hi there, this sounds like a plugin idea to me. Anyone else agree?

**Comment by Gerrit0** [comment]
I agree, once 1.0 is released, this would be a good plugin. 

**However** I feel that Anchor is missing out on a lot of enhancements because they are being put off while waiting until 1.0 is released. 

My blog was (accidentally deleted while switching hosting) running a very heavily modified version of anchor because of the lack of plugins / rejection of ideas which were to become plugins eventually. 

For now I'd say merge it in. Then if people like it make it a default plugin when 1.0 is released. 

It would be great to see some plans for the unfinished parts of 1.0 so that the community could help speed the way to its release. For example, how will plugins work?

**Comment by daviddarnes** [comment]
Yea, plugins has been put off until v1.0 is finished. However I don't think it has suffered without better text editing. Anchor has always used markdown and ever since it's become more and more popular.

I'm not sure how plugins work, better to ask @rwarasaurus or @TheBrenny maybe?

**Comment by TheBrenny** [comment]
Yeaaap. It'd be best off as a plugin. Which introduces the idea of plugin collisions: which takes precedence in functionality? Text editor plugin A, or plugin B?

@Gerrit0, I think we all underestimated the release date of 1.0, and hence, have put off too much functionality which would've been absolutely bloody amazing. But I guess it also comes down to whether or not the effort that you're about to put in is worth it... In hindsight, adding all the features in, and then releasing it into a stable branch with no new features to come, only bugfixes (for a year or so), would've been the better option. But oh well. Hindsight likes to make us feel like fools.

@daviddarnes, I'm far too used to the codebase of 0.12. Version 1.0 looks so much more different, so I can't really help on that point. :stuck_out_tongue_closed_eyes:

**Comment by daviddarnes** [comment]
@TheBrenny that's ok, the answer you've given is really good. I just wanted to get some others point of view instead of speaking on behalf of everyone

**Comment by Radiergummi** [comment]
@TheBrenny plugin collisions could be solved something like this:  
Assuming Anchor would just emit events on any point that may be interesting to plugins (kind of like the whole `EventEmitter` stuff from Node), for example `core:beforeRouting`, `themes:afterTemplateRendering` and so on. Plugins would hook in:  
````php
$app->on('core:beforeRouting', function($routesThatWillBeRouted) {
  $myAwesomePluginRoutes = [
    '/myAwesomePlugin' => 'controllers\\plugins\\myAwesomePlugin\\dashboard@index',
    '/myAwesomePlugin/do-awesome' => 'controllers\\plugins\\myAwesomePlugin\\dashboard@awesome',
  ];

  return array_merge($routesThatWillBeRouted, $myAwesomePluginRoutes);
});
````

For tasks like adding routes, something every plugin should be able to do, this works fine when sequentially executing all registered event callback. There should be events only callable once though (something the emitter should define, say, with `$app->emit('foo:bar', Events::ONLY_ONCE_CALLABLE);`), that will throw an exception when registered multiple times. Alternatively, the plugin could be automatically disabled and a message to the admin flashed.  

This has absolutely nothing to do with the issue, I'm just lacking a proper place to dump ideas for Anchor 1.0 :cry:

**Comment by biagio90italia** [comment]
Hello y'all guys, 
thanks to Gianmaria for exposing that. 
I have been working on a project and i absolutely need the "Tinymce editor" thus It'd be awesome to get it for my future works as well. 

I'm looking forward to hearing from you,
Sincerely
Biagio

**Comment by rwarasaurus** [comment]
Ill make sure we have events for the editor so you can switch it out with a plugin, ill update the docs so you can see the full list of events that we're building into 1.0
