### ISSUE TITLE
Can't hide pages in menu

### ISSUE THREAD

**Issue by bmuessig** [anchorcms/anchor-cms#1151]
### Summary

Creating a page or editing one to not show up in the menu does not work. The new settings are not saved and on reload of the editor, the settings are reverted back again.

### Expected Behaviour

Creating a page and hiding it from the menu should hide it there. Updating the settings of a page should save the settings.

### Actual Behaviour

Changing the visibility in menu / name settings of a page does not work. The changes are not saved.

### Context details (if applicable)

- Anchor version: 0.12.1

**Comment by daviddarnes** [comment]
Hmm, this is odd. Maybe this is in relation to the addition of parent & child pages?

Thanks for reporiting

**Comment by bmuessig** [comment]
This seems to be a duplicate of #1063. I have tried it with and without child pages and on child pages themselves and the name fields seem to work, but the "Show in menu" option is saved nowhere.

**Comment by daviddarnes** [comment]
Ah yes you're right, in that case I'm going to have to close this one and use the other to track this issue. Thanks for tracking that one down
