### ISSUE TITLE
Feature request: Better file/image management

### ISSUE THREAD

**Issue by bmuessig** [anchorcms/anchor-cms#1152]
I think it would be really useful if Anchor could place the uploaded images into a folder with the post slug or the upload date. This would prevent collisions and assist the user.
It might also be useful to have a little file/image manager.

**Comment by daviddarnes** [comment]
Thanks for suggesting this! However we manage features using FeatHub, you can find more info about it [in the readme](https://github.com/anchorcms/anchor-cms#feature-requests)

**Comment by bmuessig** [comment]
@daviddarnes Thank you for pointing the feathub page out! I have added my idea as a feature request.

**Comment by daviddarnes** [comment]
Thanks!
