### ISSUE TITLE
Deleting a page with sub-pages breaks the entire site

### ISSUE THREAD

**Issue by bmuessig** [anchorcms/anchor-cms#1153]
### Summary

When you are deleting a page that has sub-pages assigned to it, the public part (not the admin interface) will not be accessible anymore.
### Expected Behaviour

Deleting a page with sub-pages should either give an error, delete the sub-pages or assign the sub-pages to no page.
### Actual Behaviour

The entire blog (except for the admin interface) becomes non-accessible, when Anchor is trying to generate the menu, it encounters a non-element and errors out. The sub pages don't show up in the admin interface anymore.
### Context details (if applicable)
- Anchor version: 0.12.1
- Website: http://bmuessig.eu/
### Workaround / temporary fix

I managed to recover my blog by deleting the sub pages blindly (by accessing the /admin/pages/edit/ page with the number of the parent-less sub-page).

**Comment by daviddarnes** [comment]
Urgh, this is cool. Sorry you discovered this bug the hard way, and thank you for reporting it. Hopefully we can get someone on the case for it.

Ideal solution would be a warning to say "This page has child pages, are you sure you want to delete it?", then after confirmation the page is deleted and the child pages default back to regular pages

**Comment by wishbon** [comment]
I also solves momentarily removing the page from the database in the table anchor_pages
