### ISSUE TITLE
Crash on not-existing posts

### ISSUE THREAD

**Issue by bmuessig** [anchorcms/anchor-cms#1154]
### Summary

Accessing a deleted post or one that has never existed by Url, does not give a simple 404 but actually result in a crash.
### Expected Behaviour

Accessing a non-existing post from /posts/ by URL should give a simple 404 Not found error.
### Actual Behaviour

PHP crashes as it encounters a non-object:

> Trying to get property of non-object
> The error has been logged in /anchor/errors.log
> Uncaught Exception
> 
> Trying to get property of non-object
> 
> Origin
> 
> anchor/models/post.php on line 19
> 
> Trace
> # 0 /myserverpath/htdocs/bmuessig/www/anchor/models/post.php(19): System\Error::native(8, 'Trying to get p...', '/myserverpath...', 19, Array)
> # 1 /myserverpath/htdocs/bmuessig/www/anchor/models/post.php(13): Post::getCommentCount(false)
> # 2 /myserverpath/htdocs/bmuessig/www/anchor/routes/site.php(138): Post::slug('rpn-calculator-...')
> # 3 [internal function]: {closure}('rpn-calculator-...')
> # 4 /myserverpath/htdocs/bmuessig/www/system/route.php(152): call_user_func_array(Object(Closure), Array)
> # 5 /myserverpath/htdocs/bmuessig/www/system/router.php(152): System\Route->run()
> # 6 /myserverpath/htdocs/bmuessig/www/system/start.php(46): System\Router->dispatch()
> # 7 /myserverpath/htdocs/bmuessig/www/index.php(35): require('/myserverpath...')
> # 8 {main}
### Context details
- Anchor version: 0.12.1
- URL: http://bmuessig.eu/posts/whateverpost

**Comment by daviddarnes** [comment]
Hmm, this seems odd. We'll look into it

**Comment by TheBrenny** [comment]
As of the current build, I haven't hit an issue? Maybe update?

**Comment by frozenpandaman** [comment]
This is an issue for me as well.

**Comment by bleft** [comment]
Have a look in the modules/post.php. 
Changing the code to the following fix the issue: 

    public static function slug($slug)
    {
        $post = static::get('slug', $slug);
        
        if (!empty($post)) {
            $post->total_comments = static::getCommentCount($post);
            return $post;
        }
		return false;
    }

**Comment by frozenpandaman** [comment]
Thank you @bleft! Just to note, I think you mean `anchor/models/post.php` (not modules).

**Comment by TheBrenny** [comment]
The code to fix the issue seems to already be in the Anchor Code. Closing.
