### ISSUE TITLE
url not found

### ISSUE THREAD

**Issue by mikel392** [anchorcms/anchor-cms#1155]
### Summary

anchorcms not redirecting correctly 
### Expected Behaviour

when i go to the admin panel the url should be /anchorcms/index.php/admin
### Actual Behaviour

instead it is /anchorcms/amin/login 
### Context details (if applicable)

.htaccess config
```
Options -indexes

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /anchorcms

    # Allow any files or directories that exist to be displayed directly
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d

    # Rewrite all other URLs to index.php/URL
    RewriteRule ^(.*)$ index.php/$1 [L]

</IfModule>

<IfModule !mod_rewrite.c>
    ErrorDocument 404 index.php
</IfModule>
```
- Anchor version: .12
- Server setup:
- URL

**Comment by staticfrost** [comment]
Are you sure you want it to be  /anchorcms/index.php/admin ?

/index.php/ something is right.

Should just be  /anchorcms/admin

**Comment by TheBrenny** [comment]
Anchor routes all the traffic through the `index.php` page no matter what, but hides the filename - but only if it's supposed to. That's the way the `.htaccess` file works. It also helps when users want to share URLs; they become more memorable. [Read up on "Semantic URLs" (aka Clean URLs)](https://en.wikipedia.org/wiki/Semantic_URL).

Unless this is a suggestion to add a feature to not have clean URLs, then I'm closing.
