### ISSUE TITLE
Idea on when the next release is?

### ISSUE THREAD

**Issue by staticfrost** [anchorcms/anchor-cms#1156]
### Summary

Idea on when the next release is?
### Expected Behaviour
- A list of steps you expected to happen in order
### Actual Behaviour
- A list of steps you actually encountered
### Context details (if applicable)
- Anchor version:
- Server setup:
- URL

**Comment by daviddarnes** [comment]
I don't think this is an issue, but it's a worthy question. @rwarasaurus?

**Comment by staticfrost** [comment]
Yeah it kinda isn't but the forums don't get used to often so thought this would be the best place to get an answer ahah.

**Comment by christopherblack** [comment]
+1

**Comment by joshvickerson** [comment]
There have been quite a few commits to master since the last release. Might be worthwhile to bundle it as a small bug fix release? 0.12.2 maybe.

**Comment by Bibliofile** [comment]
I agree, a bug fix release would be very nice as right now if you run into a bug which has been fixed in the master branch it is a bit of a pain to hunt down the fix and apply it.

**Comment by CraigChilds94** [comment]
@staticfrost @Bibliofile  We've updated the forums. And we're looking to release soon. Sorry it's been so long, we want to make sure releases are checked out properly, as the current version of Anchor is old we don't have any tests in place so it's all manual. We'll be looking at `0.13` for the next one as there's been quite a few feature changes. From then on I'll try to keep bugfixes up to date with periodic releases, sorry.

https://forums.anchorcms.com/

**Comment by frozenpandaman** [comment]
Great, @CraigChilds94! Looking forward to the release. Thanks for all your work.
