### ISSUE TITLE
How to create a page for register users!

### ISSUE THREAD

**Issue by SampDev** [anchorcms/anchor-cms#1161]
I want to make a page for normal users create accounts and save the data on the anchor_users table!

On the source code, i found the Class User, i found any functions called user_"anything"

How i use this? Who i implement this on any webpage?

**Comment by Bibliofile** [comment]
Right now, you might think you want to do this, but trust me when I tell you you don't. Currently *all* anchor users can create posts, and *all* posts can contain `<script>` tags. 

The post handler to create users is here: 
https://github.com/anchorcms/anchor-cms/blob/master/anchor/routes/users.php#L125-L166

Still not convinced? Okay... to create a user, use something like this (assuming autoloaded needed classes and functions)

```php
$user = [
    "username" => "user",
    "email" => "a@b.c",
    "real_name" => "name",
    "password" => "pass hashed",
    "username" => "user",
    "bio" => "lived",
    "status" => "status",
    "role" => "administrator", //must be administrator, other roles not yet implemented. 
];
```

Now run each field except for password through eq() to maintain compatibility with the rest of Anchor. 

Finally, 
```php
$u = User::create($user); 
Extend::process('user', $u->id);
```

Again, I would strongly advise you do not do this.

**Comment by TheBrenny** [comment]
Solved by @Bibliofile. Cheers for that! 👍
