### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by joshas** [anchorcms/anchor-cms#1162]
pdo_sqlite is listed in system requirements, but I don't see how to setup anchorcms to use SQLite database.

**Comment by daviddarnes** [comment]
Hi @joshas, this is a duplicate of https://github.com/anchorcms/anchor-cms/issues/611. Is this in the latest version @rwarasaurus?

**Comment by rwarasaurus** [comment]
In the develop branch yes!

**Comment by CraigChilds94** [comment]
@joshas The system requirements on the docs were for the wrong version of Anchor, sorry about that. `0.12.*` does not currently support SQLite. But `1.*` will. You can find the in development version at on the `develop` branch :)
