### ISSUE TITLE
Image URL wrong

### ISSUE THREAD

**Issue by braindeath** [anchorcms/anchor-cms#1165]
### Summary

When I upload a picture to the editor (drag & drop) the generated URL is wrong. It is always like this

`![picture.png](/blogcontent/picture.png)`

instead of

`![picture.png](/blog/content/picture.png)`

So a "/" is missing between blog and content.

### Expected Behaviour

- Uploaded images per drag & drop should generate the URL correctly e.g. `![picture.png](/blog/content/picture.png)`

### Actual Behaviour

- It's e.g. `![picture.png](/blogcontent/picture.png)` instead. "/" is missing between "blog" and "content"

### Context details (if applicable)

- Anchor version: 0.12.1
- Server setup –
- URL –

**Comment by choicky** [comment]
If your blog URL is configured as 

    ~/blog/

instead of

    ~/blog

is the image URL correct?

**Comment by braindeath** [comment]
Where can I edit this "on-the-fly" without re-installing anchor?

**Comment by braindeath** [comment]
I was able to fix the problem, thanks for the input @choicky :)
Changed
`'url' => '/blog',`
to
`'url' => '/blog/',`
in the app.php file. Images are linked correctly now. However, it is strange, since have not altered any default values at the installation. How comes, that this occured?
