### ISSUE TITLE
How to get value from custom field in users?

### ISSUE THREAD

**Issue by JohnJonnyJohn** [anchorcms/anchor-cms#1169]
### Summary

I added a custom field in users, but I can't find any clue how to get the value of the custom field in my php template.

### Expected Behaviour

I thought something like this should work: users_custom_field('avatar_path');
Is it even possible to access this sort of customfield?

### Actual Behaviour

As current behaviour, I get an Internal Server Error

**Comment by TheBrenny** [comment]
Currently, there isn't such a custom field. If you've managed to create something, go for it and make a PR to the master. I, for sure, would love to see this!
