### ISSUE TITLE
Uncaught exception: Can't use method return value in write context

### ISSUE THREAD

**Issue by firetailor** [anchorcms/anchor-cms#1172]
### Summary

During the last Step of installation Process (Account Creation) an uncaught exception occurs.

![bildschirmfoto 2017-01-12 um 03 15 43](https://cloud.githubusercontent.com/assets/11294463/21874624/702aa560-d876-11e6-9a9e-000dd81d8545.png)

### Expected Behaviour

- Normal installation Process

### Actual Behaviour

![bildschirmfoto 2017-01-12 um 03 20 16](https://cloud.githubusercontent.com/assets/11294463/21874636/824da792-d876-11e6-9145-7814228a579c.png)

![bildschirmfoto 2017-01-12 um 03 24 09](https://cloud.githubusercontent.com/assets/11294463/21874650/9e36a21a-d876-11e6-8359-69bf8d63b431.png)

![bildschirmfoto 2017-01-12 um 03 20 50](https://cloud.githubusercontent.com/assets/11294463/21874658/a6e05bb8-d876-11e6-8818-e4c7004647d9.png)

![bildschirmfoto 2017-01-12 um 03 16 23](https://cloud.githubusercontent.com/assets/11294463/21874664/b5500784-d876-11e6-80e0-c9b21f11f031.png)

![bildschirmfoto 2017-01-12 um 03 15 43](https://cloud.githubusercontent.com/assets/11294463/21874667/bb78d532-d876-11e6-9f69-32258abec71f.png)

### Context details (if applicable)

- Anchor version: 0.12.1
- Server setup: PHP 5.6.29 (FPM via Apache)

**Comment by CraigChilds94** [comment]
A fix for this has been merged into `master`, so will be available in the next release.
