### ISSUE TITLE
No input file specified. 

### ISSUE THREAD

**Issue by unloft** [anchorcms/anchor-cms#1173]
why now my web on every link say :
No input file specified. ?

**Comment by choicky** [comment]
because of no permission for the folders or files.

or because of some required php extension are not installed.

**Comment by unloft** [comment]
# **FIXED IT !**
Now all work greats 
Resolution:
i'm add a    ?     (question marker) in   .htaccess file at line 10
THIS LINE :
    RewriteRule ^(.*)$ index.php/$1 [L]     
TO THIS:
    RewriteRule ^(.*)$ index.php?/$1 [L]
