### ISSUE TITLE
"Show in menu" option not saved in pages

### ISSUE THREAD

**Issue by darenju** [anchorcms/anchor-cms#1176]
### Summary

The `Show in menu` option is not saved when editing a page.

### Expected Behaviour

- Uncheck the `Show in menu` option
- Click `Save` button
- Change should remain on page reload

### Actual Behaviour

- Change does **not** remain on page reload

### Context details (if applicable)

- Anchor version: 0.12.1

**Comment by darenju** [comment]
Just checked source code before applying my changes, this bug has already been fixed, but were not shipped in my version. My mistake.

**Comment by daviddarnes** [comment]
👍

**Comment by tavai89** [comment]
Hi. Thanks for all your work first. I wondering when you going to have the next release including this fix?

**Comment by frozenpandaman** [comment]
Hey @darenju, do you know the commit where this was fixed? Would like to manually make the changes so this is no longer an issue for me. Thanks.

**Comment by frozenpandaman** [comment]
For those wanting for more information, including the commit that fixes this, see #1063.
