### ISSUE TITLE
Encoding errors in MySQL and with some words

### ISSUE THREAD

**Issue by sashatravkina** [anchorcms/anchor-cms#1177]
### Summary

Hi! I install Anchor and he works great. But I have problem with my russian words encoding. Post text in MySQL table looks like:

![001](https://cloud.githubusercontent.com/assets/16720880/22401016/f0299728-e5d5-11e6-8810-21dd5ec75f2b.png)

And I have problem with some letters in my post on site. For example russian letter "И" looks like "�".

![90909](https://cloud.githubusercontent.com/assets/16720880/22405125/b2b55fb6-e64e-11e6-93a1-ccc50e8a9627.png)

And this is bad. My site and server works on utf-8 (utf8_general_ci). English letters looks correct.

### Context details (if applicable)

- Anchor version: 0.12.1
- Server setup: PHP 5.6
- beta.milkleaks.ru

**Comment by TheBrenny** [comment]
Try inserting this
```
<head>
<meta charset="utf-8">
</head>
```

If that hasn't fixed anything try switching the encoding in MySQL to `utf8_unicode_ci`.
