### ISSUE TITLE
Database manually

### ISSUE THREAD

**Issue by fynekut** [anchorcms/anchor-cms#1182]
What can I do if I need to create the database and add previleges manually? (host restrictions)

**Comment by fynekut** [comment]
Database Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydatabase.anchor_meta' doesn't exist

**Comment by daviddarnes** [comment]
I'm not sure of this one, can @TheBrenny help with this? It's not an issue so I'll close it, but feel free to chat further to get help

**Comment by TheBrenny** [comment]
(This file)[https://github.com/anchorcms/anchor-cms/blob/master/install/storage/anchor.sql] defines all the tables that are created in Anchor. You should be able to execute this file, either as one huge query, or as smaller queries. Of course though, you need to find all the instances of `{{prexif}}` and replace it with whatever prefix you're going to use, ie, the default prefix is `anchor_`.

**Comment by fynekut** [comment]
I think it's solved but, 

@TheBrenny if the database already exists, the installer returns the above error

shared hostin has this restriction and will be necessary to do manually, so?

**Comment by fynekut** [comment]
By the way, the restriction also makes the migration 213 https://github.com/anchorcms/anchor-cms/commit/27fffb3d032be9a51ac1cde661346915f9dce5e8 unusable
