### ISSUE TITLE
article_markdown ignores formatting

### ISSUE THREAD

**Issue by fynekut** [anchorcms/anchor-cms#1184]
For some reason, article_markdown doesn't work

But article_html works perfectly for both, md and html

**Comment by TheBrenny** [comment]
Define what you mean by "`article_markdown` doesn't work".

Calling that function will return the content that you put in the admin panel, not the content you want to display. That function is `article_html` as you've already said.

**Comment by evansharp** [comment]
This should be closed.

**Comment by fynekut** [comment]
I meant the tags.
