### ISSUE TITLE
Can't give the blog a name with less than 4 characters

### ISSUE THREAD

**Issue by pwab** [anchorcms/anchor-cms#1185]
### Summary

When installing anchor you **can't** give your blog a _name with less than 4 characters_.
( The error occurs when installation is at this point: `anchor/install/index.php?route=/metadata` )

![anchor-issue-a blog named bob](https://cloud.githubusercontent.com/assets/19271185/22862119/dc29c492-f128-11e6-9d4e-96657eebed31.JPG)

### Expected Behaviour

Giving the blog a name with three letters or less (for example: `bob`) should be no problem.

### Actual Behaviour

When giving the name `bob` it shows the following error message:

> Please enter a site name

When giving the name `bobo` (4 chars) installation can be finished.

### Context details

- Anchor version: 0.12.1
- Server setup: WPN-XM (Windows stack) with nginx 1.9.4, php 5.5.28 and mariadb 10.1.6
- URL: localhost

### What I guess where to look
See [routes.php at line 147](https://github.com/anchorcms/anchor-cms/blob/master/install/routes.php#L147)

```
$validator->check('site_name')
    ->is_max(4, 'Please enter a site name');
```

### What would be a better UX
- Give the user the possibility to enter names with less than 4 characters
- Give the user a better error message, that the entered name is too short
- Give the user a hint next to each field that a given name (blogname, username...) has restrictions (like a minimum length)

**Comment by CraigChilds94** [comment]
@pwab Thanks for this, I will make an alteration to the way we're validating this field and provide the user with some better feedback. 👍
