### ISSUE TITLE
Database Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'anchor.anchor_meta' doesn't exist

### ISSUE THREAD

**Issue by badmangocom** [anchorcms/anchor-cms#1189]
Database Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'anchor.anchor_meta' doesn't exist

xampp v3.2.2

**Comment by daviddarnes** [comment]
Hi, which version of anchor are you using?

**Comment by axeloz** [comment]
Hello,

same issue here. Just checked out master branch. Actually, the whole database is empty, no table at all despite the installer. 
Thanks

**Comment by daviddarnes** [comment]
@axeloz from what I recall, @CraigChilds94 said that the master branch requires composer for you migrate to using the master version of Anchor. Is that right?

**Comment by badmangocom** [comment]
@daviddarnes 

page  https://github.com/anchorcms/anchor-cms/releases

anchor-cms-0.12.1-bundled.zip   timezone  wrong
Source code (zip)       timezone  wrong

page https://github.com/anchorcms/anchor-cms  

download zip    Database Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'anchor.anchor_meta' doesn't exist

**Comment by Prkns** [comment]
I've just installed a completely fresh version of Anchor from the master branch. Installed using composer and I'm having the same issue of a fully empty database after completing the installer.

There were no issues during the installer sequence, just once I clicked through to view the site after it.

I used a London timezone if that's any help?

**Comment by GotExx** [comment]
Same issue with latest master version. I've use the installer with GTM+2 Paris Timezone

**Comment by daniellobrunello** [comment]
Same problem here.
0.12.1 (bundled and source) works fine.
In 0.12.3.:
Error logs state no problems. mysql query log says there is no query that should create the tables. Database connection is established and the directly quit.

**Comment by TheBrenny** [comment]
Perhaps there's a permissions issue with the Database Account that you've given during install? Can someone confirm the permissions that their account has?

**Comment by daniellobrunello** [comment]
Tried it multiple times with different versions. Issue only on 0.12.3.

**Comment by TheBrenny** [comment]
Are you able to paste some screenshots of the table/DB? This isn't happening to me?

**Comment by joaopaulofilho** [comment]
I've faced this issue too. It seems that when installing, it does check if the database is created (of course, we've to create it to proceed to installation), but then it doesn't actually install the tables.

Preparing a PR for this.

If there is some sort of contributing guideline that I didn't followed, please let me know (sort of a beginner in contributing with projects).
