### ISSUE TITLE
Error when uploading image

### ISSUE THREAD

**Issue by N07070** [anchorcms/anchor-cms#1195]
### Summary

When I drag and drop an image to my article, it doesn't work. The console gives more details.

### Expected Behaviour

- Drag image onto the article, drop, and image/link appears in the article.

### Actual Behaviour

- Fail without other information

### Context details (if applicable)

- Anchor version: 0.12.1
- Server setup: LAMP
- URL 

### Log : 

```
TypeError: f is undefined[Learn More] zepto.js:2:11087
	k/</j  http://www.--------anchor/views/assets/js/zepto.js:2:11087

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More] dragdrop.js:139:14
	uploaded http://www.-----------/anchor/views/assets/js/dragdrop.js:139:14
	upload/xhr.onreadystatechange http://www.------------/anchor/views/assets/js/dragdrop.js:107:12
	onStopRequest resource://gre/modules/WebRequest.jsm:347:7
```

**Comment by TheBrenny** [comment]
Cheers for following the template! Are you able to double check that this still exists in the latest version of Anchor?

**Comment by TheBrenny** [comment]
Closing due to:
- the version containing bug is 0.12.1 when the current version is 0.12.7; and
- the last post was made just about a year ago and it was requesting more details - none were provided.
