### ISSUE TITLE
Uploading image/file in category not working

### ISSUE THREAD

**Issue by fishgrind** [anchorcms/anchor-cms#1198]
### Summary

Uploading image/file in category not working with custom file field

### Expected Behaviour

File should be uploaded when a custom field is used

### Context details (if applicable)

I solved the problem by adding 

`<script src="<?php echo asset('anchor/views/assets/js/upload-fields.js'); ?>"></script>`

to line 51 of edit.php and add.php in \anchor\views\categories

**Comment by CraigChilds94** [comment]
@fishgrind Thank you, would you be able to make a PR for this fix?

**Comment by fishgrind** [comment]
@CraigChilds94 sure i'll make one just now!

**Comment by fishgrind** [comment]
pull request is done: https://github.com/anchorcms/anchor-cms/pull/1200
