### ISSUE TITLE
Installation is not progressing from Timezone page

### ISSUE THREAD

**Issue by sanmation** [anchorcms/anchor-cms#1203]
Hi 
I was trying to download anchor CMs on my blog (sub-folder) with the same method it mentioned in the read me file. Unfortunately the installation is not moving from the timezone and Language screen. If you press next it just refresh and stays in the same page.

How do I continue?

Thanks in advance

**Comment by TheBrenny** [comment]
Would've been nice if you could've followed the issue template........

But can you show us what your JS log is showing? Maybe are there any issues on the networking tab of chrome's devtools? Maybe check any server logs?

Really having zero context of the server is making things more difficult.

**Comment by Gibigbig** [comment]
Using php7 and having the saem issue.

**Comment by TheBrenny** [comment]
@Gibigbig, please refer to my comment above.

**Comment by TheBrenny** [comment]
Closing due to lack of information provided. Feel free to open a new issue following the template that pre-fills the text area.
