### ISSUE TITLE
[Feature] Allow Backdating Posts

### ISSUE THREAD

**Issue by KermMartian** [anchorcms/anchor-cms#1214]
(I'd submit this on Feathub as indicated in the contribution guidelines, but it looks like Feathub is down).

I suggest that at least Admin-level users, and perhaps others, have the option to backdate new posts, in addition to the existing default of applying the current timestamp. This would probably take the form of an optional field on the new post page, allowing a date to be specified.

Apologies if this is a subpar way to request a feature and/or if feature requests are not being accepted at this time.

**Comment by TheBrenny** [comment]
This is already a feature within the current Anchor (available on GH). Edit a post and change it's `Published on (GMT)` field?

**Comment by KermMartian** [comment]
Perfect, that workflow will do the trick for me. Would there be sufficient interest in having that option available from the original post composition page, though?

**Comment by Radiergummi** [comment]
@KermMartian I think your usecase is completely valid, but in my opinion customizing the post publication date is a feature 90% of our users don't need, and if they do, they can simply edit the post after drafting it.  
Therefore it serves Anchor's philosophy to keep the field on the edit page. Might be worth an FAQ section tho 😄

**Comment by KermMartian** [comment]
Fair enough, thanks! I'll self-close as this being an eccentric use case.
