### ISSUE TITLE
Composer error: "The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly"

### ISSUE THREAD

**Issue by MerlinElMago** [anchorcms/anchor-cms#1218]
When trying to install, the web server (lighttpd on Fedora 26) throws an error: "The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly
"

Composer is installed via packet manager (although I tried the manual install as well with identical results).

Anchor version: 0.12.3
Server: lighttpd on Fedora 26

Best regards
Merlin

**Comment by TheBrenny** [comment]
I think this is more an issue with Composer not installing correctly on your distro. Probably best to consult their FAQ or issues page?

**Comment by CraigChilds94** [comment]
@MerlinElMago If you can setup ENV vars on your server try `COMPOSER_HOME=~/.composer`

This isn't an Anchor related issue, it's either your server or the installation of Composer :)
