### ISSUE TITLE
.htaccess redirect to https:// issues.

### ISSUE THREAD

**Issue by helloarchie** [anchorcms/anchor-cms#1220]
### Summary

Apologies if this is the incorrect place, I can't find anything on the forum. I have a weird .htaccess issue. I'm trying to force all http://helloarchie.co/ and www.helloarchie.co to https:// but there's something I've included previously that gets rid of index.php in the URL that's clashing with it every time.

### Expected Behaviour

Visiting any http://helloarchie.co or www.helloarchie.co link redirects to the same place but to https://.

### Actual Behaviour

It doesn't redirect OR
(if I include the https redirect code in my htaccess it brings up this URL: http://helloarchie.co/index.php?/design/ and redirects every link to the homepage instead).

### Context details (if applicable)

- Anchor version: 0.9.2
- Server setup:
- URL https://helloarchie.co/

### .htaccess

    <IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /

    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php?/$1 [L]  
    </IfModule>

**Comment by daviddarnes** [comment]
Hi @helloarchie, I've just tried the site and it appears to be redirecting as expected. http://helloarchie.co and http://www.helloarchie.co all redirect to https://www.helloarchie.co

Maybe it was a caching issue? You may want to check your image hosting too, they're being served from a non-https CDN.
