### ISSUE TITLE
How to get User Rules from Article_Author?

### ISSUE THREAD

**Issue by SampaioLeal** [anchorcms/anchor-cms#1224]
Hi, i want to get the User Rules from the `article_author` called on posts.php!

I will create a label on the "Write by: " section and i want the user rule to be like this:
![image](https://user-images.githubusercontent.com/16009837/30742519-d5aff99c-9f6f-11e7-8471-f613cf29f809.png)

**Comment by daviddarnes** [comment]
Hey, you might want to check this page out in the documentation https://docs.anchorcms.com/function-reference/articles/
You could create something like:
``` php
<div class="author">
  <span class="author__name"><?php echo article_author(); ?></span>
  <span class="author__title"><?php echo article_author_bio(); ?></span>
</div>
```

**Comment by SampaioLeal** [comment]
So, i have to put the office/rules on the biography of the user?

**Comment by daviddarnes** [comment]
I'm afraid so, as I don't think it's possible to add custom fields to authors
