### ISSUE TITLE
No inline images on post page using markdown

### ISSUE THREAD

**Issue by peanutbudder** [anchorcms/anchor-cms#1225]
### Summary

Inline images inserted using markdown not appearing on post's page.

### Expected Behaviour

When viewing a post's page, inline images inserted using markdown should appear normally as you would using an `<a>` tag. 

### Actual Behaviour

Image markdown is not parsed and inline images are not displayed. `<a>` tags function correctly. 

### Context details (if applicable)

- Anchor version: 0.12.3
- Server setup:
CentOS 7  
PHP - 7.0.23
MySQL - Ver 15.1 Distrib 10.0.32-MariaDB, for Linux (x86_64) using readline 5.1
- URL: http://beta.atafamily.com/news/just-tae-kwon-do-it-tournament-information

**Comment by daviddarnes** [comment]
@peanutbudder hi there, thanks for contributing! Are you putting extra returns between your markdown images? Links (`<a>` elements) don't need to be on new lines but images do I believe.

**Comment by peanutbudder** [comment]
Yes, I made sure the add extra returns. This is my formatting to test it:

`Come join us on October 28th for our Just Tae Kwon Do It tournament here in Indianapolis. Here is our flyer and the schedule of events for that day. It is coming up close and we are super excited for it! Hope to see you there!


<img src="/content/justtaekwondoitflyer.jpg"></img>


![justtaekwondoitflyer.jpg](http://beta.atafamily.com/content/justtaekwondoitflyer.jpg)


![justtaekwondoitschedule.jpg](/content/justtaekwondoitschedule.jpg)`

Markdown images show up fine on the '[Posts Page](http://beta.atafamily.com/news)' but they don't show up when viewing the page for an [individual post](http://beta.atafamily.com/news/test-news) and instead just prints the markdown. 

This is with the default theme.

**Comment by daviddarnes** [comment]
I'm not sure what could be happening, as the functions in the theme are exactly the same:
- https://github.com/anchorcms/anchor-cms/blob/master/themes/default/posts.php#L15
- https://github.com/anchorcms/anchor-cms/blob/master/themes/default/article.php#L6

Do you mind testing how this code reacts?
``` md
![An image](http://via.placeholder.com/350x150)
```

**Comment by peanutbudder** [comment]
I tried the Placeholder image and it still doesn't show up in the article. I did upgrade from 0.9.1 so it isn't a fresh install; I could try that but the articles.php functions haven't changed since then.

**Comment by daviddarnes** [comment]
@peanutbudder that could be why, I believe we're at least on 0.12.x now

**Comment by peanutbudder** [comment]
Yes, I upgraded to 0.12.3 from 0.9.1. I'll try a fresh install and see how that goes.

**Comment by peanutbudder** [comment]
A fresh install fixed this. I'm not exactly sure what didn't get changed when upgrading but at least I have a way to get it to work now. Thanks!

**Comment by daviddarnes** [comment]
@peanutbudder weird, maybe a DB error as the html and the markdown gets sorted I think. Glad you got it sorted!
