### ISSUE TITLE
How do I configure an SMTP server?

### ISSUE THREAD

**Issue by limenleap** [anchorcms/anchor-cms#1226]
Would appreciate notes on how to configure SMTP for anchorCMS. I can't seem to find one. How do I enable the "forgot password"? 

Thanks!

**Comment by limenleap** [comment]
I couldn't get an answer, so this is what I ended up doing

**A) Step 1** 
Firstly I installed Pear

sudo apt-get install php-pear

Then these pear packages

sudo pear install Mail
sudo pear install Net_SMTP

**B) Step 2**

Then placed these files somewhere in my main root folder of the website (The CMS is installed in a sub-folder called blog)

1) sendpearemail.php 
2) gmailconfig.php 

Both these files are in a zip file here. You need to change the password of your gmail account in gmailconfigsample.php. Then rename that file as gmailconfig.php

Then I placed  the two files into the web root folder. The anchorCMS may or may not be in same folder.
In my case it was in a folder called blog within the web root. It could be different in your case.


**C) Step 3** 

Now I opened up comment.php from here
blog/anchor/models/coment.php 

Then add the following line in the top of that file

require "../sendpearmail.php"

(The double dot is to indicate that the file sendpearmail.php is actually in the parent folder of the blog folder. In your case, you would need to know where you copied that  file to and use that path)

In the same file, there is a function call to the PHP mail( ... ) function. Change the name of that function call to pearmail  -- It has the same parameters as PHP "mail"

**D) Step 4**

I did the same above changes in this file too:

blog/anchor/routes/admin.php

------------------
Now, I am not sure how the upgrades happen in AnchorCMS  I guess when you upgrade your installation you would have to do step 3 and 4 again 

I am not sure if this is the right method. (I am new to AnchorCMS and was in a hurry) This is what worked for me. 

The sample config given is for gmail. If you use sparkpost then you would need to change the configuration in gmailconfig.php thus

$pe_host  = "smtp.sparkpostmail.com" 
$pe_username = "SMTP_Injection";
$pe_password = "SPARKPOST_KEY";
$pe_port = "587";
$pe_defaultaddress = "no-reply@SENDINGDOMAIN";

//Note the SENDINGDOMAIN must be authorized at sparkpost. SPARKPOST key is what you obtained from your account control panel at Sparkpost

[pearmailfiles.zip](https://github.com/anchorcms/anchor-cms/files/1351560/pearmailfiles.zip)

**Comment by Radiergummi** [comment]
Well, usually there's a `sendmail` binary on Linux systems available, which is what PHP uses if it is configured properly. If it is not but you have control over the server, I'd rather recommend installing `postfix` which ships with a `sendmail` binary. Next make sure your `php.ini` is configured correctly: It should have a valid `sendmail_path` (trust me, that one is freaking hard to debug) and SMTP configuration set. That should be enough to get going.  
If you don't have control (i.e. shared hosting), I'd suggest contacting your host on how to set up SMTP with PHP.
