### ISSUE TITLE
Bug when add new page

### ISSUE THREAD

**Issue by abutouq** [anchorcms/anchor-cms#1231]
I'm trying to add new page with invalid redirect URL and I got below error:

```
Undefined variable: page
The error has been logged in /anchor/errors.log
Trace
anchor/routes/pages.php on line 222
```

- Anchor version:
0.12.3
- Server setup:
Nginx
- URL
admin/pages/add

**Comment by CraigChilds94** [comment]
@abutouq Thanks for reporting this. Try an older version, we'll look into this as soon as we can!

**Comment by TheBrenny** [comment]
Try in the latest Anchor CMS? Hopefully it's fixed? 🙏
