### ISSUE TITLE
Installing anchor to hostgator issue

### ISSUE THREAD

**Issue by 14u2ponder** [anchorcms/anchor-cms#1233]
### Summary

A brief but detailed explanation of the issue or bug you are reporting.
Unable to complete setup

### Expected Behaviour
Create achor homesite

- A list of steps you expected to happen in order

URL

**Important: I had to add vendor folder from a previous anchor setup, as 12.1 doesn't seem to have that folder. I am using edge browser, but I've tried Opera as well, same behavior.

### Actual Behaviour

- A list of steps you actually encountered
![2017-11-29](https://user-images.githubusercontent.com/4943529/33386645-06f7a430-d4f1-11e7-947d-06f983e441db.png)

### Context details (if applicable)

- Anchor version: 12.1
- Server setup: php 5.6
- Url: thattruckneedsamudflap.com

Error log:
[Wed Nov 29 10:31:43 2017] [error] [client 72.47.135.2] File does not exist: /home2/zsqr5wfq/public_html/favicon.ico
[Wed Nov 29 10:31:04 2017] [error] [client 72.47.135.2] File does not exist: /home2/zsqr5wfq/public_html/favicon.ico
[Wed Nov 29 10:30:13 2017] [error] [client 72.47.135.2] File does not exist: /home2/zsqr5wfq/public_html/favicon.ico
[Wed Nov 29 10:26:28 2017] [error] [client 157.52.156.49] File does not exist: /home2/zsqr5wfq/public_html/gvs.php
[Wed Nov 29 09:21:03 2017] [error] [client 184.154.139.20] File does not exist: /home2/zsqr5wfq/public_html/th1s_1s_a_4o4.html, referer: http://www.google.com/url?url=www.thattruckneedsamudflap.com&yahoo.com
[Wed Nov 29 08:59:53 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpmanager
[Wed Nov 29 08:59:53 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpmyadmin2018
[Wed Nov 29 08:59:53 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpmyadmin2017
[Wed Nov 29 08:59:52 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpmyadmin2016
[Wed Nov 29 08:59:52 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpmyadmin2014
[Wed Nov 29 08:59:52 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpmyadmin2013
[Wed Nov 29 08:59:52 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpmyadmin2012
[Wed Nov 29 08:59:52 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpmyadmin2011
[Wed Nov 29 08:59:51 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/pma2018
[Wed Nov 29 08:59:51 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/pma2017
[Wed Nov 29 08:59:51 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/pma2016
[Wed Nov 29 08:59:51 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/pma2015
[Wed Nov 29 08:59:51 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/pma2014
[Wed Nov 29 08:59:50 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/pma2013
[Wed Nov 29 08:59:50 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/pma2012
[Wed Nov 29 08:59:50 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/pma2011
[Wed Nov 29 08:59:50 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/PMA2018
[Wed Nov 29 08:59:50 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/PMA2017
[Wed Nov 29 08:59:50 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/PMA2016
[Wed Nov 29 08:59:49 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/PMA2015
[Wed Nov 29 08:59:49 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/PMA2014
[Wed Nov 29 08:59:49 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/PMA2013
[Wed Nov 29 08:59:49 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/PMA2012
[Wed Nov 29 08:59:49 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/PMA2011
[Wed Nov 29 08:59:49 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/php-my-admin
[Wed Nov 29 08:59:48 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpMyAdmin-3
[Wed Nov 29 08:59:48 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpMyAdmin4
[Wed Nov 29 08:59:48 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpMyAdmin3
[Wed Nov 29 08:59:48 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpMyAdmin2
[Wed Nov 29 08:59:48 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/administrator
[Wed Nov 29 08:59:48 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/administrator
[Wed Nov 29 08:59:47 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/administrator
[Wed Nov 29 08:59:47 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/administrator
[Wed Nov 29 08:59:47 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/administrator
[Wed Nov 29 08:59:47 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/administrator
[Wed Nov 29 08:59:47 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/administrator
[Wed Nov 29 08:59:47 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/db
[Wed Nov 29 08:59:46 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/db
[Wed Nov 29 08:59:46 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/db
[Wed Nov 29 08:59:46 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/db
[Wed Nov 29 08:59:46 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/db
[Wed Nov 29 08:59:46 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/db
[Wed Nov 29 08:59:46 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/db
[Wed Nov 29 08:59:45 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/db
[Wed Nov 29 08:59:45 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/db
[Wed Nov 29 08:59:45 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/db
[Wed Nov 29 08:59:45 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/sql
[Wed Nov 29 08:59:45 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/sql
[Wed Nov 29 08:59:44 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/sql
[Wed Nov 29 08:59:44 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/sql
[Wed Nov 29 08:59:44 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/sql
[Wed Nov 29 08:59:44 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/sql
[Wed Nov 29 08:59:44 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/sql
[Wed Nov 29 08:59:44 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/sql
[Wed Nov 29 08:59:43 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/sql
[Wed Nov 29 08:59:43 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/sql
[Wed Nov 29 08:59:43 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/sql
[Wed Nov 29 08:59:43 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/sql
[Wed Nov 29 08:59:43 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/sql
[Wed Nov 29 08:59:43 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/sql
[Wed Nov 29 08:59:42 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/mysql
[Wed Nov 29 08:59:42 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/mysql
[Wed Nov 29 08:59:42 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/mysql
[Wed Nov 29 08:59:42 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/mysql
[Wed Nov 29 08:59:42 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/admin
[Wed Nov 29 08:59:42 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/admin
[Wed Nov 29 08:59:41 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/admin
[Wed Nov 29 08:59:41 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/admin
[Wed Nov 29 08:59:41 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/admin
[Wed Nov 29 08:59:41 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/admin
[Wed Nov 29 08:59:41 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/admin
[Wed Nov 29 08:59:40 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/mysql-admin
[Wed Nov 29 08:59:40 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/mysqladmin
[Wed Nov 29 08:59:40 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpmy-admin
[Wed Nov 29 08:59:40 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/php-myadmin
[Wed Nov 29 08:59:40 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/mysqlmanager
[Wed Nov 29 08:59:40 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/sqlmanager
[Wed Nov 29 08:59:39 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/db
[Wed Nov 29 08:59:39 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/db
[Wed Nov 29 08:59:39 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/database
[Wed Nov 29 08:59:39 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/mysql
[Wed Nov 29 08:59:39 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/admin
[Wed Nov 29 08:59:39 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/db
[Wed Nov 29 08:59:38 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/pma
[Wed Nov 29 08:59:38 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/dbadmin
[Wed Nov 29 08:59:38 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/PMA
[Wed Nov 29 08:59:38 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/program
[Wed Nov 29 08:59:38 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/MyAdmin
[Wed Nov 29 08:59:38 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/shopdb
[Wed Nov 29 08:59:37 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/myadmin
[Wed Nov 29 08:59:37 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phppma
[Wed Nov 29 08:59:37 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpmy
[Wed Nov 29 08:59:37 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/2phpmyadmin
[Wed Nov 29 08:59:37 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpmyadmin4
[Wed Nov 29 08:59:37 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpmyadmin3
[Wed Nov 29 08:59:36 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpmyadmin2
[Wed Nov 29 08:59:36 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpmyAdmin
[Wed Nov 29 08:59:36 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpMyAdmin
[Wed Nov 29 08:59:36 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpMyadmin
[Wed Nov 29 08:59:36 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/phpmyadmin
[Wed Nov 29 08:59:36 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/mysql
[Wed Nov 29 08:59:35 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/mysql
[Wed Nov 29 08:59:35 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/mysql
[Wed Nov 29 08:59:35 2017] [error] [client 89.249.2.67] File does not exist: /home2/zsqr5wfq/public_html/mysql

**Comment by 14u2ponder** [comment]
I figured it out. I downloaded 12.3 by mistake and it didn't have vendor so I was trying to use 9.3 composer vendor.
I think you might want to make a better distinction between 12.3 and 12.1 on which to install, because I got really confused.

**Comment by CraigChilds94** [comment]
Sorry about that @14u2ponder We'll look into making things clearer in the future!

**Comment by 14u2ponder** [comment]
While you are at it? Just how do you update 12.1 to 12.3?

**Comment by 14u2ponder** [comment]
@craigchilds94
