### ISSUE TITLE
Installer can't find composer.

### ISSUE THREAD

**Issue by dval** [anchorcms/anchor-cms#1237]
### Summary

After cloning Anchor, and navigating to the URL in browser I see the following:
```
We were unable to run composer our selves. Please run "composer install" from the command line to install Anchor. If you do not have composer installed please see https://getcomposer.org/
(Error #127) Here is the output of the command:
sh: composer: command not found
```

Running `composer` from term, shows the following:
```
$ composer
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.6-dev (57b3e2451404af0dac0f5fd797fce6789fa2624b) 2017-12-20 12:13:32
```

### Expected Behaviour

0.9 version had a friendly screen for starting the automatic install. I would have expected something similar.

### Actual Behaviour

I can not install anchor. There is only an error screen:
```
We were unable to run composer our selves. Please run "composer install" from the command line to install Anchor. If you do not have composer installed please see https://getcomposer.org/
(Error #127) Here is the output of the command:
sh: composer: command not found
```

Running the provided command does not work either:
```
$ composer install
Composer could not find a composer.json file in /Users/dylan/Dropbox/SiteFiles
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```

Navigating to the AnchorCMS directory in terminal and running `composer install`, almost works but tells me:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Package operations: 4 installs, 0 updates, 0 removals
  - Installing indigophp/hash-compat (v1.1.0): Downloading (100%)         
  - Installing ircmaxell/password-compat (v1.0.4): Downloading (100%)         
  - Installing ircmaxell/security-lib (1.0.0): Downloading (100%)         
  - Installing ircmaxell/random-lib (v1.1.0): Downloading (100%)         
Generating autoload files
spaghetti:anchor-cms dylan$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php >=5.6 but your PHP version (5.5.38) does not satisfy that requirement.
```

Now, my fight is with the OSX default PHP install. I have updated PHP to 5.6, but terminal is still looking at the default install, not the version Apache2 sees. 

From terminal: 
```
$ php -v
PHP 5.5.38 (cli) (built: Aug 21 2016 21:48:49) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```
From phpinfo():
```
PHP Version 5.6.31
--
```

While the last part of the issue is an OSX configuration problem, AnchorCMS is requiring composer for the install, and then not being able to find the `composer` command. The command can be run by typing `composer` into terminal.  Additionally, there is no mention in the documentation of the extra steps necessary to install a development version in a OSX/MacOS environment. (While installing in a linux environment is seemingly effortless by comparison!)

### Context details (if applicable)

- Anchor version: 0.12
- Server setup: Apache2
-System: OSX 10.11 El Capitan
- composer version: 1.6

**Comment by Radiergummi** [comment]
Could you verify whether you're running the `composer install` in the project directory and your file system permissions are ok?
Additionally, getting PHP right on MacOS can be a little frustrating. There is a great tutorial and maintained repository from Swiss agency liip.ch, following that you should be able to install it correctly.
In your case, it seems like the CLI binary is still the previous one.

**Comment by dval** [comment]
It seemed to be 1 part idiocy and 1 part config issue. Running install from project directory was needed. 
Then, after _finishing_ the installation instructions at liip.ch (which is where I updated PHP from to start with. Good to know that is a known source!) CLI and apache were showing the same version of PHP. Anchor found Composer, and I had no other issues.

Configuring PHP properly and working out of the correct directory solved it.
