### ISSUE TITLE
Custom image field supplying default value on saving an article

### ISSUE THREAD

**Issue by ddgroves** [anchorcms/anchor-cms#1239]
### Summary

I make use of custom fields for theming purposes. So in that endeavor, I  have made use of a custom image field to allow a user to have a custom hero image for each article they post if they so choose. However, if you save a new article without supplying an image, the article is saved with a default value of **`content`** which causes AnchorCMS to believe there is an image which causes a blank area with no image where a default image should show if an image is not supplied by a user in my theme. 

A couple temporary workarounds are just to save an image file in Anchor content folder named **`content`** without any file extension or just edit the post delete the **`content`** value in the custom image field and saved the post. The problem returns if you save the post again without an image.

### Expected Behaviour

- A custom image field to still be blank if no image is supplied by the user upon article saving.

### Actual Behaviour

- A custom image field has a value of **`content`** after being saved if user supply no image upon article saving.

### Context details (if applicable)

- Anchor version: 0.12.3 <-- This version seems to be the only affected version from my own testing of older versions.
- Server setup: NGINX 1.13.1, PHP 7.1.6, , MARIADB 10.2.6
I have also tried Apache, PHP with both MARIADB and MYSQL.

**Comment by South-Paw** [comment]
If I understand what you're trying to do, you can achieve it by adjusting the theme and how/where it displays your header image - that or provide a default placeholder image as I did:

```php
article_custom_field('post_image', 'http://placehold.it/500x500');
```

alternatively, you could try if check the `article_custom_field()` and see what it is when it's empty and then only render the image if it is not that value.

**Comment by ddgroves** [comment]
Before Saving:
![image](https://user-images.githubusercontent.com/8341178/34323410-752c7a02-e815-11e7-8a91-9d834853c57f.png)
After Saving:
![image](https://user-images.githubusercontent.com/8341178/34323420-ff21459e-e815-11e7-9de3-9110a1389aaf.png)

This custom image field somehow, after an article is saved, gets this **`content`** as a value, only if you don't upload an image to use. If you upload an image then everything works fine and there is no problem.

My theme is coded to display an uploaded image if there is one and if there is not an image uploaded then a default placeholder image is shown instead like how you suggested. However, the aforementioned problem is occurring and causing the theme to think there is an image to be displayed when there isn't one.

**I have added steps to reproduce the problem in my initial issue report for anybody wanted to reproduce the problem I am experiencing**.

**Comment by South-Paw** [comment]
Ah I see what you mean. But that's weird, I'm also running Anchor 0.1.23 and mine does not do this

After saving a post:

![image](https://user-images.githubusercontent.com/2154764/34324513-cfa241b4-e843-11e7-97ea-912f27026c4d.png)

**Comment by ddgroves** [comment]
So, I did a little digging of my own to see what would be causing this problem and it seems to originate from code located in: `\anchor\models\extend.php` on lines **`113-126`** but **`125`** in particular.

case 'file':
	$value = isset($item->value->filename) ? $item->value->filename : '';

	$html = '<span class="current-file">';

	if ($value) {
		$html .= '<a href="' . asset('content/' . $value) . '" target="_blank">' . $value . '</a>';
	}

	$html .= '</span>
		<span class="file">
		<input id="extend_' . $item->key . '" name="extend[' . $item->key . ']" type="file">
		<input type="hidden" name="extend[' . $item->key . ']" value="' . asset('content/' . $value) . '">
		</span>';

	if ($value) {
		$html .= '</p><p>
		<label>' . __('global.delete') . ' ' . $item->label . ':</label>
		<input type="checkbox" name="extend_remove[' . $item->key . ']" value="1">';
		}

I have a very basic understanding PHP but what I think what the code seems to say is if the value is empty execute lines between **`122-126`** if the value is not empty execute lines **`118-120`** and **`128-132`**. However, if it executes lines **`122-126`** then it will gain a value because a placeholder value is supplied on **`125`** where the whole **`content`** value is coming from and thus the problem. So, I just removed the value on line **`125`** and the problem seems to be resolved.

**Comment by TheBrenny** [comment]
@ddgroves is pretty close with this one.

The thing that's wrong though, is that there is not check to see if `$value` is empty. This could be fixed by adding `122-126` into the preceding `if` statement and then make an `else` statement attached to it. But I'm not at my computer! 😭

**Comment by marc0tjevp** [comment]
I've been having this problem too. I ended up doing a simple check in my theme:

` if (article_custom_field('article_image') && article_custom_field('article_image') != "/content/content")`

**Comment by 14u2ponder** [comment]
I just upgraded to 12.3 and I have this annoying problem. It's even worse because it throws my if statement totally out of whack. Will somebody solve this please!

**Comment by TheBrenny** [comment]
@ddgroves and @14u2ponder I know it's been far too long coming, but if you're still around can you update to 0.12.7 and double check that it now works? :D

**Comment by ddgroves** [comment]
@TheBrenny - I did a fresh install of 0.12.7 and I am still experiencing the bug. If you don't mind me asking, what are you doing to not experience the bug? I edited the "Hello World" article and saved it and and the bug was there, I created a new article and saved it and the bug was still there. The only thing I can do to not experience the bug is upload a image.

**Comment by evansharp** [comment]
I am experiencing this exact bug as well. I'm looking into it now.

**Comment by evansharp** [comment]
Got it:
When a post edit page loads, a hidden form field is populated with the file path stored in the db to be sent and updated on save. The db only stores a filename though, the `content/` part of the path sting is hardcoded at ln. 153. 

_<aside>We should fix this so that nothing is hardcoded and the whole actual path is stored in the `anchor_post_meta` table; as a matter of style if nothing else.</aside>_

Although the empty filename sting is now well-handled in `extend.php` as @TheBrenny described above, the error now persists because the js event handler that fires when a user selects a file to upload is appending a whole new hidden form field rather than modifying the pre-populated one. So when the post is saved, both hidden fields are serialized but only the first one is handled by the model, and it still just contains the hardcoded "content/" path fragment.

I'm hunting now for the actual js event handler attached to extend-field file uploaders and will open a PR when I find it. Should be a simple fix to have it change an attribute rather than append an element.
