### ISSUE TITLE
How to uninstall completely? 

### ISSUE THREAD

**Issue by staticfrost** [anchorcms/anchor-cms#1240]
How to uninstall completely?

**Comment by TheBrenny** [comment]
Hey! I hope I'm correct in understanding that you want to delete your entire Anchor CMS installation, but even though there is no "script" that does this automagically, you have the ability to do it all manually.

Essentially:
1. Delete all the files created by Anchor
2. Jump into phpMyAdmin, and delete the Anchor DB.

This should remove most/all traces of Anchor ever being on your server. The only issue is that you'll lose all your content that you've created. My suggestion would be to manually save all of those...
