### ISSUE TITLE
Output should be stripped of whitespace

### ISSUE THREAD

**Issue by jamestaylr** [anchorcms/anchor-cms#1241]
### Summary

This project should consider using a function [like this one](http://php.net/manual/en/function.ob-start.php#71953) to minify / strip whitespace from rendered PHP output:
```php
function sanitize_output($buffer)
{
    $search = array(
        '/\>[^\S ]+/s', // Strip whitespaces after tags, except space
        '/[^\S ]+\</s', // Strip whitespaces before tags, except space
        '/(\s)+/s' // Shorten multiple whitespace sequences
    );
    $replace = array(
        '>',
        '<',
        '\\1'
    );
    return preg_replace($search, $replace, $buffer);
}
```

This tidies up code sent to the client, saving a few bytes in the process. This also strips comments from themes.

Adding the above code block to any component in `views` (albeit maybe not the most appropriate place) seems to work. I'm looking for any additional thoughts / comments about this.

### Expected Behaviour

- CMS output should be compacted as possible, exposing as little information as necessary about the template and construction of the webpage.

### Actual Behaviour

- Output is not stripped of whitespace.

**Comment by Radiergummi** [comment]
While I appreciate your efforts to improve Anchors performance, removing output whitespace is almost never a solution for speed issues. Properly configured servers use GZIP anyway, which makes the size reduction of removing whitespace almost negligible. And even without doing that, I've seen results of 3-6% output compression. That is simply not worth the effort.  
Then you'll need to consider Anchor has such a lean footprint, it's probably going to be extremely fast anyway.
