### ISSUE TITLE
is_postspage() returns true for articles

### ISSUE THREAD

**Issue by dval** [anchorcms/anchor-cms#1246]
### Summary
`if( is_postspage() ): ` returns true for individual articles. 
This is in contrast to the documentation 

> Returns true if the current page is the posts listings page and false if not.

### Expected Behaviour

I would expect that while the function returns true on the post list page, that individual articles would not be considered lists.

### Actual Behaviour

It seems the individual articles are listed under the route `/posts` which qualifies them as posts. There is no way to distinguish between the Posts page, and it's children. Even testing for a post id `if( article_id() > 0):`  returns true in both cases.  

### Context details (if applicable)

- Anchor version: 0.12.3 (current)
- Server setup: apache2.4, php5.6
- URL: localhost development

**Comment by 14u2ponder** [comment]
I'm confused by what you are trying to do. Articles are generated dynamically with the article.php template.
You can also use is_article to distinguish between the two. But I am more worried that you are trying to use the menu system to create articles.
The whole parent of in the pages dialogue in admin is mainly used to create a navbar menu system and I wouldn't be using it for anything else. I really wouldn't use it at all, but that's me.
If I am off base, please clarify what you are trying to di.

**Comment by dval** [comment]
where  `tweet_url()` is defined in functions.php and builds a tweet for current url:
I was trying to use the following in footer.php 

```
<?php if (!is_postspage && !is_homepage()): ?>
<a href="<?php echo tweet_url(); ?>">Tweet</a>
<?php endif; ?>
```

However, is_article() is what I was looking for. I can use that, with a page field. 
Thank you.
```
<?php if (is_article() || page_custom_field('use_twitter')): ?>
<a href="<?php echo tweet_url(); ?>">Tweet</a>
<?php endif; ?>
```

**Comment by 14u2ponder** [comment]
Yeah, some of the functions aren't documented. A lot of times it is better just to go to the functions folder in the anchor folder and find page.php or whatever and just look at the functions that are there. In this case, it was in helpers.php.
