### ISSUE TITLE
Forbidden permissions on anchor/views?

### ISSUE THREAD

**Issue by Prkns** [anchorcms/anchor-cms#1249]
### Summary

403 Forbidden Permissions on /anchor/views/assets/** once fresh install is completed?

### Expected Behaviour

- Install Anchor as per documentation
- Login using newly created credentials
- Use Anchor

### Actual Behaviour

- Install Anchor as per documentation
- Login screen has no styling, images or javascript allowed (everything showing as 403)

Despite trying to install via download and also composer, these permissions happen every time. Potentially it's an issue with my setup but I've installed previous versions of Anchor no problems and nothing has changed with my local environment. Even changing folder permissions to 777 doesn't seem to want to grant correct permissions?

### Context details (if applicable)

- Anchor version: 0.12.6
- Server setup: MAMP, PHP 7.1

**Comment by tijme** [comment]
@Prkns could you try to add a `.htaccess` file to the `/anchor/views/assets` folder with the following contents?

`Allow from all`

Could you let me know if this fixed it, so I can create a pull-request to fix this issue?

**Comment by tijme** [comment]
Nevermind, I just fixed and verified this myself 😄!

**Comment by Prkns** [comment]
@tijme I was literally just about to do this ha ha
