### ISSUE TITLE
Version Increment

### ISSUE THREAD

**Issue by Prkns** [anchorcms/anchor-cms#1251]
Not so much an issue but it seems that the version number of the new 0.12.6 release is still showing 0.12.3 on [line 26](https://github.com/anchorcms/anchor-cms/blob/5e3044de5d323d5f8ecbf9a3cad9935e87c2f866/index.php#L26) of the index.php file? I've just created a fresh install and this is present in that new install.

**Comment by daviddarnes** [comment]
Good spot, feel free to make a PR if you like 👍

**Comment by Prkns** [comment]
@daviddarnes will do, does the migration number need updating too?

0.12.1 was 211 and 0.12.3 was 220 from what I can see. I might as well do them both in one PR if that's easier?

The only issue is that I don't know what the next migration number is? 😄
