### ISSUE TITLE
Undefined variable "ext" when saving custom image field

### ISSUE THREAD

**Issue by marceickhoff** [anchorcms/anchor-cms#1257]
### Summary

The method `resizeImage` in `anchor/models/extend.php` causes an exception because the variable `ext` is undefined. This happens when saving (and resizing) an image from a custom image field.

### Expected Behaviour

The variable `ext` should contain the image file extension.

### Actual Behaviour

It doesn't. It's undefined.

### Context details

- Anchor version: 0.12.6

### Possible solution

Define the variable:

`$ext = pathinfo($filepath, PATHINFO_EXTENSION);`

**Comment by CraigChilds94** [comment]
@marceickhoff Will take a look when I look at #1259

**Comment by Radiergummi** [comment]
@CraigChilds94 We create the pathInfo, we just don't use it: [anchor/models/extend.php#L209](https://github.com/anchorcms/anchor-cms/blob/master/anchor/models/extend.php#L209)

**Comment by TheBrenny** [comment]
Closing because #1306 fixes this.
