### ISSUE TITLE
Can't change value of custom site variables

### ISSUE THREAD

**Issue by marceickhoff** [anchorcms/anchor-cms#1259]
### Summary

It's not possible to change the value of custom site variables once created.

### Expected Behaviour

If I change the value of a custom variable and click on "Update" it should update the value.

### Actual Behaviour

If I change the value of a custom variable and click on "Update" it doesn't update the value even though it says that it was updated successfully.

### Context details

- Anchor version: 0.12.6
- Server setup: Apache on Windows, PHP 7.1.7

**Comment by CraigChilds94** [comment]
@marceickhoff Sorry about this, I'll take a look into this next as there's quite a few issues relating to this!

**Comment by marceickhoff** [comment]
No need to be sorry! Seems to be a more complex issue than I thought.
