### ISSUE TITLE
Admin stylesheet forbidden

### ISSUE THREAD

**Issue by marc0tjevp** [anchorcms/anchor-cms#1261]
### Summary

After upgrading anchor/views/assets/css/admin.min.css returns a 403 - forbidden message.

### Expected Behaviour

The stylesheet loads normally.

### Actual Behaviour

The stylesheet does not load, no style is applied to the admin environment and login page.

### Context details (if applicable)

- Anchor version: 0.12.6
- Server setup: Apache/2.4.29 (Unix)

**Comment by CraigChilds94** [comment]
This should now be fixed in the latest upload of 0.12.6 if not then we'll be getting another release out soon with some more fixed :)

**Comment by marc0tjevp** [comment]
Is this an upgrade from within the admin environment, I haven't received one.
