### ISSUE TITLE
Database passwords are shown in errors.log

### ISSUE THREAD

**Issue by bleft** [anchorcms/anchor-cms#1274]
Please have a look at this article. 
It describes how you can get the database password.

https://www.bleepingcomputer.com/news/security/anchor-cms-sites-may-be-spewing-their-database-passwords/

adding the following to my .htaccess solved the issue: 

```
<Files *.log>
Order Allow,Deny
Deny from all
</Files>
```

**Comment by CraigChilds94** [comment]
@bleft This has been fixed in the latest release :) but if you're not upgrading then yes, deploying a fix like that to your current setup is recommended
