### ISSUE TITLE
SQL syntax error 1067: similar to previous (closed) issue (#1025)

### ISSUE THREAD

**Issue by ccheath** [anchorcms/anchor-cms#1276]
just installed anchor 0.12.7 and at the end of the install going to the admin page it error'd

my setup: centos 7.4, apache, php7, mariadb (all updated to current versions)

is this the same 1067 rearing its head again?
or a new issue?
>"message":"Database Error: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'date'<\/code><\/p><p><code>SQL: ALTER TABLE `anchor_comments` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `status`","trace":[{"function":"ask","class":"System\\database\\connector","type":"->","args":["ALTER TABLE `anchor_comments` CHANGE `date` `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `status`"]}

(darn markdown is messing up the exact syntax of the error but you get it, right?)

**Comment by ccheath** [comment]
>[root@server anchor]# php -v
PHP 7.1.16 (cli) (built: Mar 28 2018 13:19:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

>[root@server anchor]# mysql -V
mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1

>[root@server anchor]# httpd -v
Server version: Apache/2.4.6 (CentOS)
Server built:   Oct 19 2017 20:39:16

>[root@server anchor]# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core) 

also i've noticed an apache error
>AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
related?

**Comment by CraigChilds94** [comment]
@ccheath That apache error is internal, maybe related to the way your virtual host are configured? not related to Anchor.

And by the looks of it you're using an unsupported version of MySQL. You'll need a more up to date version of MariaDB or you can update the schema in your Anchor installation to remove that query.

I'd recommend MariaDB 10.2 :) the version you have is running MySQL 5.5 and we require MySQL 5.6

**Comment by ccheath** [comment]
i believe my msql version is 15.1 ... but you're probably right that something else on my end went awry (everything was going so smooth until the very end)

i'm going to try and re-install and give it another shot

is there a doc/guide for proper uninstall/reinstall?

thanks
