### ISSUE TITLE
Post save success function not completed on touchscreen Chromebook

### ISSUE THREAD

**Issue by evansharp** [anchorcms/anchor-cms#1283]
After updating to 0.12.7, saving a post appears to hang. The 'wait' cursor remains and the buttons stay disabled. Inspector shows that the form submit ajax function is serializing the data, but the notification on server respoinse is throwing an error. The trace indicates the issue is in the Zepto.js lib, which is being triggered because I'm on a touchscreen Chromebook.

The error might just be with Zepto as that project is pretty stale and may not be supporting the Chromebook. **I tried updating my local copy of Zepto to their most recent version (1.2.0), but this did not resolve it.** Still opened a PR for the upgrade.

### Expected Behaviour

- Click 'Save' button in post editor
- Should wait while ajax submit completes
- Success or error notification appears

### Actual Behaviour

- Browser seems to hang
- Is actually a crashed js script
![Console](https://user-images.githubusercontent.com/1461350/42586461-0455250c-84ed-11e8-8bed-1932465fcc71.png)

### Context details (if applicable)

- File: archor/views/assets/js/editor.js
- Anchor version: upgraded 0.12.3 -> 0.12.7
- Server setup: apache2 on xenial
- https://evansharp.ca/admin/posts/edit/10

**Comment by evansharp** [comment]
Using breakpoints I've determined that the ajax requests is probably not being sent before the exception goes off. 

I don't know Zepto at all so I'm not sure what I'm looking at. Still at it...

**Comment by evansharp** [comment]
After clearing the cache my error has changed. The Zepto issue about `querySelectorAll` has disappeared. I believe this could be the updated version of Zepto (PR #1282) working.

Now it looks like jQuery objects are not being created however, since the `notification` object does not contain an `animate()` function, which it would if jQ were present.

**Comment by evansharp** [comment]
Discovered a small logical error around `editor.js:218` related to the `submitProgress` variable. I have changed the logic to avoid using this var altogether. The feedback on the button itself and in the document title are now as expected. This bug fix will be a part of my eventual PR when I solve the notification animate bug.

**Comment by evansharp** [comment]
As usual, the answer is simple once realized: the Zepto animate function isn't in their core anymore, so updating the Zepto lib to 1.2.0 means the `fx` module needs to be included separately. I'm going to close my previous PR #1282 and open a new one that includes the additional fx module.

**Comment by evansharp** [comment]
Ok the fx module is crazy so I'm going to roll my env back to Zepto 1.0 and see if that was even the problem...

**Comment by evansharp** [comment]
Nope, not the problem. Still not getting a save or a notification of an error on the Chromebook. Will test on another computer asap.

**Comment by CraigChilds94** [comment]
Thanks @evansharp for finding this and looking into it, if you're able to work out the solution it'd be a great help if you could create a PR? :) If not we'll try and look into this as soon as we can!

**Comment by evansharp** [comment]
I'm struggling to build an updated (1.2) version of the Zepto,js library to hopefully improve touch screen support. They removed several of the components Anchor uses (ajax, fx, etc.) from the default distro, so to get them you have to build your own - except that they haven't updated their makefile to work with the latest versions of their own dependencies! 

I'm working right now on patching a local copy of their makefile (I don't know coffeescript though so it's a bit annoying) and hope to get something out of it for an Anchor PR soon. The PR will update us to Zepto.js 1.2 with the modules we require included and any changes in our base to implement it.

The Zepto.js project is looking somewhat abandoned. They have [many outstanding issues and PRs](https://github.com/madrobby/zepto/pulls) and [haven't done much work in the past year](https://github.com/madrobby/zepto/graphs/commit-activity). 

**I suggest we look to migrate the (two?) custom Zepto plugins to something more active-looking like [Umbrella](https://github.com/franciscop/umbrella).**

**Comment by Radiergummi** [comment]
Since I'm a little weary of abstractions over perfectly fine native JS APIs but don't know Umbrella... what problems does it solve that `querySelector()`, `fetch()` and `classList` can't handle? Don't get me wrong, I appreciate your effort here, I just think we should try to get rid of a framework once and for all. Anchor uses so little JS, it's not worth the extra complexity in my opinion.

**Comment by evansharp** [comment]
@Radiergummi I agree!

As you can see, I've finished this patch. It now fixes the actual bug. I think the `.notifications` div was removed from the edit.php files by accident recently, so I replaced it in addition to updating the js.

The upgrade of Zepto was just my first step on this bug since touch standards are evolving and making sure that our shim was up-to-date made sense. I would abandon Zepto as I mentioned above. 

All I see the frameworks giving us right now is handy traversal for implementing the markdown editor and a conveniently packaged ajax function. If we want to roll our own vanilla scripting my only concern is the barrier to contribution and the cross-browser testing we take-on. Honestly my own vanilla-fu is not so strong that I'd be able to help as much as I do for example, meanwhile, these lightweight frameworks are pretty zippy if we can find one that will be maintained.

Thoughts?

**Comment by TheBrenny** [comment]
@evansharp, I dare say your skill in JS is probably just as good, if not better, than my skill in PHP. And realistically, Anchor was sort of my first *'real'* attempt at PHP. So your Java-Scriptsu might actually be more beneficial than some framework which slows things down... Just make sure it's legible and not obfuscated. 😅

@mo, time to say Zeeya to Zepto? *ba dum TSS* 😂😂😂

**Comment by Radiergummi** [comment]
@evansharp In my experience, all the cross-browser compatibility that libraries such as jQuery promise are largely irrelevant as of 2018, unless you intend to support IE. Everyone else uses Firefox, Chrome or Edge anyway, which have feature parity in almost all aspects.  
[This gist](https://gist.github.com/Radiergummi/eccf7acd7916b833f65fc65005c85fdb) I wrote for a project recently is a minimal AJAX wrapper that works in all recent browsers, uses modern JS features and provides stuff like `const response = await http.post('/url', { data: 'test' })`.  

So I think we should be able to pull this off easily, I just need some spare minutes 😭

**Comment by CraigChilds94** [comment]
@evansharp For the time being I've merged in your PR; there are certainly some improvements that could come from the tools we write these things in.

Ideally we should be looking to rip everything out and remove the unnecessary optimisations that are no longer relevant.

But we've got some other big things in the works at the moment, so I'm not sure we can dedicate the time to such a task!

**Comment by evansharp** [comment]
For lack of a better place @CraigChilds94, can I ask you here:

>  we should be looking to rip everything out
yes and no, Zepto is the only JS lib I see being used and it is used for just two very specific things. The implications of removing dependency on it might not be that far-reaching

 > unnecessary optimisations
what optimisations? Do you mean things like the markdown editor/textarea replacement? 

> so I'm not sure we can dedicate the time to such a task
That's why I was volunteering :) I enjoy contributing to this project and would gladly join the team more substantially if you'll have me.

This was just a random bug I set out to fix for my own anchor implementation that turned into a bigger discussion about using JS libs. From everything I learned picking through the frontend files, I feel like dropping the dependency could be pretty straightforward unless there is a planned change in the way Anchor posts data front-to-back; if that's the case then I want into that discussion too!

**Comment by siggi2git** [comment]
`TypeError: f is undefined, can't access property "apply" of it  ....zepto.js`

No notifications after submit. Message does not appears in post and page section :(
Browser: FF
