### ISSUE TITLE
Undefined variable: id  anchor\routes\posts.php on line 283

### ISSUE THREAD

**Issue by echoisles** [anchorcms/anchor-cms#1288]
### Summary
save a new post throw error

### Expected Behaviour
when  field validation failed alert error msg

### Actual Behavioura
chrome Network:
`/index.php/admin/posts/add`
Undefined variable: id
The error has been logged in /anchor/errors.log
Uncaught Exception
Undefined variable: id

Origin
anchor\routes\posts.php on line 283

Trace
#0 E:\envi\anchor\anchor\routes\posts.php(283): System\error::native(8, 'Undefined varia...', 'E:\\envi\\anchor\\...', 283, Array)
#1 [internal function]: {closure}()
#2 E:\envi\anchor\system\route.php(142): call_user_func_array(Object(Closure), Array)
#3 E:\envi\anchor\system\router.php(105): System\route->run()
#4 E:\envi\anchor\system\start.php(41): System\router->dispatch()
#5 E:\envi\anchor\index.php(37): require('E:\\envi\\anchor\\...')
#6 {main}

- Anchor version: 0.12.7
- Server setup: php7.2/win10x64
- URL

**Comment by CraigChilds94** [comment]
@echoisles Thanks for reporting this, I'll take a look :)

**Comment by alinawaz-office** [comment]
I would like to contribute in fixing this issue.

**Comment by TheBrenny** [comment]
Closing because #1305 fixes this.
