### ISSUE TITLE
Version One

### ISSUE THREAD

**Issue by davidapple** [anchorcms/anchor-cms#1289]
I remember discovering and Anchor CMS back in 2014 and helping out with the development a little bit. It's a great lightweight CMS and I love it.

It's a little disappointing that we're now in 2018 and there is still no version one. Have you considered hiring developers to help develop this project into a version one? If funds are a problem, have you considered crowd funding the money to hire some developers?

What would it take to lift Anchor out of alpha/beta?

**Comment by Radiergummi** [comment]
Hey David! Maintaining a project like AnchorCMS requires a lot of work and dedication. There have been a lot of important changes over the last four years, but as you've noted, no version one as of now. That is to say: Anchor is definitely production-ready and used for quite a few sites around the globe.  
Nevertheless, we are still working on the CMS and version one in particular.  
I usually just ignore comments like these, but this bugs me right there: 
> Have you considered hiring developers

I don't know which field you come from, but... I'm a developer. Hiring me costs you around 1k per day currently, and that's cheap. Rewriting Anchor will take around 200-400 days, as a rough estimate.  
If you know where I can crowd fund a quarter million for a cool but small CMS, I'm happy to work on it full-time 😉 

It just takes time. We're all just guys with day jobs, friends and family. Please bear with us: We've not forgotten AnchorCMS.
