### ISSUE TITLE
/version failed to open stream: Connection timed out after login

### ISSUE THREAD

**Issue by nitwhiz** [anchorcms/anchor-cms#1290]
### Summary

After logging in I'm welcomed on https://mydomain.com/blog/admin/login with:
```
file_get_contents(https://anchorcms.com/version): failed to open stream: Connection timed out
The error has been logged in /anchor/errors.log
Uncaught Exception
file_get_contents(https://anchorcms.com/version): failed to open stream: Connection timed out

Origin
anchor/libraries/update.php on line 71

Trace
#0 [internal function]: System\error::native(2, 'file_get_conten...', '/var/www/html/b...', 71, Array)
#1 /var/www/html/blog/anchor/libraries/update.php(71): file_get_contents('https://anchorc...', false, Resource id #4)
#2 /var/www/html/blog/anchor/libraries/update.php(44): update::touch()
#3 /var/www/html/blog/anchor/libraries/update.php(29): update::setup()
#4 /var/www/html/blog/anchor/routes/admin.php(95): update::version()
#5 [internal function]: {closure}()
#6 /var/www/html/blog/system/route.php(142): call_user_func_array(Object(Closure), Array)
#7 /var/www/html/blog/system/router.php(105): System\route->run()
#8 /var/www/html/blog/system/start.php(41): System\router->dispatch()
#9 /var/www/html/blog/index.php(37): require('/var/www/html/b...')
#10 {main}
```
Pressing enter in the address bar (so not actually reloading) removes the error and I'm on the admin panel.

### Expected Behaviour

Dunno, maybe the admin panel. I freshly installed everything and am new to anchor

### Actual Behaviour

An error

### Context details (if applicable)

- Anchor version: 0.12.7
- Server setup: php7.2, apache2
- URL /blog

**Comment by CraigChilds94** [comment]
@nitwhiz It looks like your machine wasn't able to connect to https://anchorcms.com/version

Are you able to visit this in your browser and see if you get a 404 or something?

We need to re-work this version checking stuff, it's basically used to see if there's an update for you

**Comment by nitwhiz** [comment]
/version leads to 404 on my hosted anchor instance, and get a version number on using [https://anchorcms.com/version](https://anchorcms.com/version) I have it in a subdirectory, does it make a difference?
