### ISSUE TITLE
minor issue | circular link to docs in github

### ISSUE THREAD

**Issue by jasonbrown1965** [anchorcms/anchor-cms#1292]
### Summary

This page : 
https://github.com/anchorcms/anchor-cms/wiki

Has a link "Please checkout our docs here" where **"here"** leads back to the same page :
https://github.com/anchorcms/anchor-cms/wiki

### Expected Behaviour

Supposed to go here [?]  :
http://docs.anchorcms.com/

### Actual Behaviour

As above.

**Comment by daviddarnes** [comment]
@jasonbrown1965 thanks for spotting this! Should be fixed now
