### ISSUE TITLE
Is Anchor CMS dead?

### ISSUE THREAD

**Issue by therealmaxmoon** [anchorcms/anchor-cms#1299]
I am looking for an alternative for Wordpress, because Wordpress became a huge and heavy stone and isn't good for small blogs. 

Anchor looks really small and tidy, but I couldn't find a single demo page to test it. And if I visit https://anchorthemes.com/theme to check for good themes, not a single demo link works. 

So my questions are:
- Is Anchor CMS dead?
- Will it be still maintained (Important updates for security)?
- Is there a better blogging software?

**Comment by daviddarnes** [comment]
Hey @therealmaxmoon. Anchor CMS is still maintained, but Anchor is quite a bit older than many other CMSs out there and some of the demos that other people maintain have not been maintained. This is the same for theme demos as they are maintained by the theme developers and not the Anchor team.

I did just spend a minute to find some working demos on Anchor Themes and found quite a few actually:
- https://anchorthemes.com/theme/dark-foundation
- https://thoughtessays.com/
- http://dev.daveis.net/manifesto/

There are many other blogging platforms and CMSs out there and I'm sure if you spent a moment or two to search you may find other options

**Comment by adikwok** [comment]
Anchor is still the one of the  best, for light blog, .. i guess. for theme, learn a bit, and you can bootstrap it. i guess.On Dec 3, 2018 5:32 PM, David Darnes <notifications@github.com> wrote:Closed #1299.
