### ISSUE TITLE
can not install anchor with sqlite

### ISSUE THREAD

**Issue by MercuryhgJiang** [anchorcms/anchor-cms#1302]
### Summary

I want install anchor with sqlite, but some wrong happend. 
![image](https://cnkmmk-pic.nos-eastchina1.126.net/20181220/20181220090250.png)
![image](https://cnkmmk-pic.nos-eastchina1.126.net/20181220/20181220091340.png)

- Anchor version: 0.12.7
- Server setup:  PHP Version 7.1.5 
- URL

**Comment by SiL3NC3** [comment]
Also have the same issue with current version. Why is this closed??

**Comment by FinalTek** [comment]
exact same problem here, install failed with sqlite backend

**Comment by KiraSokolov** [comment]
me too
