### ISSUE TITLE
Anchor CMS's license

### ISSUE THREAD

**Issue by ducnv999** [anchorcms/anchor-cms#1316]
### I have some question

1.  Can I use Anchor cms for my clients?
2. I use Anchor CMS core and develop it to an other CMS, am I allowed? . I will credit to Anchor, of course.

Many thanks! :)

**Comment by daviddarnes** [comment]
Hey, sounds like you need to check out the license for Anchor CMS https://github.com/anchorcms/anchor-cms/blob/master/license.md

**Comment by ducnv999** [comment]
> Hey, sounds like you need to check out the license for Anchor CMS https://github.com/anchorcms/anchor-cms/blob/master/license.md

I have read it, but I'm not sure about my problem.

Can you tell me more clear?

Thanks.

**Comment by Radiergummi** [comment]
Hey @ducnv999, 
as you can see in the linked license document:
 1. Yes, you may use AnchorCMS in a commercial setting without any restrictions,
 2. Yes, you're free to fork the project, modify and redistribute it, as long as you keep the attribution, the same license and disclose your modified source code. For more specific questions, please refer to the GNU General Public License v3.0.
