### ISSUE TITLE
getmypid has been disabled for security reason

### ISSUE THREAD

**Issue by TheRolfFR** [anchorcms/anchor-cms#1317]
### Summary

After instllation, it throwned me an error

### Expected Behaviour

Gets PHP's process ID

### Actual Behaviour

Throws an error

<a href="https://www.noelshack.com/2019-16-5-1555678160-screenshot-2019-04-19-uncaught-exception-anchor.png"><img src="https://image.noelshack.com/minis/2019/16/5/1555678160-screenshot-2019-04-19-uncaught-exception-anchor.png" border="0" alt="1555678160-screenshot-2019-04-19-uncaught-exception-anchor.png - envoi d'image avec NoelShack" title="1555678160-screenshot-2019-04-19-uncaught-exception-anchor.png"/></a>

### Context details (if applicable)

I have a shared host and it is disabled

- Anchor version: 0.12.7
- Server setup: ?
- URL: https://therolf.fr/anchor/

**Comment by Radiergummi** [comment]
There's not so much we can do about this - we rely on the library that uses the function for security reasons...

**Comment by TheRolfFR** [comment]
I had to replace it with a
```php
mt_rand(0,32000);
```
in order to work :/
