### ISSUE TITLE
sqlite

### ISSUE THREAD

**Issue by SiL3NC3** [anchorcms/anchor-cms#1319]
### Summary

A brief but detailed explanation of the issue or bug you are reporting.

### Expected Behaviour

- A list of steps you expected to happen in order

### Actual Behaviour

- A list of steps you actually encountered

### Context details (if applicable)

- Anchor version:
- Server setup:
- URL

**Comment by Radiergummi** [comment]
Please add new details to your issue, I'm going to reopen it then.

**Comment by SiL3NC3** [comment]
Issue edited...
