### ISSUE TITLE
Broken forum, dead project? and a question

### ISSUE THREAD

**Issue by aolko** [anchorcms/anchor-cms#1321]
### Summary

1. Your forum api is broken, returns 500 therefore can't post nor create threads
2. Is this project dead or abandoned?
3. How can i truncate post text (and cut post image) for *all the posts but the recent one*?

**Comment by daviddarnes** [comment]
1. Are you referring to this forum? https://forums.anchorcms.com/
2. Development has very much slowed down but it should be still functional as a CMS
3. You should be able to use php `substr` to truncate the text, and then use an if statement to check if it's the latest post

**Comment by aolko** [comment]
1. yes, since you down't have more than one
2. that sucks
3. sure, how do i exactly get all the posts but the first to apply `substr`? (even if they are paginated)

**Comment by daviddarnes** [comment]
I'm not sure why you're seeing a 500 error for the forum, works fine for me. You would apply the substr filter in the theme template code with some php

**Comment by aolko** [comment]
> I'm not sure why you're seeing a 500 error for the forum, works fine for me.

It happens on new thread/post creation, meaning while making it forum application errors out resulting in nothing.

> You would apply the substr filter in the theme template code with some php

so far you are telling the most obvious things, specifics or a snippet would help, thanks

**Comment by daviddarnes** [comment]
Ah I see, thanks for reporting. Don't appreciate the tone, these GitHub issues aren't for support queries. I just did a quick search and someone has done the same thing and shared it in the forum https://forums.anchorcms.com/d/2351-trim-post-content-based-on-length

**Comment by aolko** [comment]
there you go, a 500 error (it's being displayed in F12 panel as well)
![](https://i.imgur.com/VUcmGZf.png)

**Comment by daviddarnes** [comment]
Did you read the comments though? There's some example code there that will help you get started at least
