### ISSUE TITLE
Editing existing post wipes custom styles

### ISSUE THREAD

**Issue by matronator** [anchorcms/anchor-cms#1325]
### Summary

When you open a post to edit it, the custom CSS field is empty.

### Expected Behaviour

 * Open a post to edit.
 * The custom CSS fields are filled in (saved) from previous edit/creation.

### Actual Behaviour

 * Open a post to edit.
 * The custom CSS fields are empty.

### Context details (if applicable)

- Anchor version: 1.2.7
- Server setup: MariaDB 10.1.38 Debian 9.8, Apache/2.4.25 (Debian), PHP version: 7.0.33

**Comment by matronator** [comment]
Video of the behaviour: [https://www.youtube.com/watch?v=IB7clLIRIb4](https://www.youtube.com/watch?v=IB7clLIRIb4)

**Comment by exts** [comment]
I cannot reproduce on 0.12.7 from a fresh installation.

**Comment by matronator** [comment]
Thanks for checking on a fresh installation, I looked through the code to compare my version of `anchor/views/posts/edit.php` with the original one here and found the issue was on my part.

I made some edits to the JS and CSS fields, so they'd be only visible to Admin and wouldn't confuse "regular" posters and don't know how that happened, but I have copied the code displaying the fields from `anchor/views/posts/add.php` to the `edit.php`, so that's why they were always empty when editing a post.

Thanks again for checking, otherwise I might not have found it, and sorry for the false bug report. So I guess, you can change the label to "Invalid".
