### ISSUE TITLE
composer.json file does not match the regex pattern ^[a-z0-9-]+$ 

### ISSUE THREAD

**Issue by xny-xx** [anchorcms/anchor-cms#1330]
composer.json file seems not to match the expected JSON schema.

I have installed all the required php packages and configured MariaDB normally but when I try to `compose install` or `composer create-project anchorcms/anchor-cms .` at the directory that I am trying to install Anchor CMS), Composer returns only the following error message.

 ```
[Composer\Json\JsonValidationException]                     
  "./composer.json" does not match the expected JSON schema:  
   - type : Does not match the regex pattern ^[a-z0-9-]+$ 
```
I'm using composer version 0.12.7 on CentOS 7.7.1908. I referenced [this article ](https://www.howtoforge.com/how-to-install-anchor-cms-on-centos-7/) and official documentations of Composer and Anchor CMS for my installation.

**Comment by djsipe** [comment]
Check out this and see if your `compose.json` is valid. https://getcomposer.org/schema.json

**Comment by selfagency** [comment]
Change `"type": "CMS"` to `"type": "cms"` and that will fix it.

**Comment by Mrjavaci** [comment]
> Change `"type": "CMS"` to `"type": "cms"` and that will fix it.

Thank You, İt's Working !
