### ISSUE TITLE
Custom Fields To Accept Markdown

### ISSUE THREAD

**Issue by daviddarnes** [anchorcms/anchor-cms#155]
Feature: Allow the html custom field type to accept markdown. 

Not sure if this has already been covered, or is too much trouble too add?

**Comment by plhnk** [comment]
Wow this is really frustrating. The solutions should have been to create a new type of custom field called "Markdown" — Markdown ≠ HTML — been trying to add some custom HTML, NOT md.

**Comment by plhnk** [comment]
(5 years later)

**Comment by TheBrenny** [comment]
@plhnk This has been identified and already fixed. What's the issue?

**Comment by plhnk** [comment]
@TheBrenny Thanks for the reply! I'm using [0.12.1](https://github.com/anchorcms/anchor-cms/releases) and in the extend.php file on ln 49 it still has the md conversion...granted its a prerelease and almost a year old but its the one linked from Anchor site.

**Comment by TheBrenny** [comment]
Oh! I was looking at the `html()` function, not the `value()` function. Cheers for pointing this out.

**Comment by plhnk** [comment]
@TheBrenny cheers! Thanks so much for the help.
