### ISSUE TITLE
Unable to Change a Post's Date 0.8

### ISSUE THREAD

**Issue by codeThatThinks** [anchorcms/anchor-cms#168]
It seems that the date field has gone missing in 0.8.

**Comment by cebreus** [comment]
Hi @idiot , I have same problem. I do not see it in 0.9.2 either. My version came from ZIP archive on Git (0.9.2). Please help me.

**Comment by TheBrenny** [comment]
Did you get the master branch or the Dev branch? because as far as I know, the master branch doesn't allow this.

**Comment by cebreus** [comment]
My installation came from _master_ branch, because _dev_ branch shows some PHP errors. I actually figure problem with direct editing in database. I can not wait for new master version :-)
