### ISSUE TITLE
Unhandled Exception - error message

### ISSUE THREAD

**Issue by VincentStephens** [anchorcms/anchor-cms#241]
Hi, I have an error message popping up on the footer.  The site seems to behave fine so not sure what is going on here. I am a designer not a php developer so cant really help with debugging but would like to fix the issue on my install.  

site: 
clearcutcode.co.uk
![Screen shot 2013-03-19 at 09 57 52](https://f.cloud.github.com/assets/3767496/275065/961cd604-907b-11e2-94f4-55e41f6d8e8a.png)

error: 
Unhandled Exception
Message:

PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20090626/imagick.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20090626/imagick.so: cannot open shared object file: No such file or directory

Location:

Unknown on line 0

Stack Trace:
#0 /home/vincenti/public_html/clearcutcode.co.uk/system/bootstrap.php(79): System\Error::shutdown()
#1 [internal function]: System{closure}()
#2 {main}

![Screen shot 2013-03-19 at 09 57 52](https://f.cloud.github.com/assets/3767496/275060/7f4acd64-907b-11e2-83e1-ae495bee28c2.png)

**Comment by vertexclique** [comment]
occurs in many pages 
![screen shot 2015-02-15 at 00 47 24](https://cloud.githubusercontent.com/assets/578559/6201344/3f640eac-b4ac-11e4-9ad7-950b4a2d9c39.png)

**Comment by CraigChilds94** [comment]
@vertexclique Which version of PHP are you using and have you tried seeing if it's a problem with your php extension configuration?
