### ISSUE TITLE
[Feature] Automatic XML Sitemap Generation

### ISSUE THREAD

**Issue by matthewmorek** [anchorcms/anchor-cms#247]
I would like to request a feature for Anchor to automatically generate "sitemap.xml" file in the root of the site, and regenerate the file each time a new post/page is added, but only when it's set as "published".

It's a basic SEO thing allowing web crawlers to quickly index the site, spot changes, etc.

At the moment, the only way to get a working sitemap, is to use a static sitemap generator, then upload it manually to the server.

**Comment by cebreus** [comment]
I copied the referenced code in a referenced place in file. When and where will generate a file?

**Comment by jakerb** [comment]
@cebreus If you've used Sitemap-Anchor then it will be accessible through http://yoursite.com/sitemap.xml (obviously replacing yoursite.com)

**Comment by cebreus** [comment]
Thanks @jakerb! I tried to search physical file of FTP. But file is generated virtually on http request. This is unexpected :-)

**Comment by jakerb** [comment]
@cebreus No problem! - The generated XML file will grab your latest content on request which is also great for SEO. :)
