### ISSUE TITLE
Social sharing buttons?

### ISSUE THREAD

**Issue by hako** [anchorcms/anchor-cms#250]
Would be a cool feature to implement for anchor, especially at the end of each post. 

for example I don't really see like a facebook sharing button on any of the anchor themes let alone the basic one.

Any thoughts on this?

**Comment by mikebcbc** [comment]
Any updates to this? This isn't working anymore. 

Uncaught ReferenceError: encode is not defined

**Comment by daviddarnes** [comment]
@mikebcbc you mean the plugin? You might want to check the repo for updates https://github.com/jakerb/Share-Anchor

**Comment by protomorph** [comment]
@mikebcbc try replacing `encode(t)` with `this.encode(t)` and  `encode(h)` with `this.encode(h)` in share-anchor.js
