### ISSUE TITLE
Embed HTML or CSS code to the article

### ISSUE THREAD

**Issue by ImBobby** [anchorcms/anchor-cms#306]
I am using Anchor and it is fantastic. I am making my own blog and I find it difficult to embed HTML or CSS code into the article. I have tried by doing &[nospace]lt;div&[nospace]gt;&[nospace]lt;/div&[nospace]gt; like shown below

![Capture](https://f.cloud.github.com/assets/2084193/419338/66b29d76-acc9-11e2-851e-eb071ff1da40.PNG)

but unfortunately Anchor render the tag instead. What I wanna achieve is like this in the article

![Capture2](https://f.cloud.github.com/assets/2084193/419340/894f0540-acc9-11e2-992c-9250c8b5c39f.PNG)

Any idea how can I do so?

**Comment by ShtHappens796** [comment]
I know it's been some time, but it seems that AnchorCMS doesn't like tabs. Literally, one tab character ruins the whole code block during saving and the rest is not rendered. If you try Not to use tabs and use double spaces instead or have the html formatted to use spaces you won't have problems.
