### ISSUE TITLE
Error when try to add new page

### ISSUE THREAD

**Issue by xwlee** [anchorcms/anchor-cms#358]
Uncaught Exception

Database Error: SQLSTATE[HY000]: General error: 1364 Field 'menu_order' doesn't have a default value

SQL: INSERT INTO `anchor_pages` (`parent`, `name`, `title`, `slug`, `content`, `status`, `redirect`, `show_in_menu`) VALUES(?, ?, ?, ?, ?, ?, ?, ?)

Origin

system/database/connector.php on line 52

Trace
#0 /Users/leexiangwei/Sites/anchor-cms/system/database/query.php(205): System\Database\Connector->ask('INSERT INTO `an...', Array)
#1 [internal function]: System\Database\Query->insert_get_id(Array)
#2 /Users/leexiangwei/Sites/anchor-cms/anchor/models/base.php(19): call_user_func_array(Array, Array)
#3 /Users/leexiangwei/Sites/anchor-cms/system/database/record.php(136): Base::__callStatic('insert_get_id', Array)
#4 /Users/leexiangwei/Sites/anchor-cms/system/database/record.php(136): Page::insert_get_id(Array)
#5 /Users/leexiangwei/Sites/anchor-cms/anchor/routes/pages.php(195): System\Database\Record::create(Array)
#6 [internal function]: {closure}()
#7 /Users/leexiangwei/Sites/anchor-cms/system/route.php(152): call_user_func_array(Object(Closure), Array)
#8 /Users/leexiangwei/Sites/anchor-cms/system/router.php(152): System\Route->run()
#9 /Users/leexiangwei/Sites/anchor-cms/system/start.php(36): System\Router->dispatch()
#10 /Users/leexiangwei/Sites/anchor-cms/index.php(33): require('/Users/leexiang...')
#11 {main}

**Comment by Cam** [comment]
Has anyone found a reasonable fix for this for 0.9.2? Or are we not supposed to be using the version on the website anymore?

**Comment by dval** [comment]
@Cam, if you look at the [change](https://github.com/anchorcms/anchor-cms/commit/44c2c4e9f41929cd44b48e5a43a0cc63c379e069) @CraigChilds94 made, it's just swapping a few lines of code. Works.  (Asking about what version should be used as default, is a good question. Maybe that is another issue. I don't know if a roadmap is posted anywhere.)

**Comment by Cam** [comment]
@dval Thanks for the suggestion. Unfortunately that (and the other possible solutions above) haven't worked for me this time (though did in a previous build). Hopefully there will be a stable version someday soon :)

**Comment by daviddarnes** [comment]
@Cam please don't hesitate to voice your concerns, we appreciate that you've used Anchor for this long and continue to do so :)

**Comment by Cam** [comment]
Thanks @daviddarnes. I certainly don't want to appear ungrateful. I freakin love Anchor over the other options out there, despite its teething quirks!
