### ISSUE TITLE
<code> text will be parsed and thus executed

### ISSUE THREAD

**Issue by elegos** [anchorcms/anchor-cms#383]
Even if I use escape characters, I can't make <pre><code>my code</code></pre> to work: the editor will un-escape the characters, and thus displaying them as normal characters( like < and >). I can't escape the tags because at that point the escape character will be visible in the post/page.

Take for example GitHub: if you simply write \<pre>\<code>my code\</code>\</pre> you'll be able to escape tags. You can't (actually) in AnchorCMS, not inside a CODE block, not even with HTML entities (as described before).

<pre><code>&lt;pre&gt;&lt;/pre&gt;</code></pre>

^-- that's actually
<pre><code>&lt;pre&gt;&lt;/pre&gt;</code></pre>

**Comment by the-c0d3r** [comment]
I've tried 3 ticks ```
It didn't work totally, with or without new line before and after the code block
only 4 spaces worked for me. I needed multi-line code block, not single so a single tick only rephrase the code into a one line code, neglecting all indentation and white spaces before the code.
