### ISSUE TITLE
RSS issues

### ISSUE THREAD

**Issue by jdcauley** [anchorcms/anchor-cms#397]
I may be crazy, but on two or three installs I've found that the RSS feed doesn't provide post text beyond the first entry.

**Comment by jeff-h** [comment]
Just wondering — is this in the current release (0.12.1 at this moment)?

**Comment by rwarasaurus** [comment]
Sorry for the late reply, its only in 1.0 which is still being developed

**Comment by Ace2213** [comment]
Is it really that hard to implement this that it keeps getting pushed?
