### ISSUE TITLE
Curly braces in posts

### ISSUE THREAD

**Issue by srccd** [anchorcms/anchor-cms#418]
I am having an issue when posting. I share a lot of code snippets on my site. In a standard PHP if else structure, the curly braces { and } appear fine.

But sometimes I enter something like {Permalink} and it gets stripped out - apparently trying to be processed as a variable. Any way to have the processor ignore these in our posts?

Try to add it to a post and I imagine you will see it happen as well. It does not appear to be related to the Markdown processing.

**Comment by georg90** [comment]
Hi @rwarasaurus sorry for replying to this old topic.
This problem still persists in 0.12.1.
I tried to find any related commit to this (since you mentioned this is a milestone for 1.0), but I didn't find any..

Kindly ask you to point me to the right direction.

**Comment by Gerrit0** [comment]
I haven't looked for the fix, but the replacement is done in the [parse function](https://github.com/anchorcms/anchor-cms/blob/master/anchor/helpers.php#L38-L48) in anchor/helpers.php

**Comment by georg90** [comment]
Hi @Gerrit0! Thanks for your reply and commit.

I added your helpers.php to my blog, with a small edit it's working for me!

I had to leave https://github.com/Gerrit0/anchor-cms/commit/3141c83a962b5a7a9614947acabcb8867969edc2#diff-8c950cc923ffa06d7fb3f15bedef23bbL50 in, otherwise html code isn't parsed

**Comment by Gerrit0** [comment]
That would be because you didn't merge [this commit](https://github.com/Gerrit0/anchor-cms/commit/40cf83eefbb9d659e54fbe7b7a4d43e47e2af00b) in as well. I had several bug fixes going on at once and they got spread out across multiple commits. Glad I could help!

**Comment by georg90** [comment]
What bug is 40cf83eefbb9d659e54fbe7b7a4d43e47e2af00b fixing?

**Comment by Gerrit0** [comment]
I'll have a pull request up soon that goes through all my changes, but in this case it was fixing #1046.

**Comment by georg90** [comment]
Nice! You've done a great job, I'll need to merge my changes into the master soon.. Since I started with the 0.12.1 release I'm missing a lot of commits..

Thanks!
