### ISSUE TITLE
Unknown session driver

### ISSUE THREAD

**Issue by mLupine** [anchorcms/anchor-cms#424]
Howdy guys!

Just installed the newest 1.0 dev on my server to see what's changed since I last used Anchor. Well, I wasn't able to. 

http://cloud.maciej.es/image/2m0t1W1k0D1y

*Edit:* `$config['driver']` in `system/session.php:31` is empty.

**Comment by TimohStudios** [comment]
This issue is really old now, is this still relevant?

**Comment by CraigChilds94** [comment]
@TimohStudios No one has mentioned this for a while, and I've not encountered it personally. So I think not.
