### ISSUE TITLE
Admin account not created.

### ISSUE THREAD

**Issue by MiPnamic** [anchorcms/anchor-cms#428]
Nginx + Php-fpm on a Debian VM

Created the vhosts, taken the sources from git, created the db, gone trough the install process but there's no account in the anchor_users.

I also tracked down the query executed into MySql and no INSERT in that table has passed.

I see that in installer.php is called $this->data();

but there's no "account" trace in that function

![image](https://f.cloud.github.com/assets/1021567/856138/54bbc0d8-f536-11e2-9d88-dd4fdef7dba5.png)

**Comment by idiot** [comment]
Definitely works now.

**Comment by sifex** [comment]
Over two years. Finally getting around to these, huh VI? ;)

**Comment by daviddarnes** [comment]
@sifex FYI this has been constantly worked on for the last two years. This particular bug was caused by using the repo version of Anchor when it's better to use the version from http://anchorcms.com

**Comment by sifex** [comment]
Yea, I gathered as much. I don't run the anchor website anymore.
