### ISSUE TITLE
proposal: Image & filehandling for a portfolio page

### ISSUE THREAD

**Issue by p-h-i-l** [anchorcms/anchor-cms#455]
Hey there,

first of all, i love anchor cms. It is easy to use and really stylish! Little buggy here and there but it's functional and i really enjoy using it! 

But i am interested in using anchor-cms not only as a blog but also for a portfolio. So far i have only seen solutions where the category is being filtered for portfolio and all posts are displayed. 

I would love to see a few things and would appreciate any help archiving this in a way other people can use, too! Or maybe i can do this already?

- [ ] added images shall be resized according to a custom field or max content width (already implemented??)
- [ ] added images (to a page) shall be archived in content/pagename/....all other images according to file structure content/pagename/article ...
- [ ] these images shall be addressable with a function or a shortcode so that it returns the url of the image and the <img> tag is customizable for lazy load or other librarys

i guess these functions would be really basic and help to create an easy image grid portfolio or similar. Further functions could be added to save images as "stacks". 

Let me know what you think, thanks!

**Comment by Radiergummi** [comment]
Well @p-h-i-l I had the same problem and went for a different approach - I implemented page type templates (which have been merged into Anchor) and created the template`gallery.php` for my page type `gallery`. In the markup, theres some JS initializing my gallery and loading all pictures from `/content/gallery/{{gallery-name}}`. Said gallery-name is a custom field specified in the admin panel.  
So to create a new image gallery, I just create a new page, set the page type to gallery, add the custom field gallery-name (could just use the page slug) and upload all desired pictures manually via FTP. ([see here](http://moritzfriedrich.com/photos/morocco-2015))
