### ISSUE TITLE
Password reset issue on 1.0dev

### ISSUE THREAD

**Issue by simon-fraser** [anchorcms/anchor-cms#457]
User resetting password has a bug, the `password_hash()` function is being called twice, once in the model `anchor/model/user.php` and once in the route `anchor/routes/admin.php`. 

I removed from the user model lines `37-39` as all but one password routes have their own `password_hash` and you can place the following in line 51 at `anchor/routes/users.php` to make sure user editing still works.
 `$input['password'] = password_hash($input['password'], PASSWORD_BCRYPT);`

**Comment by TimohStudios** [comment]
Another 1.0 issue from yearrrrrrrrrrs ago. Again, does this still exist? I don't really know my way around 1.0, but as far as I can tell, the structure is totally different from how it was back then. and there no longer is an admin.php, so this same issue can't still be around. If somebody has 1.0 set up, it would probably be good to quickly see if it works, then update the issue accordingly.

**Comment by CraigChilds94** [comment]
@TimohStudios  I don't think so as I believe it's been rebuilt since this.
