### ISSUE TITLE
anchor-plugins repo

### ISSUE THREAD

**Issue by woutervddn** [anchorcms/anchor-cms#463]
There should be an anchor-plugins repo.

One with a couple of plugins already in it. Plugins that are well structured and documented. By all means: I'd love to build some plugins, like social share, but I don't even know how to start with it.

On the website I can't even find a place where plugins are listed. anchorthemes does have http://anchorthemes.com/plugins but let's face it, it's a hidden page.. that won't make developers jump to create this.

**Comment by daviddarnes** [comment]
Repo can be found at https://github.com/anchorcms/anchor-plugins
