### ISSUE TITLE
Medium like WYSIWYG.

### ISSUE THREAD

**Issue by tduarte** [anchorcms/anchor-cms#475]
Navigating the Github discovered this project, a visual editor based on Medium. There are few options and the visual result is immediate, I think it would be a good solution for "humans", since most publishers try to copy Microsoft Word..

https://github.com/mduvall/grande.js

**Comment by morph027** [comment]
Just added the one from lepture mentioned by meskarune (ty) and i love it ;)

http://blog.morph027.de/posts/anchor-cms-with-nice-markdown-editor

**Comment by gautiermichelin** [comment]
+1 for lepture as quoted by @meskarune, thanks for your post @morph027. 

I love to use stackedit.io for writing Markdown, doing copy-paste in anchorcms thereafter. 

![capture d ecran 2015-04-11 a 12 49 24](https://cloud.githubusercontent.com/assets/314697/7101138/6c70ea50-e049-11e4-81c4-692231026a20.png)

The preview on the right is not the most interesting feature, but effects like Lepture on the left part of screen keep the proofreading enjoyable, it's based on Pagedown : http://stackoverflow.com/questions/23051541/how-can-i-use-stackedits-markdown-editor-in-my-application
