### ISSUE TITLE
TextArea - Improving Undo History for Pages, Posts and Comments 

### ISSUE THREAD

**Issue by thumbpiano** [anchorcms/anchor-cms#485]
Is there a plan to improve undo and redo history when writing in the textarea using keyboard strokes such as CTRL-Z, CTRL-SHIFT-Z, etc?

How it might be done:
- Etherpad: Support unlimited "undo" with arbitrary undo model
https://github.com/ether/pad/blob/cb4977238f55f9b2518e7c43a5c769823b0afd45/infrastructure/ace/www/undomodule.js

- Forms: javascript example:
http://www.thomasfrank.se/form_state.html

**Comment by CraigChilds94** [comment]
http://feathub.com/anchorcms/anchor-cms/+13
