### ISSUE TITLE
Admin Interface for Mobile?

### ISSUE THREAD

**Issue by daltonsutton** [anchorcms/anchor-cms#492]
Just was thinking if it would be worth making the admin interface responsive to accommodate mobile users. Just an idea.

**Comment by yannicgraeser** [comment]
I this still in the radar?

**Comment by daltonsutton** [comment]
The Admin area has been modified in the 1.0 update, which will be released somewhat soon from what I know. It'll be responsive for mobile users as well.

**Comment by CraigChilds94** [comment]
http://feathub.com/anchorcms/anchor-cms/+22

**Comment by adikwok** [comment]
anchor.  its fast and elegant.

could be much better with mobile responsive theme for admin area.

unfortunately i can not find any.
