### ISSUE TITLE
Suggestion on the Anchor Admin Post's Page

### ISSUE THREAD

**Issue by daltonsutton** [anchorcms/anchor-cms#496]
I have an idea, and thought it would be cool to share before 1.0 gets released. 

Plus, it might make life easier.

Instead of having the post's page display links to the post's edit page, what if the post's page displays links to the article itself, and showed the article beside it instead of going to another page to display it? 

I **know** I just lost some of you. 

Alright, so we have this (and I think my download of anchor is missing css style due to development):
![screen shot 2013-10-20 at 11 59 42 am](https://f.cloud.github.com/assets/3005706/1368452/8144ba0a-39a2-11e3-86d0-3a204aa958d0.png)

To maybe this (and just by looking at it, you may understand what I'm talking about now):
![after](https://f.cloud.github.com/assets/3005706/1368496/1e36ff24-39a5-11e3-8fa9-082b23127f38.png)

**Comment by CraigChilds94** [comment]
This design has been dropped so this ticket is no longer relevant. Thanks for the feedback though!
