### ISSUE TITLE
Allow User to Post Comments Without Info if in Session

### ISSUE THREAD

**Issue by noahbuscher** [anchorcms/anchor-cms#515]
Possibly add a few LOC that checks to see if the visitor on site is logged in as a user  (check for session cookie) and if they are, don't require them to put their name and email into the contact form. Just grab the data from the 'Users' database.

**Comment by noahbuscher** [comment]
@idiot Welcome back. :wink: Glad to see this project back in action.

**Comment by daviddarnes** [comment]
@noahbuscher it was never out of action.
