### ISSUE TITLE
Sample plugin like Hello Dolly

### ISSUE THREAD

**Issue by aalaap** [anchorcms/anchor-cms#518]
How about including a sample plugin similar to WordPress' [Hello Dolly](http://wordpress.org/plugins/hello-dolly/) so beginners can get started with plugin development more easily?

I'm looking at developing some simple plugins that insert content into the header, footer or some places in between, but I haven't been able to figure out much by reading the sparse documentation.

**Comment by CraigChilds94** [comment]
http://feathub.com/anchorcms/anchor-cms/+20
