### ISSUE TITLE
Child Page's link goes to 404

### ISSUE THREAD

**Issue by xiaozj** [anchorcms/anchor-cms#523]
I'm trying out anchor and ran into an issue.

I created a child page called "Test Page" under the default "Posts" page.

So the link in the menu on the default theme points to the url "my_site/posts/test-page".

However that link goes 404, and the actual, accessible url is at "my_site/test-page".

Obviously something's wrong here.

Here's my test setup: http://www.miragecraft.com/test/anchor/

**Comment by CraigChilds94** [comment]
I've finally fixed this.
