### ISSUE TITLE
Add url rewriting information for lighttpd and nginx

### ISSUE THREAD

**Issue by meskarune** [anchorcms/anchor-cms#583]
The following rewrite rules work for me with Anchor CMS on Lighttpd web server:

    url.rewrite-if-not-file += ( "^/(.*)\.(css|js|jpg|png|gif)$" => "$0",
                                 "^/blog/(.*)$" => "/blog/index.php/$1" )

These rules should work with Nginx, but aren't tested:
    
    error_page 404 /index.php;
    
    location / {
      if (!-e $request_filename){
        rewrite ^(.*)$ /index.php/$1 break;
      }
    }

I would love to see this information added your documentation on clean urls. Thanks!

**Comment by drFabio** [comment]
For my admin on http://DOMAIN/index.php/admin/login i am getting the following error : 

rewrite or internal redirection cycle while internally redirecting to "/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/admin/login", client: 189.121.42.43, server: 107.170.73.32, request: "GET /index.php/admin/login HTTP/1.1", host: "dexus.com.br"


with


	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files       $uri $uri/ /index.php$uri;
		# Uncomment to enable naxsi on this location
		# include /etc/nginx/naxsi.rules
	}
	location ~ \.php$ {
		try_files  $uri /index.php$uri =404;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
                
        }
	location = /favicon.ico {
		access_log      off;
		log_not_found   off;
		#return         204;
	}



So I added the following:

	location ~ index\.php(?<clean_url>.+)$ {
		try_files  /index.php$clean_url =404;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
	}

To at least get a 404.  Anyhow the point is that without the last part a infinity loop was happening
