### ISSUE TITLE
Can't use PrismJS and HTML

### ISSUE THREAD

**Issue by idriskhenchil** [anchorcms/anchor-cms#605]
So i'm using PrismJS for the code on my pages. I can't use the HTML for some reason. This one works fine http://colourity.com/posts/generate-a-random-string But I think that since the editor interprets the HTML and tries to display it, it messes up Prism. Any ideas on how I can disable it?

**Comment by csengineer13** [comment]
All, I was having the same issue. It's hardly a perfect fix, but I got the output I wanted by doing the following:

```
<pre>
	<code class="language-javascript">
<script>
<!-- Code goes here -->
</script>
	</code>
</pre>
```

When rendered, the script tags aren't shown, and the highlighting for the HTML is *mostly* correct. This issue doesn't appear to be specific to PrismJS, but rather with wrapping HTML in code blocks period.

This should probably be made an official bug.
