### ISSUE TITLE
Uncaught Exception v0.9.2

### ISSUE THREAD

**Issue by jufracamo** [anchorcms/anchor-cms#624]
![capt](https://cloud.githubusercontent.com/assets/6473248/3067793/e1c91c6c-e286-11e3-8c5e-be4ac6e7f6b2.PNG)
What am I doing wrong?

**Comment by idiot** [comment]
Tested in PHP 5.4 on a few envs and it all looks fine now. Any more problems, let me know and I'll look in to it more.
