### ISSUE TITLE
Browser Testing

### ISSUE THREAD

**Issue by nblackburn** [anchorcms/anchor-cms#647]
It would appear that the CMS could benefit some browser testing as various elements are not displayed consistantly across all modern browsers.

> A main focus of this would be custom form controls.

**Comment by saucytomato** [comment]
I use a bunch of different browsers with Anchor (Chrome-based, Safari, Edge, and Firefox) and certain features don't work in all browsers. I'll post some screenshots

**Comment by daviddarnes** [comment]
@saucytomato strange, because I've been using nothing but chrome and everything works fine for me :/

**Comment by CraigChilds94** [comment]
@saucytomato is this on the latest version?

**Comment by saucytomato** [comment]
0.12.1

They seem to work on Chrome 48.
When I wrote above, I was running on Chrome-Based Browser, which has a few issues since it's still in beta.

**Comment by daviddarnes** [comment]
I think this issue needs to be broken down better. I'm not surprised there's bugs on certain browsers, but we need to scope in issues to specific elements so this doesn't become a mass list of bugs. Eg "Drag & drop on Chrome" or "Edit menu on Edge".

**Comment by CraigChilds94** [comment]
Good idea @daviddarnes I think we should close this issue as it's not specific, it's also not really and "issue" it's a suggestion.
