### ISSUE TITLE
Line breaks not being rendered

### ISSUE THREAD

**Issue by nblackburn** [anchorcms/anchor-cms#661]
Line breaks `\n` are not being rendered correctly in the markdown pre-processor. I have fixed this issue on my fork of the project which can be found here: https://github.com/nblackburn/anchor-cms/commit/1d6e318f1cd73016dd5768c0e145343518f8df7c

**Comment by minxomat** [comment]
However, it is an issue. And more common flavors of markdown, including githubs, support this. Also, every line break in code blocks is ignored - and this is not a good default behavior. Right now, I have to put an HTML `<br>` tag at every single line end to force a break.

**Comment by daviddarnes** [comment]
@minxomat are you not using two returns as mentioned in the comments above? Using two returns will close the `<p>` allowing you to start a new paragraph.

**Comment by minxomat** [comment]
Not inside Code. And outside code, there should be an option for a standard line break (i.e. <br>), not a full paragraph break.  This makes it hard to format posts :) . I'm just used to it (github, wiki etc.). Maybe create an option? Just a suggestion, though.

**Comment by daviddarnes** [comment]
@minxomat can you give an example? You comment is kind of confusing.

**Comment by TheBrenny** [comment]
I always thought that the break between a `</p>` and `<p>` tag was the same spacing for a `<br>` tag by default. Try changing the CSS of your website and/or update to 0.9-dev. This will convert all markdown upon saving.
