### ISSUE TITLE
PDO_Exception in installer

### ISSUE THREAD

**Issue by apmuthu** [anchorcms/anchor-cms#695]
![anchor_cms_install_db_state_on_error](https://cloud.githubusercontent.com/assets/2995044/4331028/b005bb20-3fbc-11e4-8f8e-687560124923.png)
On the final page during installation we get:
````
Database Error: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.

SQL: INSERT INTO `anchor_meta` (`key`, `value`) VALUES(?, ?)
````
This error occurs only on Windows XAMPP v1.7.3 / PHP 5.3.1 with mysql root user and blank password.

**Comment by CraigChilds94** [comment]
I think this was a MySQL server config issue as this hasn't been replicated in a long time.
