### ISSUE TITLE
Drag and drop in 0.9

### ISSUE THREAD

**Issue by TimohStudios** [anchorcms/anchor-cms#704]
I think drag and drop support for images could definitely be implemented in 0.9 already, as it's (as it stands) really confusing. The site says you can drag & drop, and the screen you see when you try to do so also doesn't tell you it doesn't work for images. Now, tovic has a solution out on the forum (which I can't link cause it's down and I can't look up what to link), and Mazzo has it in a [branch here on GitHub](https://github.com/mazzo-/Anchorcms-0.9.2-drag-drop-fix) (though it isn't a full version of Anchor). I believe there were even more branches with fixes available on the forum, but I can't take a look at that right now.

**Comment by TimohStudios** [comment]
#779 Also addresses this, and so does #756 in some way. I think it's best to keep just on issue open for the same problem.

**Comment by daviddarnes** [comment]
@TimohStudios which issue best addresses the problem?

**Comment by TimohStudios** [comment]
Taking a look at 756, it really isn't the same. 779 is, and a more people have expressed their problems with it there. But really, the best one is #813, but the PR has some issue. If @CraigChilds94 could take a look at that, both could be closed

**Comment by daviddarnes** [comment]
@TimohStudios I'd just to refine them to one issue really. Easier for everyone to track and reduces admin.

**Comment by CraigChilds94** [comment]
@daviddarnes I agree. We've got a lot of duplicate/related posts on here and it's hard to manage them all. Often we've already fixed things relating to an earlier issue but someone else has reported it before it's been released.

**Comment by daviddarnes** [comment]
@CraigChilds94 ah ok, well in that case we need to round up all the open issues directly related to the drag 'n' drop image uploading and decide on an appropriate one to be the 'master' issue. Then related the others to it and close them.

**Comment by TimohStudios** [comment]
[https://github.com/anchorcms/anchor-cms/commit/04d0f2540169c438b62d04e599bafc63c617fdf7](This is madness.) :heart: @CraigChilds94
