### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by TimohStudios** [anchorcms/anchor-cms#706]
It kinda drives me nuts that sometimes translations are accepted, and sometimes they redirect people to PR at the translations fork. I can understand you don't want all that much languages in it by default, but just these 3 don't really make sense either. My suggestion: Link to the translations repo in the readme, only English by default. And that isn't even my first language.

**Comment by daviddarnes** [comment]
In #540 @shoostar [mentioned some good ideas](https://github.com/anchorcms/anchor-cms/issues/540#issuecomment-30665645) on how to approach this. I think it would be worth while checking out the most commonly requested languages by our users, as well as commonly used languages from the web and coming up with a set that will apply to most of Anchor's users. The rest can clearly noted in the readme.md.

**Comment by CraigChilds94** [comment]
@daviddarnes great idea, I think we need to work on this sometime!
