### ISSUE TITLE
Feature: Theme Options in Admin

### ISSUE THREAD

**Issue by TimohStudios** [anchorcms/anchor-cms#738]
How awesome would it be if the [theme options](http://anchorcms.com/docs/function-reference/config) would be editable from the admin interface. I'm currently thinking somewhere under `Extend`. If I also could define them to be (for example) image fields, it would bring Anchor theming to a whole new level.  
  
This might be seen as a 1.0 feature, but I want it now! Seriously, from what it looks like, 1.0 is just an idea, something to push everything to so it doesn't need to be done now.  
  
Idiot actually says something about this in #58 (that was back in 2012) and it still hasn't been implemented.  
  
I wonder what all of you people think about this. Let me know.

**Comment by TheBrenny** [comment]
@CraigChilds94, in response to [your comment][1], why not have a table:
**Name**: ThemeConfig
**Fields**: id, theme_name, value

It really just depends whether or not this feature would be as useful as we all hope...

[1]: https://github.com/anchorcms/anchor-cms/issues/738#issuecomment-58695773

**Comment by daviddarnes** [comment]
This is very much a desired feature. As Craig said, a config that writes the fields to the DB if they don't already exist will be the best solution. Would also be good to share common field names so switching themes is a smooth process. Eg `thumbnail` or `subtitle`.

**Comment by TheBrenny** [comment]
Oh! So it's like automating the extends of a theme? So a user doesn't need to manually add the Extend fields?

This would indeed be very well utilised. I misunderstood the idea. Whoops.

However, @daviddarnes's idea is a great idea, having common field names - but if each config file will  write to the DB, then I don't think that common field names is necessary? If each theme utilises it's own fields, then on every theme change we can delete all the previous theme's fields, and insert the new fields. Perhaps we could just have the config file as an SQL file to minimise the size of Anchor? But on the other hand, that could just deter web developers who don't know SQL from making potentially amazing themes with great extend fields.

Or I could still be getting this whole topic wrong... :')

**Comment by daviddarnes** [comment]
@TheBrenny I'm not keen on deleting fields when switching themes, just incase a user switches theme by accident and then switches back only to realise all their values have been cleared :/

**Comment by TheBrenny** [comment]
Have an extra field in the table which contains the theme's name? But then conflicting theme names... How about a UID (which could be set by the developer in the config file)?

It seems that this implementation needs a little more though than anticipated. The overall implementation idea is up to you dev guys though! :P

**Comment by CraigChilds94** [comment]
http://feathub.com/anchorcms/anchor-cms/+18
