### ISSUE TITLE
Feature: ability set template for each item of category

### ISSUE THREAD

**Issue by alexander-gess** [anchorcms/anchor-cms#740]
Would be nice to have ability set template for each item of category.

**Comment by CraigChilds94** [comment]
I'm looking back at this and it seems pretty straight forward. I'll have a go at implementing it tonight xD

**Comment by CraigChilds94** [comment]
I've added this functionality into the dev branch. And following previous convention with page and article templates.

`category-{category_name_here}.php`

**Comment by daviddarnes** [comment]
@CraigChilds94 perfect :ok_hand:
