### ISSUE TITLE
Feature: Store both Markdown and rendered HTML when saving pages and posts

### ISSUE THREAD

**Issue by james2doyle** [anchorcms/anchor-cms#744]
I was looking through the Markdown class yesterday, wondering if [Parsedown](https://github.com/erusev/parsedown) could replace it, and I noticed that the database only saves *the Markdown content* for posts and pages.

I was wondering why is this? Wouldn't it be more efficient to save the markdown *and the HTML* into the database instead of having a "render content as HTML" function for the frontend? The markdown for a page is probably modified much less than the number of times the HTML is viewed by site visitors.

The `article_html` function could be reduced to the same weight as reading any other static property of a page or post.

I can tackle this feature if there is an actual need for it. I realize adding Parsedown, would be a different conversation.

**Comment by meskarune** [comment]
I know this issue already has a pull request, but I don't agree that storing both html and markdown is the way to go. It is very redundant (essentially you are storing the same data in different formats) and sorta invalidates the whole reason for using/storing markdown in the first place. (if you store html, why even have markdown in the database?)

The real solution to speed up anchor and reduce database hits is to use caching.

You can configure an opcode php cache easily and then drop varnish onto your web server stack.

Opcode caching in php 5.5:

edit php.ini, add/uncomment the following:

    zend_extension=opcache.so
    opcache.memory_consumption=512
    opcache.max_accelerated_files=50000

For older versions of php, you can just as easily use APC.

Quick varnish tutorial for Apache: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-varnish-with-apache-on-ubuntu-12-04--3

There are of course many other caching solutions available, I just wanted to show that implementing this isn't too complicated, and really should be standard if you host lots of websites.

I will grant that for someone who has a single Anchor site, installing varnish could be seen as excessive/unnecessary. For this type of user, the ideal solution would be to have Anchor implement it's own cache system, or save content as html in the database.

So I guess the real question is this, does Anchor plan to implement caching sometime in the future? 

This could either be in the main code base, or implemented as a plugin so users can choose which caching solution they want to use. If Anchor will have it's own caching solution, it doesn't make sense to save html along with markdown in the database long term.

If Anchor won't be implementing a caching solution, would you want/expect your users to configure their own? We could just add a recommendation along with information/links in the documentation for setting up a caching proxy and opcode cache. I wouldn't mind helping to write some docs on optimizing your server for the best Anchor performance.

If you expect most users to use Anchor without caching, and don't plan to implement caching, then saving content as html for faster page rendering makes sense. If you go this route, is there a way to remove markdown from the database so you aren't storing the same information twice?

I know you *could* just store both markdown and html, but this really bothers me. What if I have 2000 Anchor installs on a host for various clients. I am now storing the same information twice for each site. Just thinking in terms of scale, this seems very inefficient.

ps: +1 for parsedown

**Comment by james2doyle** [comment]
I think the main thing to not get caught up on, is that *markdown is being used for it's ability to abstract HTML*, not reduce data size. If every client (as in customer/end user) could write HTML and create perfect blockquotes/links/image tags etc., then markdown wouldn't exist and we could stick with a single "HTML" column. 

I wish there was a cache in Anchor, that would make this PR less relevant. There really isn't one at the moment, and *not every host provides the tools to install extensions or tweak existing ones*. So things like APC and opcache would be great, but sometimes you don't have that luxury. This is the "cheapest" way to gain a 98% performance increase without breaking backwards-compatibility, or adding to/rewriting the core classes.

> What if I have 2000 Anchor installs on a host for various clients.

There is always going to be a case of *"but what if I have a [X] situation with a [Y] setup?"*. The goal of Anchor seems to be that they are shooting for the highest server coverage and best host support. If you are at the scale where you need to be running 2000 instances of something, I would suggest a system that already has things like caching and multi-site support.

> I am now storing the same information twice for each site

Not quite. That data is not really *the same*. We are storing "uncompiled" raw markdown, and then we are storing the "compiled" results. This data is not identical. *Before* you had a site that was 98% slower, so there is a significant return on that additional data. We can argue the cost of SQL table columns all day. *Why store the slug when you can just slugify the title column when the page data is pulled?* 

The point is to reduce functions and string manipulations that happen each time a page is called. It's the same thing opcache and APC are trying to do. They try to reduce the number of times a function is called when the results are going to be the same.

This approach seems to be a pretty common tactic in the world of markdown-supported CMSs. It really is a cheap way to squeak a little more performance out of the site, without too much of an overhaul.

**Comment by lifehome** [comment]
@james2doyle 

Sorry for pushing this up a bit while the PR is almost ready to go, but I'm still confusing after reading this pile of comments and the PR commits.

(Please correct me if I'm wrong)

So this feature is going to store two things: "raw markdown" and "compiled html"
And this is supposedly to increase the speed on rendering the client-side page loadup.

If so, just being curious, that, why not creating a encode/decode function? Like render html and store into the database, and "decompile" it back to markdown/html-mixture/somewhat-the-content for editing? This might slow down alot/a bit at the backend, but just an idea.... (messed up mind, dunno what I'm typing... lol)

**Comment by james2doyle** [comment]
> So this feature is going to store two things: "raw markdown" and "compiled html". And this is supposedly to increase the speed on rendering the client-side page loadup.

Yes, you got it.

> why not creating a encode/decode function? Like render html and store into the database, and "decompile" it back to markdown/html-mixture/somewhat-the-content for editing? This might slow down alot/a bit at the backend...

Well you basically gave the reason why, it would be slower.

The main thing is, and I've hammered this point enough, that the change in this PR is so minor, yet we get quite a nice performance boost without an sacrifices. I actually removed some parsing functions because they aren't needed anymore.

**Comment by hubply** [comment]
I implementing rabid system for asia company and some complaint on govement , On comment store pattren, I and my team seperate to strore 3 storage (1 index, 1 raw html, 1 normal text ,and sure system are not on mysql or some sql directly (overhead hardware on lot comment) ,I store on cache (redis) first and seperate in pattren db level ),It's complexier but on my clients is fine on them.Try it.

**Comment by CraigChilds94** [comment]
**Update:**

I'm still working on getting this implemented. Last time I pulled down the PR to my local I had some issues. It might take a bit of working out but this will be a considerable change to anchor! Again thanks for all of your hard work @james2doyle

**Comment by CraigChilds94** [comment]
This has now been merged in! Thanks for everyones help on this! :D
