### ISSUE TITLE
500 internal server error during installation

### ISSUE THREAD

**Issue by maple48** [anchorcms/anchor-cms#746]
I was told to post this issue here from the AnchorCMS forum:

Whenever I try to install AnchorCMS, it keeps showing a 500 internal server error from ../install/index.php onward. Though I can view the first installation page where it says ../index.php just fine. I've checked the requirements and everything seem to be updated. Any idea of how to fix it?

**Comment by erm3nda** [comment]
I got same problem (error 500), using default .htaccess posted here (the same of the readme) under the 0.9.2 version of anchorcms. I'm running php 5.4 and double checked for rewrite module running `/usr/local/apache/bin/apachectl -M | grep rewrite`

Switch back to php 5.3 is not an option.

My error code on the apache's log
[Tue Mar 17 11:31:19 2015] [alert] [client 178.239.240.202] /home/anchor/public_html/.htaccess: Illegal option <IfModule

Im not sure but i guess this is some character encoding issue on my side.
I got the same problem parsing a conf file on the owasp rules (mod_security) and still not found the origin (https://stackoverflow.com/questions/28375602/syntax-error-on-owasp-rules)

@TimohStudios Love your Avatar (i've updated mine). Send me pm or whatever.

**Comment by CraigChilds94** [comment]
@erm3nda  Hmmm that's weird. Have you tried any newer versions of PHP, or even the `0.9-dev` branch of Anchor?

**Comment by CraigChilds94** [comment]
as @maple48 Is no longer using Anchor for his project and this issue is stale I will be closing it. If this issue persists for anyone then please open a new issue following the new format so that we can more easily debug it, thank you :)
