### ISSUE TITLE
Feature: Better comment management in Admin

### ISSUE THREAD

**Issue by bennettscience** [anchorcms/anchor-cms#747]
I have a demo site up for my Anchor theme and I ran into a problem which prompted this issue. I forgot to turn off "Auto allow comments" in the site and then didn't check it for a few weeks. I ended up with a *ton* of spam comments on one post demonstrating how they worked. So, I went into the admin settings and then went through...one by one...marking those as spam.

Is there some way the Admin interface could improve the comment moderation functions? Checkboxes, at least, would be great. Right now, you have to go into each individual comment to make changes, and if you have dozens (let alone hundreds) it gets arduous.

**Comment by CraigChilds94** [comment]
http://feathub.com/anchorcms/anchor-cms/+17
