### ISSUE TITLE
Feature: Image / File Uploading

### ISSUE THREAD

**Issue by danoxide** [anchorcms/anchor-cms#756]
I think there should be a file manager (upload, remove, rename files to contents/ directory).

**Comment by daviddarnes** [comment]
Is this the main issue for "Drag & Drop File Uploading" feature? Here's the results of my testing…

![anchor-cms-file-upload](https://cloud.githubusercontent.com/assets/1177460/7019381/42c21ef8-dd07-11e4-94af-13a0501faf10.gif)

…AKA it works! Tried a PDF and a GIF, works with no apparent errors.
