### ISSUE TITLE
Make Pages as well as Posts searchable

### ISSUE THREAD

**Issue by martindavies** [anchorcms/anchor-cms#771]
There have been a few requests that the search functionality be extended to pages as well (see http://forums.anchorcms.com/help/make-pages-searchable/) 

This has already been written by BrainEB

```
public static function search($term, $page = 1, $per_page = 10) {
		$query = Base::table('pages')
			->where(Base::table('pages.status'), '=', 'published')
			->where(Base::table('pages.name'), 'like', '%' . $term . '%')
			->or_where(Base::table('pages.content'), 'like', '%' . $term . '%');
			
		// $total = $query->count();
		
		$pages = $query->get(array(Base::table('pages.*')));
			
		return array($pages);
	}
```

But I'm not sure where it needs to be implemented. 

Thanks,
Martin

**Comment by CraigChilds94** [comment]
Sorry I haven't got around to looking at this :( but yeah this should definitely be finished off.

**Comment by CraigChilds94** [comment]
That has now been implemented and is currently being tested :D
