### ISSUE TITLE
OpenGraph Data Implementation - 1.0?

### ISSUE THREAD

**Issue by CSCG** [anchorcms/anchor-cms#772]
Hey guys,

I've added an easy way to pull post data for OpenGraph / Facebook from posts pages using post variables in the meta tags of the individual post page. I've implemented this in the Barhop theme, however I'm doing some testing for it this week to see if other themes are playing well (and they should...it's just a meta lol). The issue is my implementation is pulling from the featured-image added post tag, where I realize the stock install and other themes won't have that. I'm brainstorming an elegant workaround...the first of which would be to refer to images in a `<p>` or `<div>` and ignore anything in the layout directly. I think while this is trivial, it would be a good addition for 1.0.

Here's a preview attached, this issue is just a bit of a reminder that I need to push this out soon. It's a trivial update and issue, but something as minimal and elegant as Anchor should have an implementation like this that just works, and it does! Let me know if you think of a better way, eventually I want to extend this into an extend plugin that really helps to optimize sharing of Anchor content on social media. Does anybody else have any ideas for lightweight additions to the code to help facilitate sharing and SEO? 

<img src="http://cdn.moonserv.com/images/og-data.png">

**Comment by TimohStudios** [comment]
I think this can be closed, right?

**Comment by daviddarnes** [comment]
@TimohStudios correct!
