### ISSUE TITLE
Bug: menu_render can't handle child menus properly

### ISSUE THREAD

**Issue by AbelToy** [anchorcms/anchor-cms#774]
I've noticed menu_render has a strange behavior. It only renders the first item and its children to me.

I noticed Registry::get("menu") returns a Item object with the menu items inside.

The way Item works conflicts with menu_render, as I don't think it supports multiple iterations through itself. So, this weird behavior occurs.

I was trying to implement my own menu_render adaptation that used Foundation's menu styles, and this occurred...

**Comment by csengineer13** [comment]
Registry::get("menu"); gets a list of all of the pages in the menu.

menu_render calls Registry::get("menu") to get that list of pages and then turn it into a nested list. I don't think there's a bug, as calling menu_render returns the following for me:

<code>
<ul>
    <li><a class="active" href="/posts">Posts</a>
        <ul>
            <li><a href="/posts/tier-2">Tier 2</a>
                <ul>
                    <li><a href="/posts/tier-2/tier-3">Tier 3</a></li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
</code>

**Comment by AbelToy** [comment]
That works because there's just a single menu item with children. The problem I had was with multiple top-parent items that had children themselves, like this:

- Home
- Games
  - Action
    - Shooter
    - RPG
  - RTS
- Movies
  - Horror
  - Comedy

**Comment by csengineer13** [comment]
Thank you for the example @AbelToy.

I was able to duplicate the issue; while doing so I noticed that if an Anchor site were to have more than a few nested pages that management becomes difficult. I do think that if this is something that we want to support, then the administration side of this should be changed to make nesting pages more intuitive.

I'll try to knock out a revised render_menu post the solution here for you sometime this weekend.

**Comment by csengineer13** [comment]
@AbelToy && @CraigChilds94 

Here is how I changed *menu_render()* to get the desired result.

```
function menu_render($params = array()) {
	$html = '';
	$menu = Registry::get('menu');

	// options
	$parent = isset($params['parent']) ? $params['parent'] : 0;
	$class = isset($params['class']) ? $params['class'] : 'active';
	$index = isset($params['index']) ? $params['index'] : 0;

	foreach($menu as $item) {
		if($item->parent == $parent) {
			$attr = array();

			if($item->active()) $attr['class'] = $class;

			$html .= '<li>';
			$html .= Html::link($item->relative_uri(), $item->name, $attr);
			$html .= menu_render( array('parent' => $item->id, 'index' => $menu->key()) );
			$html .= '</li>' . PHP_EOL;
		}
	}
	// Reset our index before returning
	$menu->rewind();
	$menu->next();
	while($index > 1){
		$menu->next();
		$index--;
	}

	if($html) $html = PHP_EOL . '<ul>' . PHP_EOL . $html . '</ul>' . PHP_EOL;

	return $html;
}
```
