### ISSUE TITLE
Disable Markdown

### ISSUE THREAD

**Issue by nickburrett** [anchorcms/anchor-cms#777]
I have commented out this:

function article_markdown() {
return parse(Registry::prop('article', 'html'));
}

And replaced it with this:

function article_markdown() {
    return Registry::prop('article', 'html');
}

Yet it appears that Anchor is still inserting "p" tags where I have left an empty line?

**Comment by Svetozar95** [comment]
my verison 0.9.2. i hange code: 

function article_html() {
        return Registry::prop('article', 'html');
}


code works!

**Comment by NathanLawrence** [comment]
I agree with the other commenters. article_html() seems like a much better practice in this situation. Would this solve your problem? If so, how do you recommend amending documentation so this is clearer?

**Comment by idiot** [comment]
Yes, should be using `article_html()`.
