### ISSUE TITLE
File upload not working

### ISSUE THREAD

**Issue by wirehack7** [anchorcms/anchor-cms#779]
I installed anchorcms on Debian wheezy with Apache2. All neccessary packages are installed. Also all files and folders are belonging to www-data, the user which Apache2 runs at. When I drag a image inside the input field it gets not uploaded, the overlay appears "Upload your files", after releasing the mouse button nothing happens. No error, no upload. I am using the latest Chrome browser for Windows.

**Comment by CraigChilds94** [comment]
I know this is a big issue and should really be dealt with but I'm struggling to find the time, so if anyone can suggest a fix please make a PR.

**Comment by gautiermichelin** [comment]
First page on anchorcms.com : 
"Drag-n-drop
Want to add some custom CSS, JavaScript, or an image to your post? Just drag the file over to Anchor, and we'll do the rest." 

At least, it should state that this is in develop branch... no ?

**Comment by csengineer13** [comment]
To clarify requirements:
- Drag & Drop support for images or all file types?
- Ability to be extended or hooked into?

Is there a preference for whether these uploads are added to a database table so they can be referenced/found if removed from the post? Are we okay with allowing orphaned media, or should it be deleted? Anything else you can think of?

If we can hammer out the requirements, I would be more than happy to make a PR and implement.

**Comment by TimohStudios** [comment]
[Fixed!] Craig is amazing. One of the most important changes to Anchor in a while.

**Comment by CraigChilds94** [comment]
Thanks @TimohStudios soon it'll be in a release, just need to test `0.9-dev`. It's thanks to this guy really: https://github.com/mazzo-/Anchorcms-0.9.2-drag-drop-fix
