### ISSUE TITLE
Feature: Page URL is removed from post URL when page is set to homepage

### ISSUE THREAD

**Issue by daviddarnes** [anchorcms/anchor-cms#788]
Anchor has a pretty sweet setup when it comes to setting the posts page. It cleverly takes whatever the posts page URL is and uses it in the single post url, thus meaning you can use it for other post types.

However, if the homepage is the same as the posts page the URL structure is still used. Ideally when for example 'Posts' is set as the posts page AND as the homepage the single post url shouldn't be ```website.com/posts/my-single-post``` it should be ```website.com/my-single-post```.

This addition would benefit users who are using Anchor for its core purpose, for blogging.

**Comment by CraigChilds94** [comment]
I personally feel that it should be `/posts` but we could supply an option to remove this. In which case there can be no 2 pages/posts with the same name and the user must resolve any problems.

**Comment by CraigChilds94** [comment]
http://feathub.com/anchorcms/anchor-cms/+15
