### ISSUE TITLE
My fault? Page 2 of categories 404 error

### ISSUE THREAD

**Issue by cmykaye** [anchorcms/anchor-cms#790]
When I try to access page 2 of categories through the back-end, I'm getting a 404 error. If I try and access the single category item here: http://helloarchie.blue/admin/categories/edit/3

I get this: 
![screen shot 2014-12-09 at 08 47 44](https://cloud.githubusercontent.com/assets/1450951/5354478/6a8738fe-7f80-11e4-9e6e-acd9a2d7b341.png)

Checked the edit.php against a newly downloaded version and nothing seems out of place?

**Comment by CraigChilds94** [comment]
Which version of Anchor are you using? have you tried the 0.9-dev branch? or even the latest tag

**Comment by TimohStudios** [comment]
I'm pretty sure this was recently fixed. I know for sure this doesn't occur in the most recent version.

**Comment by daviddarnes** [comment]
@CraigChilds94 can you confirm this has been fixed in the latest build?

**Comment by cmykaye** [comment]
This was using 0.9.2 so it may have been fixed.

**Comment by CraigChilds94** [comment]
@daviddarnes A pagination problem with the admin was fixed, I can't remember if it was on the categories page also. 

@cmykaye Please download the latest version of `0.9-dev` and have a check? Or download the latest tag?

Sorry I haven't had a chance to look at any issues lately. Going to try to free up some time over the coming months.

**Comment by daviddarnes** [comment]
@CraigChilds94 ok cool, appreciate you getting back to me :smiley:

**Comment by CraigChilds94** [comment]
@daviddarnes  @cmykaye Yeah this has been fixed. Sorry it took so long for me to check. If you get the latest pull of `0.9-dev` or hopefully the next tag after `0.9.3-b` then it should be working fine for you.
