### ISSUE TITLE
Parent / Child pages in menu

### ISSUE THREAD

**Issue by ChangePlaces** [anchorcms/anchor-cms#796]
Shouldn't pages that are children appear as children li elements in the menu? I can't find any links that would suggest a parent / child relationship at all anywhere, either in the admin or public side

**Comment by CraigChilds94** [comment]
I don't think this has been implemented to work like so; but don't quote me on this as I'm not 100% sure

**Comment by daltonsutton** [comment]
I'd like to see this if it has somewhere, I've looked in the forums, but found nothing.

**Comment by csengineer13** [comment]
@CraigChilds94, I believe that this has been implemented and can be seen in the *menu_render()* function found in /anchor/functions/menus.php

The default theme uses the *menu_items()* function in a while loop to create a flat list of all valid pages, but there is enough information to tweak its behavior to create a nested list (or simply use *menu_render()*)

**Comment by CraigChilds94** [comment]
Thanks for taking the time to look into this, I don't know where we're going from this though?

**Comment by csengineer13** [comment]
I don't think we need to go anywhere (:  (for now)

The default theme doesn't use *menu_render()*, it uses *menu_items()*; which is a perfectly acceptable implementation for a theme. So there are a couple of options:

* Change the default theme to use a menu that better represents parent/child structure
* Leave the menu as is, and note that menu_render() can be used in place of the current implementation to generate a nested structure

I have mixed feelings about both. If parent/child page relationships are important to the Anchor CMS team, then I think a decent amount of UI changes need to take place on both the front-end and back-end to make using tiered relationships more intuitive/less clunky.

Maybe worth a discussion, hammering out some desired end results, and setting a goal release for? But I don't necessarily think its something that should be a 0.9 focus.

**Comment by CraigChilds94** [comment]
I personally feel that this isn't a priority and is something that can easily be implemented when need be. We're probably looking at v1.0 for a refinement on this.

**Comment by overcatbe** [comment]
csengineer, thank you very much, that is just what i needed
