### ISSUE TITLE
How debug SQL?

### ISSUE THREAD

**Issue by luuckx2** [anchorcms/anchor-cms#802]
I'm trying to do similar to laravel because the class system / database.php is similar. But I did not succeed, if anyone can help me I'm grateful.

In laravel looked like this:
$queries = DB::getQueryLog();

**Comment by daviddarnes** [comment]
Could you ask such questions on the [Anchor CMS forums](http://forums.anchorcms.com/) please?

**Comment by luuckx2** [comment]
Ok, thanks

**Comment by luuckx2** [comment]
After register
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'banned' in 'field list' SQL: INSERT INTO `users` (`role`,`registered`,`username`,`email`,`password`,`reset_token`,`auth_token`,`banned`) VALUES(?,?,?,?,?,?,?,?) Params: "3", "2015-01-03 14:48:03", "luuckx2", "contato@humorceego.com", "$P$BaVXMqE2fkcsW.xa3fQ4GDFIIK3/4F0", "", "", "0"

**Comment by TimohStudios** [comment]
Sorry about that, it's fixed now!
