### ISSUE TITLE
Feature: description for site variables

### ISSUE THREAD

**Issue by james2doyle** [anchorcms/anchor-cms#804]
I'm working on a Anchor project that has a bunch of site variables in it. Since there is no **choice** option (checkbox, radio, select), it would be nice to have description fields so that I could add in instructions for when someone is modifying the site variable.

Custom fields already have a label, although having an extra field for extended description or help text, would be nice too.

Does anyone else see this as a viable addition? If yes, I can add it and create a new PR.

**Comment by rgdlee98** [comment]
I see it as a good addition. Have you started working on this already? If not I'd be happy to help.

**Comment by james2doyle** [comment]
I haven't started the work actually. No one responded so it seemed like no one was interested.

**Comment by daviddarnes** [comment]
I don't see any harm in adding it, far simpler addition than adding another field. Just a static string that can be added optionally yes? Just to be clear, are you adding these custom fields via the interface? How are you finding it? Do you prefer coding them in, aka coding fields into the functions file?

**Comment by gautiermichelin** [comment]
+1 that could be useful.

**Comment by james2doyle** [comment]
@daviddarnes I have always used the admin panel because of clients and their need to visualize.

In the first case, I would add an additional VARCHAR column to the `meta` table called description. It would only be used for site variables and not the site metadata.

The second option would be to add an additional table called something like `meta_descriptions`. It would have 2 fields, the `meta_key` and `description`.

Ideally the site variables could be re-written to allow more input types. Does anyone have an idea for that?

**Comment by daviddarnes** [comment]
@james2doyle I was just thinking about the idea of themes having the option to add custom fields in via their functions file, it would be easier than adding a theme and then going through the docs of it just to add custom fields.

**Comment by james2doyle** [comment]
Yeah I agree with that approach.

People on here know I'm a big fan of PyroCMS, they have a `theme.php` file in all their themes that creates fields based on an array. You can see [an example here](https://github.com/pyrocms/pyrocms/blob/2.2/develop/addons/shared_addons/themes/base/theme.php#L11).

It has some pretty awesome control in terms of allowing things like dropdowns and validation without any DB queries.

I actually have a 3rd approach. What if themes came with a migration? Then the migration could run based on what theme was installed. This would allow super control of the theme fields and validation.

**Comment by TimohStudios** [comment]
Related to #738

**Comment by CraigChilds94** [comment]
http://feathub.com/anchorcms/anchor-cms/+14
