### ISSUE TITLE
beta testing 1.0

### ISSUE THREAD

**Issue by severak** [anchorcms/anchor-cms#808]
It's possilble to beta-test 1.0 version for now?

**Comment by CraigChilds94** [comment]
I'd speak to @kieronwilson about this as I'm not sure on the state of the branch.

**Comment by CorstianBoerman** [comment]
As of the last test I did there is some problem with a database implementation and/or a config file related to this which prevents the system from doing anything.

**Comment by CraigChilds94** [comment]
Yeah last time I tried an install I didn't work; I think he was in the middle of something.

**Comment by Zegnat** [comment]
Do we have any new info on the beta?

**Comment by CraigChilds94** [comment]
Unfortunately not, I was hoping that Kieron was able to help with this? @rwarasaurus

**Comment by idiot** [comment]
Right now it's not stable or ready and requires PHP7

**Comment by CraigChilds94** [comment]
As this was more of a question than an issue, I'm closing this.
