### ISSUE TITLE
Domain name with cyrillic characters

### ISSUE THREAD

**Issue by isayev-ivan** [anchorcms/anchor-cms#809]
I have domain name with cyrillic characters.
Request to any page other than the main causes an 404 error. How to fix?

**Comment by CraigChilds94** [comment]
We haven't come across this yet. Unfortunately we're busy so it might take a while for us to get around to this. If you're able to fix it please let us know how you did it and if possible, make a pull request.

**Comment by TimohStudios** [comment]
@isayev-ivan Does the fix in the above PR fix your issue?

**Comment by CraigChilds94** [comment]
I guess we're waiting to find out?

**Comment by isayev-ivan** [comment]
Sorry for not having posted. Nope... the fix in #811 and #680 not fixed my issue :(((

**Comment by CraigChilds94** [comment]
@isayev-ivan That's a shame, we're having a big problem with this and we're looking to get it resolved. If you do however come up with a solution it'd be great if you were able to share it with us!

**Comment by TheBrenny** [comment]
@isayev-ivan, update to the latest version, and then test it out.

**Comment by tamr** [comment]
@isayev-ivan 
Replace this line https://github.com/anchorcms/anchor-cms/blob/master/anchor/helpers.php#L29 with:
$string = preg_replace("/[^\p{L}0-9]/u", "$separator", $string);

If you are using an old theme, also check for differences in search.php
