### ISSUE TITLE
Update post published date when actually publishing a post

### ISSUE THREAD

**Issue by vlribeiro** [anchorcms/anchor-cms#810]
Hi guys, I've been using Anchor for about a week now and I am not quite sure if this is by design or a bug, but whenever I create a new post draft and keep it as a draft, when i finally publish it the post date isn't updated to the actual time, it stays as the time i created it.

I gues i can see where this idea came from, but as soon as i have multiple drafts queued and i keep more than a day composing or adjusting images and all for some of the, the posts listing becomes very messy with recently published posts not on top.

I've been able to manually fix this by setting the post date in the database, i guess it is not complicated to update it when publishing also, but i still haven't got the time to look into it in the code. Has anyone had this same issue?

**Comment by daviddarnes** [comment]
Thanks for reporting this issue @vlribeiro, this bug has already been reported and is being worked on under #635. It's not great having to edit dates in the database so we understand why this is an issue for you.
