### ISSUE TITLE
Markdown parser working correctly?

### ISSUE THREAD

**Issue by MaxXor** [anchorcms/anchor-cms#818]
Hello,
I've added [highlight.js](https://highlightjs.org/) to my site but when I create a code block it treats the < and > from windows.h like a html element. I'm not sure if you can help me as this is just the github page of the cms.

`<pre><code class="c">#include <windows.h></code></pre>`

It just shows the "#include " because the rest gets treated as an html element even if it's in the code block, maybe there is a mistake in the markdown parser?

**Comment by MaxXor** [comment]
I fixed this by commenting this line: https://github.com/anchorcms/anchor-cms/blob/master/anchor/helpers.php#L45

And replacing the visible < and > by &lt; and &gt;

**Comment by daviddarnes** [comment]
@MaxXor glad you fixed the issue, if a little awkwardly. Anymore questions like this feel free to ask on http://forums.anchorcms.com/ :+1:
