### ISSUE TITLE
How can I add images to post?

### ISSUE THREAD

**Issue by sambuev** [anchorcms/anchor-cms#821]
Hello, I want to post images in the post, but without uploading them to the website. 

I want to use tag IMG-SRC, can I do it?

**Comment by danoxide** [comment]
Check this out: https://github.com/mazzo-/Anchorcms-0.9.2-drag-drop-fix

**Comment by sambuev** [comment]
didn't work, when I Drag and Drop, it shows me "Upload your file" and when I release file, nothing happens and post has no images.

P.S. but IMG-SCR tag works, so I can post images manually, but of course I would love to have Drag and Drop option working.

**Comment by danoxide** [comment]
Also you can add custom field.

**Comment by sambuev** [comment]
DragDropFix seems to have problem, I've uploaded it again on clean installation and I see it can upload images to content folder and put some markdown text to the post, but URL of the image is not correct:

This is what I see on broken image:
http://content/iphone.gif

where I can fix it? which file to replace?

**Comment by CraigChilds94** [comment]
Thanks for highlighting this, I knew it became a problem. I'm working on getting this fixed ASAP as it's pretty fundamental.

**Comment by CraigChilds94** [comment]
This has now been fixed in `0.9-dev` and will probably soon be included in a tag, thanks guys :)

**Comment by cdarlens** [comment]
Hi I'm using version 0.9.2. I'm not able to upload images in posts
