### ISSUE TITLE
Only 3 supported languages

### ISSUE THREAD

**Issue by raphaeljolivet** [anchorcms/anchor-cms#822]
Hi,

There are only 3 supported languages in the repo : 
https://github.com/anchorcms/anchor-cms/tree/master/anchor/language

It seem they have been move by this chanset :
https://github.com/anchorcms/anchor-cms/commit/4e3594ab833435d08bf0099d400f134be6b8ec6a

But I cannot find where.

**Comment by TimohStudios** [comment]
They are in their own repo: https://github.com/anchorcms/anchor-translations

**Comment by raphaeljolivet** [comment]
Ok thanks.
It should be updated on the doc then :
http://anchorcms.com/docs/getting-started/configuration
This is pointing to old URL.

**Comment by TimohStudios** [comment]
@daviddarnes ?

**Comment by daviddarnes** [comment]
@TimohStudios correct @raphaeljolivet this should be updated. However I don't have access to the main website as of yet.

**Comment by Sneffel** [comment]
+1

**Comment by TimohStudios** [comment]
@CraigChilds94 This issue still isn't resolved in my opinion, it just turned into a different kind of issue, as the docs still point to the wrong URL. I think it's important to get that fixed before you close this issue.

**Comment by CraigChilds94** [comment]
@TimohStudios it becomes an issue on a different repo
