### ISSUE TITLE
How to make 100 posts on one page?

### ISSUE THREAD

**Issue by sambuev** [anchorcms/anchor-cms#823]
Hello, I use Anchor CMS for quick notes and I need to see 100 posts on one page. 
Which file to modify to change the number? 

As you know in the web-admin settings there is interactive scroll-bar, but MAX number there is limiting to 13 posts...

**Comment by daviddarnes** [comment]
Hi, yes the scrollbar does have its limitations. You can edit the [posts.php file](https://github.com/anchorcms/anchor-cms/blob/master/themes/default/posts.php) and state posts per page using the [post loop options](http://anchorcms.com/docs/function-reference/posts).

Hope this helps!

**Comment by TimohStudios** [comment]
Or... Download the latest development version of Anchor. It has an option to set the posts per page to unlimited.

**Comment by daviddarnes** [comment]
@TimohStudios I think he already has an installation setup, so I'm assuming he'd rather make a small modification than update the entire install.

**Comment by TimohStudios** [comment]
Yesssss, true, but if that's too hard for him, there's a second option.

**Comment by sambuev** [comment]
yes I can't update entire site, I have my own modifications there, which string to edit to get 100 posts per page?

**Comment by sambuev** [comment]
<?php $bg = sprintf('background: hsl(215, 28%%, %d%%);', round(((++$i / posts_per_page()) * 20) + 20)); ?> 

is this?

**Comment by daviddarnes** [comment]
If you're struggling then yes it would be better to update.

I thought because you were posting on GitHub you were wanting to make code modifications, questions like these should be asked on the [official forum](http://forums.anchorcms.com/).

**Comment by sambuev** [comment]
which string to modify to have 100 posts per page?

**Comment by daviddarnes** [comment]
@sambuev apparently this seems to be the most effective way to change the number of posts, as posted by @TimohStudios back in september https://github.com/anchorcms/anchor-cms/issues/711#issuecomment-56548552

**Comment by sambuev** [comment]
yes changing number in DB works great. 
Thank you.
