### ISSUE TITLE
How to hide /posts from public? 

### ISSUE THREAD

**Issue by sambuev** [anchorcms/anchor-cms#824]
Hello, I have simple blog and I don't want users to see my website:

site.com/posts/ - make it visible only for admin, or hide it any different way. 
site.com/posts/posting-title - make it visible for everyone.

How can I do it?

**Comment by daviddarnes** [comment]
Could you please ask questions like these [on the forum](http://forums.anchorcms.com/), GitHub issues are designed to report bugs and issues with Anchor. Thanks.
