### ISSUE TITLE
Something is wrong with absolute path open_basedir

### ISSUE THREAD

**Issue by Sneffel** [anchorcms/anchor-cms#827]
![screenshot](http://i.snag.gy/BQMSM.jpg)

It looks like I can't open /.htaccess, maybe because my PHP is not in / but in /membri/lezip/...
I think it's my fault, but I would like how to solve it.

Thanks,
Sneffel.

**Comment by Sneffel** [comment]
Please tell me how to change the absolute ('/') path, because mine is not / but /membri/lezip

**Comment by daviddarnes** [comment]
There should be a ```url``` option in the following file:
```root > anchor > config > app.php```

You might have to change your .htaccess file too. Hope this helps.

**Comment by Sneffel** [comment]
hi, I changed the url option, but everything messed up.

the /membri/lezip/ path must be only be used for php code

eg
file_get_contents('/membri/pkspritesearch/image.jpg');
with PHP
<img src="/image.jpg" />
for HTML.

please, tell me how to change absolute path for PHP or how to deactivate error dumping
