### ISSUE TITLE
Is there a way to control which posts i want on my theme?

### ISSUE THREAD

**Issue by drFabio** [anchorcms/anchor-cms#833]
Hello , i don't know if this is the current channel to ask but i was wondering.
Is there a way to control which posts i show on my theme for example:
I want to have a page called X and on my home display all posts that are not  on category X.
Is there a right way to do it or i have to enter on the core code?

**Comment by NinjaSentry** [comment]
Hi drFabio. 

It would be great if you could ask your question on the forum, as GitHub issues are for reporting bugs and issues with Anchor. Thanks.

- http://forums.anchorcms.com/


this section is for reporting issues / problem related to Anchor cms

**Comment by CraigChilds94** [comment]
Thanks for replying correctly @NinjaSentry :+1:
