### ISSUE TITLE
How to write plugin

### ISSUE THREAD

**Issue by fawwaz** [anchorcms/anchor-cms#834]
I dont see any pages in anchorcmsthemes.com explaining on how to write custom plugin ? Then how to make it ?

**Comment by NinjaSentry** [comment]
Hi fawwaz

It would be great if you could ask your question on the Anchor support forums, as GitHub issues are for reporting bugs and issues with Anchor. Thanks.

- http://forums.anchorcms.com/

**Comment by daviddarnes** [comment]
We do have other issues relating to plugins, but they are related more to how we are going to implement it into Anchor. Ho to questions are better off [asked in the forum](http://forums.anchorcms.com/).
