### ISSUE TITLE
Feature: Custom types

### ISSUE THREAD

**Issue by TomS-** [anchorcms/anchor-cms#842]
Hello, I've just come across this project by chance. 

I'm looking to move away from Wordpress. I've thought about custom building my own CMS but this day in age, it seems pointless when there is plenty of open source projects you can get involved with. 

Firstly, I must say the design of Anchor is beautiful, the user interface is very clean. This is very refreshing to see. 

Also I love the idea of having a GUI custom post fields. I would love to see the same for custom post types allowing for complete flexibility. While I understand this needs to be lightweight, I would love to see a WYSIWYG editor. Simply to make it as user friendly as possible, such as (http://imperavi.com/redactor/).

Concrete5 does this very well.

**Comment by jessycormier** [comment]
One of the points of the project I think is to keep it very clean and simple, adding a WYSIWYG will go against that unless you mean to add a format bar something like stackedit.io has :smile:  that would be awesome.

it uses Markdown as the style editor just like github. 
For more information http://commonmark.org

Maybe writing a plugin will let you replace parts of the system like your suggesting however.

**Comment by CraigChilds94** [comment]
Thanks for your feedback, we all appreciate it and we're happy for the community to get stuck in! I too work with Wordpress and I'm very tired of it If I'm honest, its super bloated and incredibly slow! The only thing it has going for it is that non-techy's recognise it and understand how it works.

But yes @jessycormier is correct, we don't want to add too much to this project! Clean and simple is how we want it to be by default. There's been a lot of talks about plugins for a long time and version `1.0` should support them. In this case it'd be great if it were possible to customise and swap out the back end components of the CMS such as the editor when required, I personally thinks that's what makes a CMS truly useful; being able to tailor it to yours and your clients/projects requirements.

We want to make using Anchor a great experience, feel free to get stuck in and help us out!

**Comment by CraigChilds94** [comment]
This is most likely going to be a plugin in 1.0 and currently not a concern for the current release.
