### ISSUE TITLE
Feature: Live preview of markdown formatting in editor

### ISSUE THREAD

**Issue by Radiergummi** [anchorcms/anchor-cms#843]
Currently, you have to format blindly using markdown - which isn't hard once you know the few rules.  
Nevertheless, it would be nice to have some inline preview of the formatting, as seen on [Stackedit](https://stackedit.io/editor): The editor text keeps its formatting characters but is rendered with the respective formatting options, like so:  

![Screenshot of Stackedits interface](https://cloud.githubusercontent.com/assets/6115429/7219656/a8b153c6-e6aa-11e4-96fe-5c29f7a8c683.png)

**Comment by CraigChilds94** [comment]
I think we have a previewing system in version `1.0` @rwarasaurus  correct me if I'm wrong? and I believe it's a side-by-side preview, which in my opinion is much easier to use.

**Comment by Radiergummi** [comment]
Aw, that's a pitty. I worked with both concepts for a while now and think
the inline preview is much better suited for writing longer texts, so you
don't have to look left and right and back again. Aside of that, how would
you build an editor that works for phone screens as well? Side-by-side
isn't possible, so you'd have to place it below or above.. Oh well.
Anyway, better a preview than none at all. Thank you for the response
anyway :)

2015-04-24 12:59 GMT+02:00 Craig Childs <notifications@github.com>:

**Comment by CraigChilds94** [comment]
Ah you make some good points. hmmmm I think we'll have to consult the others. I'm not involved in the design much so I guess it really isn't my topic :P

**Comment by daviddarnes** [comment]
Whispers: _Plugin?_

**Comment by Radiergummi** [comment]
@daviddarnes : Coming soon, yo! :smile:

**Comment by daviddarnes** [comment]
Side by side preview that can be toggled sounds best, and I guess will be in the core. As for this 'mixed' preview I don't think there's any harm it being a plugin, thoughts people?

**Comment by CraigChilds94** [comment]
Side by side is good but it's a big job. I'll see what can be done but it's looking like we might have to leave changes to the editor until 1.0 comes out.

**Comment by TheBrenny** [comment]
I assume if we had an in-editor markdown preview, it wouldn't render instantly? Maybe rerender every 10-15 seconds?

**Comment by daviddarnes** [comment]
What does the writing space look like in v1.0? Is there a preview?

**Comment by TheBrenny** [comment]
@daviddarnes, I'm not running 1.0, but in 0.10 (or 0.9-dev as it's known by the branch name) the POST route is there, but I don't think anything calls it.....

**Comment by Radiergummi** [comment]
@TheBrenny take a look at stackedit, as they manage do it instantly without a noticeable performance loss. I like the text flow there.

**Comment by TheBrenny** [comment]
It's a great little tool - I've used it many times. But I just can't see how they've implemented it. I've tried to even Inspect Element that and trace everything back, and I've even gone through their github repo, but finding out how it works, yeah that's a whole mission and a half.

**Comment by TimohStudios** [comment]
I think they basically wrote their own Markdown parser in Javascript, but I might be wrong. Like, in a way it checks for special characters at the start of words as soon as they're typed, that kind of stuff.

**Comment by TimohStudios** [comment]
If we know where we're going with this I'm willing to build it

**Comment by daviddarnes** [comment]
Do we run into inconsistency issues if we're storing markdown and HTML in the DB, and then using JS to parse the markdown live? I guess it's the best way for previewing but we'd need to make sure PHP and JS parsing the markdown in the same way :s

**Comment by TheBrenny** [comment]
@daviddarnes, we could make a file that's setup like a `key:value` pair where the `key` is a markdown value, and the `value` is the HTML tag equivalent.

**Comment by Radiergummi** [comment]
@TheBrenny @daviddarnes If I may throw in some thoughts -  Markdown is usually not nested so deeply, so listening for markdown delimiters and parsing text on paste should be possible. Inconsitency should not occur when using standard markdown libs (for example Parsedown for PHP and js-markdown for JS).

**Comment by TheBrenny** [comment]
@Radiergummi, 1) that's very true. It shouldn't produce speed issues - I'm just concerned about keeping anchor as small as possible.
2) but you'll notice that stackedit has more tags... It shouldn't be too hard to import the `key:value` pairs upon opening and what not. This will also allow anyone to add their own tags. Or even PR a whole bunch of tags that are necessary.

**Comment by Radiergummi** [comment]
@TheBrenny Well, I don't know about the others, but some way of previewing the rendered markdown would be disirable, at least for me, so *some* kind of addition is due anyway.  
There are three possiblities: Side-by-side, separate container (as here on Github) or live preview. The last one is the most sexy option - it requires no effort, even people new to markdown get it quickly, it works well on small screens and it has that kind of elegance I love about AnchorCMS.

**Comment by TheBrenny** [comment]
@Radiergummi 
- Side-by-side being something like stackedit's side-by-side? - Seems easiest, but hurts the size* constraints of anchor (* size as in width and hight). However this can be achieved as a vertical side-by-side as on StackExchange?
- Separate container being like switching tabs? - This seems the most anchor-like feature to implement, and shouldn't be too hard to implement.
- Live Preview as in stackedit's editor? - Unless you can find the editor file, I feel that I wouldn't be able to accomplish this.

**Comment by k4kfh** [comment]
I didn't have time to read the whole thread, so forgive me if I missed something, but I think [SimpleMDE](https://nextstepwebs.github.io/simplemde-markdown-editor/) is an excellent tool for this job. It would barely require any changing on the backend (just add a class to the textarea and a couple lines of JavaScript on page load). I like the inline editor as opposed to a side-by-side or tabs-based editor like on GitHub or another site.

**Comment by k4kfh** [comment]
### Update: I can confirm this editor works very well.

I don't know enough about PHP or Anchor's inner workings to just fork it and add it myself, but I can tell you guys what I did to my Anchor install and I'm sure you can make it happen.

Here are some images/captures of the editor in action on my Anchor install. This is slightly out of date (it's missing a few of the features present in the version in the GitHub repo, which is why I didn't just fork it and immediately make a pull request) but from looking at the new install it would be pretty easy to make the necessary changes.

![](http://i.imgur.com/73CliAV.png)

![](http://i.imgur.com/6BZNyYR.png)

![](http://i.imgur.com/R4eUfrY.png)

![](http://i.imgur.com/l1B2kfc.png)

**Comment by CraigChilds94** [comment]
http://feathub.com/anchorcms/anchor-cms/+13
