### ISSUE TITLE
Deleting a page that is assigned as Home Page makes the CMS unusable

### ISSUE THREAD

**Issue by sidrun** [anchorcms/anchor-cms#847]
I deleted a page (the default posts page) that was assigned as Home Page and after that I could not use the admin nor the page itself anymore because of:

```
Uncaught Exception

Trying to get property of non-object

Origin

anchor/views/partials/header.php on line 47

Trace

#0 path/anchor/anchor/views/partials/header.php(47): System\Error::native(8, 'Trying to get p...', 'path/pub...', 47, Array)
#1 path/anchor/system/view.php(87): require('path/pub...')
#2 path/anchor/system/view.php(72): System\View->render()
#3 path/anchor/anchor/routes/pages.php(21): System\View->partial('header', 'partials/header')
#4 [internal function]: {closure}()
#5 path/anchor/system/route.php(152): call_user_func_array(Object(Closure), Array)
#6 path/anchor/system/router.php(152): System\Route->run()
#7 path/anchor/system/start.php(36): System\Router->dispatch()
#8 path/anchor/index.php(33): require('path/pub...')
#9 {main}
```

As it says, the problem is in anchor/views/partials/header.php line 47
```
<?php echo Html::link($home->slug, __('global.visit_your_site'), array('class' => 'btn', 'target' => '_blank')); ?>
```

I was able to comment out that line and then access the admin and then set another page as a Home Page, but that was just a temporary fix. 
A solution would to be to restrict deleting a page, when it is set as Home Page.

**Comment by daviddarnes** [comment]
I've encountered the same issue. While it's an understandably non-major issue (you probably shouldn't delete the home page) there should still be an indicator of what you're trying to do or just remove the delete option when it's set.

**Comment by CraigChilds94** [comment]
In the latest version, or at least the `0.9-dev` branch you won't be able to delete the home page.
