### ISSUE TITLE
Bug: Letter "p" removed  or case changed from end of file name during image upload

### ISSUE THREAD

**Issue by pdxvr** [anchorcms/anchor-cms#848]
Sorry if this is a known issue, but it's hard to figure out what to search for when looking for this issue.  Version 0.9.2
Pretty generic installation

Added a number of custom fields to upload images, in each field the lowercase letter "p" is removed from the file name as it's uploaded.  In the database the file name remains correct, but in the /content folder the letter is missing from the file name.  Anchor does however render the image, it 'knows' the file name is missing the "p" even though the database contains the p in the file name.

Capital "P" gets changed to lowercase "p" during upload

**Comment by CraigChilds94** [comment]
We'll examine this further, but have you tried downloading the development branch and seeing if this issue still occurs? It could've been related to something else and fixed a while back.

[Download 0.9-dev.zip Here](https://github.com/anchorcms/anchor-cms/archive/0.9-dev.zip)

**Comment by pdxvr** [comment]
I downloaded from the link you posted and it does the same thing.  I also noticed that it changes file names to lowercase which I don't think is an problem, however I'm not sure it's intended or wanted to work that way.

**Comment by CraigChilds94** [comment]
Hmm, thanks for letting us know. I will look into this for you :)

**Comment by TheBrenny** [comment]
@pdxvr, does this problem still occur? Can you provide images?

**Comment by pdxvr** [comment]
@TheBrenny, is there some reason to believe it has been fixed?

**Comment by TheBrenny** [comment]
There is no reason, but if you update to the latest merging and retest, it could be that a file edited in one of the latest PRs accidentally fixed this bug.

And the pictures: I have no pictures to upload to my website, and I don't want to set up another anchor installation, so it's easier if I can just see what's wrong.

**Comment by pdxvr** [comment]
I cannot get my uploads to work at the moment with the new updates, so I can't tell you if this bug still exists.

**Comment by pdxvr** [comment]
I also notice that it removes the letter "g" when it's the last character of a file name (not including extension)

**Comment by CraigChilds94** [comment]
Not getting this anymore :/
