### ISSUE TITLE
Proposal: JSON API

### ISSUE THREAD

**Issue by Radiergummi** [anchorcms/anchor-cms#853]
Okay, now this is a little bit of madness :smile:
I use PJAX to fetch my content, which has made the site much smoother but causes multiple side effects, like the entire `<head>` element not being updated, CSS separating problems, and so on. So I thought, would it be possible to have an Anchor API that returns JSON data?
Like, if you request `http://anchorcms.com/api/slug` instead of `http://anchorcms.com/slug`, it'd not parse a view but rather return all the relevant variable content defined for this route as JSON for easy use with client-side scripts.

I know this sounds contraproductive to "lightweight and simple" at first, but that approach would provide many possibilities without interfering with existing architecture.

Remarks?

**Comment by CraigChilds94** [comment]
Something like that would be cool, it wouldn't add much either. We'd just need to handle it correctly via the routes.

I think something like `/slug-here?json=true` would be easier and cleaner to implement. As we're not looking at adding a REST api, so the term `api` doesn't really fit in.

Or we could do it conventionally and require you to specify the type data you want to be returned in the response via some request headers, we'll check for them and try to return the correct type. Then we could make it flexible and allow for multiple document types like `xml, json, html, text` etc...

What are your thoughts? @Radiergummi I personally feel like this is a bit crazy for the current version and should be considered for `v1.0`, @rwarasaurus @daviddarnes @idiot What are your thoughts also?

**Comment by Radiergummi** [comment]
Well, I just used `/api/` because I work a lot with REST and am used to it, but you're right, your approach is better... That being, if Anchor won't implement an API in the future (which would also enable executing template functions on the client side - I don't need it, but there's gotta be a reason for the Angular/Backbone/Ember guys :smile:). And yep, definitely `v1.0`.

**Comment by rwarasaurus** [comment]
The plugin framework for 1.0 will allow you to build your own api, you will be able to manipulate the application routes adding your own /api/whatever and output json, xml etc.

**Comment by CraigChilds94** [comment]
I think this is quite a big feature and should be left for 1.0 and the plugins. I think at that stage it will be more useful. Though you're welcome to implement such a system to the current one yourself if you'd like! it'd be great to see what you come up with!
