### ISSUE TITLE
Branches and Git Workflow

### ISSUE THREAD

**Issue by CraigChilds94** [anchorcms/anchor-cms#856]
Hey everyone, I've adjusted the branch naming accordingly. We're not really working on a `0.9` version of this CMS anymore; too many things have been added and fixed and we need to continue with correct versioning. So from now on, any work should be made on ~~`0.10-dev`~~.

This may cause some issues for you all and if you could please resubmit any PR's that you made to `0.9-dev` that would be great!

Sorry for any inconvenience, I'm trying to tidy things up. 

I'll add some update documentation in due course, which will hopefully clear some things up and make it easier for everyone to get involved.

__EDIT:__

Work has resumed on `0.9-dev` so don't worry about changing anything.

**Comment by daviddarnes** [comment]
So we're on 0.10 not 0.1 right? Will we continue with this sub-versioning until we're happy with the product to be able to go to v1.0?

**Comment by Radiergummi** [comment]
I find the development process a bit complicated, to be honest. So
@rwarasaurus is working on v1.0 completely on his own, right? All public
work/contribution is going into soon-obsolete <v1.0, because the
architecture will change a lot (I stumbled over Ship accidentially)....

2015-05-06 16:24 GMT+02:00 David Darnes <notifications@github.com>:

**Comment by CraigChilds94** [comment]
@daviddarnes it's 0.10 because I think we should start following http://semver.org/ `major.minor.patch`, this will come into full effect when 1.0 is released. 

The development process has changed quite a lot. It's hard to coordinate between everyone, but 1.0 is still correct in being a non-backwards compatible change. We will ensure that the communities contributions aren't wasted; in fact they've helped us grow and build this CMS. All of that will be taken into account with v1.0. And with the support for plugins, who says this will stop?!?!

Like I've said, I will write full docs on all of this; even with some guideline `git` commands to follow; anything that does not follow this document will not be merged in.

**Comment by daviddarnes** [comment]
@CraigChilds94 thanks Craig, I think I understand it a bit more now. I think the 0.9 to 0.10 is just caught me out.

**Comment by CraigChilds94** [comment]
@daviddarnes That's okay; theoretically we could have `v*.*.*` where `*` is any number. And relevant changes increment the relevant value by 1.

This will be documented anyway :)

**Comment by rwarasaurus** [comment]
@Radiergummi it won't be obsolete, there are still a lot of people using 0.9

**Comment by CraigChilds94** [comment]
@rwarasaurus  is right, the 0.* version of Anchor is independent to 1.*

**Comment by Radiergummi** [comment]
@CraigChilds94 May I ask if migration of data and/or themes will still be possible? And besides, any ETA on v1.0?

**Comment by daviddarnes** [comment]
I think data migration will be in there, be silly not to. Theme migration would be nice, but I tried a random theme on v1.0 dev and it kinda worked but kinda didn't :worried:

**Comment by CraigChilds94** [comment]
@daviddarnes  it'll just be a case of adding backwards compatible API functions, but this is dependent on whether or not the functionality provided is the same.

ETA on 1.0 is best served by @rwarasaurus

**Comment by CraigChilds94** [comment]
Because things went a bit messed up I've reverted back to `0.9-dev` for the current development branch. It's a shame we're in too deep to follow `semver` but once `1.0` is out we can follow it completely!

I would like your opinion guys? I think keep branch same but tag correctly? so next tag is `0.10` like it should probably be... or `0.9.4` or something like that? @daviddarnes @rwarasaurus @idiot  I just want something that we can stick to and that makes sense; without messing things up.

**Comment by TheBrenny** [comment]
I think it depends on what all of the branches are. I would send all my PRs to the master branch, but it seems that I am incorrect for doing so?

I think having two separate branches that are trying to achieve the same gaol (from what I see) is a bit silly. Having one branch per * in version labels seems reasonable:

Major: when a stable build of the cms can be used and pushed as an upgrade.
Minor: where a new feature has been tried and tested, merged from an unofficial branch which has been created by a contributer.
Patch: obviously for bug fixes and the likes.

If anchor ends up adopting this versioning system, I guess we should start calling it the big 1.0.0! :P

**Comment by CraigChilds94** [comment]
@TheBrenny The master branch is ideally for release versions only which is why any development/PR activity can be found on the `dev`  branches... I'm not sure what the status on 1.0 is but I'm getting pretty excited xD

**Comment by TheBrenny** [comment]
I'm keen as well! :D

But I'm confused as to why we have a 1.0-Dev and 0.9-Dev though. Where should I send my PRs to? :P

**Comment by CraigChilds94** [comment]
1.0-Dev is an old branch and is really only there for @rwarasaurus. I need to update the guidelines to make it clearer that `0.9-dev` is where to work on, though it does make sense as it's currently 0.9.3.* and 1.0 hasn't been released yet.

**Comment by CraigChilds94** [comment]
I've updated the `contributing.md` file with some clearer details
