### ISSUE TITLE
Bug: Random page movement when Ctrl or shift is pressed whilst writing a post or page

### ISSUE THREAD

**Issue by DavidSouthgate** [anchorcms/anchor-cms#858]
Whenever writing a blog post or a page, shift or control causes random page movement which is incredibly annoying

**Comment by daviddarnes** [comment]
I have never seen this issue. Can you present this in a gif?

**Comment by DavidSouthgate** [comment]
Now that i disgnose it a little more it's not random but jumps to the top every time shift or control are pressed.

Running Firefox 38 on Windows 8.1 not present in chrome 42

![bug5](https://cloud.githubusercontent.com/assets/6199657/7633429/cd590282-fa4b-11e4-854d-b33244005366.gif)

**Comment by daviddarnes** [comment]
Thank you for the gif, it's a really good way to present visual bugs. It does sound like a Firefox only issue, maybe something that can be averted with js?

**Comment by CraigChilds94** [comment]
This seems really weird, I've never encountered such an issue. If anyone come up with a fix, I'll be happy to add it in.

**Comment by Sneffel** [comment]
Yeah, it also happened to me.

**Comment by CraigChilds94** [comment]
As no one else has suggested this as an issue i'm closing this. I'm unable to replicate it myself.
