### ISSUE TITLE
How to stop error reporting

### ISSUE THREAD

**Issue by Sneffel** [anchorcms/anchor-cms#860]
how to stop errors to be reported at the end of every page?
please tell

thanks!

**Comment by CraigChilds94** [comment]
You can add `error_reporting(0)` to the project, but Anchor likes to use Environments to configure the error_reporting level.

I hope this answers your problem. Though it'd be great if you could give us a screenshot or paste in the error messages so we can examine further!?

**Comment by Sneffel** [comment]
Hello, and thank you very much for answering my question.
Now, please, could you kindly help me telling me where do I have to set that on my web space; I really wouldn't know where I'd have to start.

**Comment by daviddarnes** [comment]
@Sneffel that's not really the best thing to do, as @CraigChilds94 said you're meant to turn off error reporting in your environment and not the application. I'm guessing it might be a PHP version error.

Also if you have queries like this then please [use the official forum](http://forums.anchorcms.com/).

**Comment by daviddarnes** [comment]
@Sneffel I've noticed you've asked this same question in #827, #828 and in this issue (#860). Please stop spamming GitHub issues for such queries. This is what [the official forum](http://forums.anchorcms.com/) is for. You have already [created a thread](http://forums.anchorcms.com/help/just-a-few-questions-favicon-error-display) that has plenty of activity to help your problem. Consider this as your second warning ([first warning](http://forums.anchorcms.com/help/just-a-few-questions-favicon-error-display#post-6046)).

**Comment by Sneffel** [comment]
HEY! I don't care about your warnings.
Nobody answered me so I just opened a new query.

Now everything is fine so why should I open something new now?

**Comment by Cam** [comment]
@Sneffel Dude, not cool. This is an open source community. If you want a commercial product, giving you the right to act like a ****, go elsewhere.

**Comment by daviddarnes** [comment]
@Sneffel you have had multiple responses on both GitHub and the forums. Plenty of suggestions have been made, and I have personally responded to all issues you have raised on GitHub.

I'm glad you have resolved your problem.
