### ISSUE TITLE
How can I loop posts in article template?

### ISSUE THREAD

**Issue by JustCruize** [anchorcms/anchor-cms#862]
I want to loop my recent posts in all my article template so when users view an article on my website they can see a list of recent posts within the article page without having to go to the posts page.

I tried to place the while loop within the article.php file but nothing gets outputted.

How could I do this?

**Comment by CraigChilds94** [comment]
This is more of a question rather than an issue, would you mind posting it on the forums?

http://anchorcms.com/forum
