### ISSUE TITLE
Feature: Allow choice for drafts and archived articles in article pagination

### ISSUE THREAD

**Issue by TheBrenny** [anchorcms/anchor-cms#863]
The default functionality is that all archived posts show up in the article pagination, which can be annoying considering that if an article is archived between two non-archived articles. This can lead to a spaghetti-like website in terms of articles...

Reproduction:
 1. Create a new post
 2. Make it archived
 3. Go to the post previous to the newest
 4. Using article pagination, navigate to the new archived post.

Working on the feature and pushing shortly.

**Comment by daviddarnes** [comment]
So essentially you want the ability to filter between post states within the admin interface? 'Show all archived' or 'Show all drafts' yes?

**Comment by TheBrenny** [comment]
Negative. Not on the admin interface. When you call the article adjacent function, the ability to include drafts or archived articles should be optional, rather than forced the pagination of archived articles.

**Comment by daviddarnes** [comment]
Ah I see now, sorry. Yes this seems like a bug rather than a feature, archived and draft posts shouldn't be accessible like this (well by default at least).

So by default article pagination won't provide access to draft or archived posts, unless the developer opts in with a function option? :+1: 

Thanks for this contribution ( don't forget to reference this issue in your PR, #863)

**Comment by TheBrenny** [comment]
By default, only archived can be seen, however, it seems only reasonable to allow the developer more control.

Correct. With more control over what the developer can show, comes more control over the blog.

Where should I mention this? :') this is my first contribution to anything, so I don't quite understand the masses of everything on GitHub.

**Comment by daviddarnes** [comment]
@thebrenny when making a pull request, in the content text box you can mention issues simply by typing # and then the issue number. The issue number is next to the title of this issue, in this case it's #863. You can mention it in pull request comments or even commit messages, that way changes can be tracked with issues. Hope this explains things better.
