### ISSUE TITLE
Feature: Make pages as well as posts searchable

### ISSUE THREAD

**Issue by TheBrenny** [anchorcms/anchor-cms#866]
So I saw this in the Readme.md and thought I'd help out and give it a crack. There will be a new PR shortly....

But, for the description:
This added feature will enable posts to be searchable as well as pages, with the option of including both types, or exclusively only one type.

I clearly want this hitting 1.0.0! :stuck_out_tongue_winking_eye:

**Comment by daviddarnes** [comment]
Ace! I'm guessing this needs to be submitted to 0.9-dev, right @CraigChilds94?

**Comment by TheBrenny** [comment]
I think I PRed this to 0.9-Dev? :P

**Comment by daviddarnes** [comment]
@TheBrenny PR #867 seems to be going into master?

**Comment by TheBrenny** [comment]
Well... This is embarrassing. I think I might just go fix that up...

**Comment by daviddarnes** [comment]
@TheBrenny no embarrassment required, you're making an effort to contribute and that's all that matters :+1:

**Comment by TheBrenny** [comment]
Anything I see, I will fix. :smiley:
