### ISSUE TITLE
Author rights management

### ISSUE THREAD

**Issue by digitalesherz** [anchorcms/anchor-cms#869]
I'd like to use the author rights to really fix access of every function in the Admin-area.
Is it going to be implemented? At the moment there are only some checkboxes in the User-management-page?

**Comment by CraigChilds94** [comment]
This is something we're planning on doing, hopefully before `1.0` as we know a lot of people want a roles system, but it's quite a big feature to implement and will most likely be put after bugs.

**Comment by CraigChilds94** [comment]
Closing this one as the referenced Issue provides more detailed information.
