### ISSUE TITLE
Bug: Normal users can edit the webiste

### ISSUE THREAD

**Issue by TheBrenny** [anchorcms/anchor-cms#873]
Reproduce: Create a user in the admin panel with the role of 'User' and re-login with the created credentials. Whilst logged in, edit posts and observe the effects.

I would implement a fix for this, but I don't know the default user-level-access that should be implemented. If I were to implement this, however, I would redirect them to a `[specific page]` based on the role that the user is, ie:

- Admin -> `[Posts]` (unfiltered), and all other pages
- Editor -> `[Posts]` (filtering all posts that have different authors), and no other pages
- User -> `[401 Access Denied]`

Although this is a separate issue, I feel that this falls under the same category as a Roles System (mentioned not too long ago (#869))

**Comment by vanzhu** [comment]
has this bug been fixed?

**Comment by daviddarnes** [comment]
I feel as though this issue should be a perfect example of how to report bugs. Gold star to @TheBrenny :star:.

**Comment by TheBrenny** [comment]
Amend the contributing.md file? :stuck_out_tongue_winking_eye:

But no @vanzhu, this is still an issue. I've spoken to @CraigChilds94 about this briefly, and I understood that the intent was to allow the admin to make certain posts private to only users, so unregistered guests are unable to view them. However, to start off with, it wouldn't be a bad idea to at least redirect certain accounts based on their permissions?

**Comment by rwarasaurus** [comment]
The user roles have not been implemented yet, the fix for now should be removing the feature of creating users with any specific role so the admin knows they can only create admin users.

**Comment by TheBrenny** [comment]
@rawrasaurus, removing functionality? I admit, its something that we don't want admins to do, but we could add a `Notification` instead to notify that there is a user account and that this bug exists.

**Comment by CraigChilds94** [comment]
@TheBrenny @rwarasaurus I'm going to try to implement something using these roles. Even if it is really basic.

**Comment by CraigChilds94** [comment]
@TheBrenny As this isn't really a "Bug" I'll close this. I'm going to look into something we can use to handle admin users.
