### ISSUE TITLE
Offline cache

### ISSUE THREAD

**Issue by datasmurfen** [anchorcms/anchor-cms#877]
Hello, I want the content to be available offline. 
Am using this theme: https://anchorthemes.com/theme/iwrite

I have created a manifest file, and in the pages added the nessasary html code.
But it still dosn't work.  Maybe someone could help please.

**Comment by daviddarnes** [comment]
Hi @datasmurfen, questions like this should be asked on the [official forum](http://forums.anchorcms.com/).
