### ISSUE TITLE
Feature: Ability to re-order posts & pages

### ISSUE THREAD

**Issue by Lewitje** [anchorcms/anchor-cms#878]
I think it would be really useful to be able to re-order posts and pages.
Especially pages, because they show up in the navigation.

**Comment by TheBrenny** [comment]
Reordering pages is possible thanks to the 0.9-Dev branch. Download that and install it and give it a crack.

But as far as posts go, I've been thinking the same... What sort of order did you have in mind?

Devs: maybe an advanced section where people can insert custom SQL in the where and sort by clauses?

**Comment by Lewitje** [comment]
Thanks, I should have looked there first.

Although I don't want to run a development branch on my project, so i'll wait till it's been merged with the master.

I was thinking a sort by / latest first function too, but I thought a page sorting function was a big missing feature.

**Comment by TheBrenny** [comment]
The Dev branch works perfectly fine! :P I squashed the big ugly bugs in my general fixes PR. So give it a shot - however it will require a reinstall of anchor... :/

Posts are also sorted to be the latest is first by default, and that's unchangeable unless you alter the where clause in the `site.php` or the `posts.php` (I forgot which one! :P )

**Comment by TimohStudios** [comment]
No reinstall should be required! Of course it's fine to not run on the dev branch, there can be major bugs in there, even in the dev releases. I believe it's posts.php by the way.

**Comment by TheBrenny** [comment]
Hmm.. That's strange... I had to reinstall... But I think I screwed up changing versions somewhere...

I just had to change some of the SQL in the install directory (commenting the create tables), but that was it, everything was fine and dandy.

Cheers!
