### ISSUE TITLE
Bugfix: Result isn't a variable...

### ISSUE THREAD

**Issue by TheBrenny** [anchorcms/anchor-cms#885]
Bug:
> Undefined variable: result
> The error has been logged in /anchor/errors.log
>
> **Uncaught Exception**
> Undefined variable: result
> 
> **Origin**
> anchor/libraries/update.php on line 61
> 
> **Trace**
> 0) /home/ubuntu/workspace/anchor/libraries/update.php(61): System\Error::native(8, 'Undefined varia...', '/home/ubuntu/wo...', 61, Array)
> 1) /home/ubuntu/workspace/anchor/libraries/update.php(14): Update::touch()
> 2) /home/ubuntu/workspace/anchor/libraries/update.php(6): Update::setup()
> 3) /home/ubuntu/workspace/anchor/routes/admin.php(62): Update::version()
> 4) [internal function]: {closure}()
> 5) /home/ubuntu/workspace/system/route.php(152): call_user_func_array(Object(Closure), Array)
> 6) /home/ubuntu/workspace/system/router.php(152): System\Route->run()
> 7) /home/ubuntu/workspace/system/start.php(36): System\Router->dispatch()
> 8) /home/ubuntu/workspace/index.php(33): require('/home/ubuntu/wo...')
> 9) {main}

(Note: Trace's numbering is not a bug, just preventing issue references...)

As for reproducibility, I'm doubtful of it; I think this was just a one off. But with a clean install of anchor-cms/0.9-dev, I went to the admin panel, logged in, and bam! I was hit with that exact log.

Expect a PR in about a few seconds! :smile:

**Comment by Lewitje** [comment]
Getting the same problem with a clean install of dev 0.9:

Undefined variable: result
The error has been logged in /anchor/errors.log
Uncaught Exception

Undefined variable: result

Origin

anchor/libraries/update.php on line 61

Trace

#0 /.../anchor/libraries/update.php(61): System\Error::native(8, 'Undefined varia...', '/Users/.../Des...', 61, Array)
#1 /.../anchor/libraries/update.php(14): Update::touch()
#2 /.../anchor/libraries/update.php(6): Update::setup()
#3 /U.../anchor/routes/admin.php(62): Update::version()
#4 [internal function]: {closure}()
#5 /.../system/route.php(152): call_user_func_array(Object(Closure), Array)
#6 /.../system/router.php(152): System\Route->run()
#7 /.../system/start.php(36): System\Router->dispatch()
#8 /.../index.php(33): require('/Users/.../Des...')
#9 {main}
