### ISSUE TITLE
Different anchor version on the website

### ISSUE THREAD

**Issue by giacomocerquone** [anchorcms/anchor-cms#891]
I noticed in relation to the previous problem https://github.com/anchorcms/anchor-cms/issues/889 that the anchor cms that is downloadable on the site: http://anchorcms.com/ it's a different version where blockquote isn't even styled. Please provide an updated version on the site.

**Comment by TheBrenny** [comment]
@giacomocerquone We are aware of this sort of issue. As the devs are working on 1.0, I can't see this being fixed until 1.0 pops. Just be patient, or if you want to snag the latest, your best bet would be to grab the 0.9-dev. I'm working on some of the open issues to help out, so I can try get 0.9-dev stable and pushed to master.

@CraigChilds94 A lot of issues are opening up about the outdated version on the website. Maybe point that link the the zip from the GitHub master

**Comment by fbrinker** [comment]
Yep you should point the download link to the [github-master zip download](https://github.com/anchorcms/anchor-cms/archive/master.zip)...

I've tested a few cms and also this one. But i couldn't create pages or even upload images... so i threw the test installation away... but at the end, i liked this lightweight cms more than drupal and the other big ones and took a look into the code... after installing the master, the image uploads worked and i only had to fix the page-creation mysql-error :)

So you may want to merge some PRs, too

**Comment by CraigChilds94** [comment]
@fbrinker Hopefully some of your issues have been fixed. I know for certain `pre-1.0-develop` contains some of those fixes and will hopefully be realising a new version soon. We've recently release `0.11` and updated our website. Again we need to have another work on that to get things sorted out.
