### ISSUE TITLE
Timezones issues.

### ISSUE THREAD

**Issue by giacomocerquone** [anchorcms/anchor-cms#893]
I saw other old issues like this in this section. During the installation the timezone for italy and also for other countries is completely wrong (I think that every country has a wrong timezone at this point). For example in the installation italy it's GMT +2 (the correct GMT is +1), London GMT +1 (the correct GMT is 0). It doesn't seem that has been corrected on the other branches. I tested for a while the timezones function and it seems that makes a mess when is executed, infact the DateTimeZone::listIdentifiers() function of php is ok.
I'll try to fix it as soon as I can.

**Comment by TheBrenny** [comment]
I thought this was wrong. My timezone is +0830 but anchor said it was +0930. I thought I was stupid, but this gives me great relief! :wink:

**Comment by giacomocerquone** [comment]
YES I DID IT, at least I think! I deployed my code on my anchor installation and it worked. I'm doing a PR to the master and 0.9 branches.

**Comment by alexbagirov** [comment]
Time to close this issue? It seems to be fixed.

**Comment by idiot** [comment]
okey doke
