### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by paragonie-scott** [anchorcms/anchor-cms#902]
Hello,

Do you have a `security@` email address I can use to report a security vulnerability?

Thanks,
Scott

**Comment by TheBrenny** [comment]
If you have Gitter, you can message me, and I will try create a fix for it. It's not the XSS vulnerability that everyone has been reporting, though, is it? That's been fixed as far as I can remember, please test against 0.9-Dev. Thanks!

**Comment by paragonie-scott** [comment]
No, this is a new vulnerability.
