### ISSUE TITLE
Feature: API for nested menu-items styling

### ISSUE THREAD

**Issue by PLJNS** [anchorcms/anchor-cms#903]
I'd like to be able to define arbitrary parent-child relationships for pages and have a traverser for it.

Something like this:

    function print_nav_bar($menu_item) {
        if ($menu_item.has_sub_menu_items()) {
            while ($menu_item.subentry = $current_entry) { 
                    if (has_submenus($menu_item)) {
                        echo '<li class="dropdown-submenu" role="presentation">';
                        echo '<a tabindex="-1" href="?page=' . rawurlencode(substr($file_name, 7) . '/' .$current_entry) . '">' . $current_entry . '</a>';
                        echo '<ul class="dropdown-menu">';
                        echo print_nav_bar($file_name . $current_entry . '/');
                        echo '</ul>';
                        echo '</li>';
                    } else if ($menu_item.is_page()){
                        echo '<li><a href="$menu_item.url">' . $menu_item.display_name . '</a></li>';
                    }
                }
            }
        }
    }

Sorry for the mangled PHP, but the point is, recursively iterate over pages and sub-pages and print a nested menu nav bar. There would need to be some API for specifying the template for a top-level menu item and a nested menu item.

I'd really love to implement something like this if I can be pointed in the right direction. In the mean time, I'll try to work it out (or a workaround) on my local copy.

**Comment by TheBrenny** [comment]
Hey!

If you implement the commits from PR #887, you can do this by calling the menu functions `menu_has_children($parent)`, and `get_menus_children($parent)`. Both of which have the optional parameter `$parent`. Omitting this parameter allows you to use the current menu item that has been set in the registry - so if you're using the `menu_items()` function, you can just call `get_menus_children()` from your code, and you get an `array` of all the menu_items for that currently iterated menu item.

If all that jargon makes sense! :laughing:

If you want to make a default function for quickly generating this, look to the `anchor/functions/menus.php` file and append it to the end, or alter the existing function!

**Comment by PLJNS** [comment]
Top notch 👌, thanks for the insight, it does make sense, I'm investigating now.

I'm really enjoying using Anchor and would be game to contribute. If you have any good entry-level tickets, feel free to assign them to me and I've give it a shot.

**Comment by TheBrenny** [comment]
If you want to contribute, there's a whole bunch of open bugs! However, the devs are extremely busy at the moment, that's why there's a whole bunch of open PRs. Be patient, and things will come. In the mean time, myself and @giacomocerquone, are hosting a sibling called `NaveCMS`. Our intentions for it are to maintain an up-to-date Anchor up until Anchor 1.0 releases, however, depending on how far we get we may maintain it past there. - Moral, any PRs made to here, drop them also on Nave! :stuck_out_tongue_winking_eye:
