### ISSUE TITLE
Error when update Metadata

### ISSUE THREAD

**Issue by a9tm** [anchorcms/anchor-cms#910]
I'm going to change theme and got this error:

    Uncaught Exception

    Database Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'value' cannot be null

    SQL: UPDATE `anchor_meta` SET `value` = ? WHERE `key` = ?

    Origin

    system/database/connector.php on line 52

    Trace

    #0 /usr/local/www/anchor/system/database/query.php(217): System\Database\Connector->ask('UPDATE `anchor_...', Array)
    #1 /usr/local/www/anchor/anchor/routes/metadata.php(52): System\Database\Query->update(Array)
    #2 [internal function]: {closure}()
    #3 /usr/local/www/anchor/system/route.php(152): call_user_func_array(Object(Closure), Array)
    #4 /usr/local/www/anchor/system/router.php(152): System\Route->run()
    #5 /usr/local/www/anchor/system/start.php(36): System\Router->dispatch()
    #6 /usr/local/www/anchor/index.php(33): require('/usr/local/www/...')
    #7 {main}

What can I do?

**Comment by TheBrenny** [comment]
What's the theme called, where can it be found? I'll investigate this.

**Comment by a9tm** [comment]
Any themes which I downloaded from anchorthemes.com and I'm using 0.9.2 from homepage, though the beta (?) 0.10 was fixed.

**Comment by daviddarnes** [comment]
I suspect both Basic and Snowly have custom fields certain design additions. I thought it might be just the theme not checking if the fields already exist but Anchor should probably be doing that?

**Comment by TheBrenny** [comment]
So I just uploaded both themes to my testing range for anchor themes ([Bootstrap Tester](https://bootstrap-tester-mastercork889.c9.io/)) and I see no problem with either of them...

**Comment by a9tm** [comment]
So, it's just my VPS? I tried a few times on a FEMP droplet on DgitalOcean before posting here.

**Comment by daviddarnes** [comment]
@a9tm have you tried it all locally? With a copy of the live DB?

**Comment by a9tm** [comment]
I tried it on a DigitalOcean droplet, php 5.6 w/ pdo mysql, and MySQL server 5.6

**Comment by daviddarnes** [comment]
@a9tm that's great, but have you tried testing this in a local environment? Just to see if the issue persists.

**Comment by a9tm** [comment]
@daviddarnes I've installed a fress VM with image was downloaded from [freebsd.org](https://www.freebsd.org/where.html), and used the same [install procedures](https://www.digitalocean.com/community/tutorials/how-to-install-an-nginx-mysql-and-php-femp-stack-on-freebsd-10-1) on Digital Ocean, but the error still appears the same.

![](https://i.imgur.com/D3NfNQj.png)

**Comment by daviddarnes** [comment]
@a9tm thanks, not good. Sorry about this. Do we know what might be causing the issue @TheBrenny?

**Comment by TheBrenny** [comment]
The only thing I'm seeing is that I *THINK* that line 52 doesn't exist in the `anchor/routes/metadata.php` like trace `#2` reckons. This may well be present only in the website version, as (AFAI can see) there's no such line.

Try using 0.9-Dev. Because that seems to be the most up-to-date. And in my opinion the website should just point to GH - saves band with in the process! :P

I'll look at this further during school, but I'm pretty sure value can't be null in the GH branches.

**Comment by rwarasaurus** [comment]
Its the mysql setup, @TheBrenny you might have strict mode disabled while @a9tm mysql strict mode is enabled ... see https://dev.mysql.com/doc/refman/5.6/en/sql-mode.html#sql-mode-strict and https://dev.mysql.com/doc/refman/5.6/en/innodb-parameters.html#sysvar_innodb_strict_mode

this should also be fixed still

**Comment by hariadi** [comment]
Like @rwarasaurus said, its mysql setup.

MySQL 5.6 setting STRICT_TRANS_TABLES by default for new installations of MySQL.

You can check using this command:
```mysql
mysql> SELECT @@GLOBAL.sql_mode;
+--------------------------------------------+
| @@GLOBAL.sql_mode                          |
+--------------------------------------------+
| STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION |
+--------------------------------------------+
1 row in set (0.00 sec)
```

You can test by setting `mysql> SET GLOBAL sql_mode="";` or ` mysql> SET GLOBAL sql_mode="TRADITIONAL";`. Restart mysql and try update/add in anchor app again.

This is not permanent (mysql setup go back to default when mysql service restart). To make it permanent, add this to your my.cnf file (or my.ini if you're using windows):
```
sql-mode="TRADITIONAL" or sql-mode=""
```

Using this method by changing your mysql setup, you don't need to fixing anchor database.

Hope this help

**Comment by TheBrenny** [comment]
Would this be something that might be useful in the installation as we set
up the anchor DB?
