### ISSUE TITLE
overwrite theme_url()

### ISSUE THREAD

**Issue by a9tm** [anchorcms/anchor-cms#912]
I wonder Is there any ways to overwrite theme_url()? It's because I'd like to implement CDN service (Cloudfront or Fastly) to CSS and JS files. I can change links manually, but it's nice if I can alter it all at once..

**Comment by TheBrenny** [comment]
Instead of putting the PHP tags in the quote marks, put the CDN link
instead?

Or am I missing something?

**Comment by a9tm** [comment]
@TheBrenny Right, I over thought the issue and I was lazy then I just insert the full CDN domain in front of PHP tags. It just works.

**Comment by TheBrenny** [comment]
The new XSS. Taking JS from another theme! :P
