### ISSUE TITLE
Feature: Automatic installation of languages

### ISSUE THREAD

**Issue by TheBrenny** [anchorcms/anchor-cms#931]
After the discussion on PR #918, it has been noted that there should be an easier method of installing different languages, OOTB from the installation pages. Where on the page, and which page this is located on, I have no idea.

Discuss?

**Comment by TheBrenny** [comment]
[This](http://jsbin.com/bovipafure) could be a potential fix if jQuery is allowed within anchor.

**Comment by TimohStudios** [comment]
Although that looks really cool, I don't think it's very good for UX. I will have to wait around _hoping_ that my language will come by at some point. This could still be done without jQ by the way.

**Comment by daviddarnes** [comment]
Prefer not to use JavaScript to switch languages, PHP can do the job perfectly fine on its own.

**Comment by TheBrenny** [comment]
@TimohStudios, I guess so... Maybe have the `previous`, `current` and `next` all shown at the same time... I'm not amazing at JS, and to be quite honest, I'm terrible at designing, so I don't really pay attention to those methods. I prefer back-end over front-end any day.

@daviddarnes, I assumed that we would have the link point to - not a view - but a function that would download the language, set it as default in the anchor config, and redirect back to the page that it was called from.

**Comment by daviddarnes** [comment]
I'm not sure what you mean? You don't need to redirect back to a page do you? I thought it would be like a plugin process but with a UI? Or possibly not even that. Plugins and themes require a bit of dev knowledge to install them, maybe languages should be the same? Anchor could come with a specific set of languages that cover _most_ of our users. The rest could be installed by adding it into a specific folder within the CMS. Then it would be selectable within the admin UI.

I realise we want to make Anchor accessible, but I think languages should be looked upon like any other add on we have.

**Comment by Radiergummi** [comment]
What do you guys think of [this](http://jsfiddle.net/kue8jvvL/)? It's using a pure JS library (see [here](http://www.cssscript.com/lightweight-flexible-pure-javascript-autocomplete-library/)).

**Comment by daviddarnes** [comment]
@Radiergummi pretty sure we already have a JS script that acts like this in the installation process.

**Comment by Radiergummi** [comment]
I was focusing more on the process itself - this script can fetch an ajax
list of available languages (eg. from the Anchor repo) and trigger the
download on click. Later, additional languages could be installed as
packages within the admin panel.

2015-10-26 10:40 GMT+01:00 David Darnes <notifications@github.com>:

**Comment by daviddarnes** [comment]
@Radiergummi I see. Well that would be a great feature! However I don't want to create more work on top of the initial problem. We might just need to select the right languages and place them in the basic install, and then document how to install additional languages. Then these kinds of features could be added on top.

The directory seems to be `root/anchor/languages`, so I assume languages can be added here and they'll appear in the admin interface?

**Comment by CraigChilds94** [comment]
http://feathub.com/anchorcms/anchor-cms/+12
