### ISSUE TITLE
Bug: View fails when going to route "login" if user is already logged in

### ISSUE THREAD

**Issue by teamcreed** [anchorcms/anchor-cms#933]
Reproduce: Login into your CMS account with your user and password, type in the url "hosting/project-name/admin/login" and observe how the login form displays in the left-up corner and the view remain as in the admin panel.

![test1a](https://cloud.githubusercontent.com/assets/14580377/11135766/a35bfc6e-897a-11e5-84e3-bbceb304b3c2.png)

![test1b](https://cloud.githubusercontent.com/assets/14580377/11135767/a35ca268-897a-11e5-883a-fbb8f284cf74.png)

![test1c](https://cloud.githubusercontent.com/assets/14580377/11135768/a35f90ae-897a-11e5-804f-8a1f89ed9d2f.png)

The bug were tested in a local environment and in my own hosting; with Firefox, Chrome and Internet Explorer.

**Comment by TheBrenny** [comment]
Isn't it as simple as changing [this line](https://github.com/anchorcms/anchor-cms/blob/master/anchor/routes/admin.php#L40), to have it checked if we're already logged in? I'll quickly add a PR for this.

**Comment by CraigChilds94** [comment]
@TheBrenny @teamcreed I've merged the pull request which fixes this in :) Thanks for noticing this guys!
