### ISSUE TITLE
Uncaught Exception on Pages section

### ISSUE THREAD

**Issue by teamcreed** [anchorcms/anchor-cms#938]
When I try to access to the "Pages" section on the admin area it throws an uncaught exception. Call to undefined function menu_parent().

Does anyone knows why is this happen? I'am using the 0.9-dev.

![picture1](https://cloud.githubusercontent.com/assets/14580377/11272719/22e0b206-8ea1-11e5-8e6d-2d1b7c588316.png)

**Comment by daviddarnes** [comment]
Is there a particular reason you're using the development version?

**Comment by teamcreed** [comment]
Yes, I want to contribute maybe with a new feature so I'm working on the 0.9-dev branch.

**Comment by daviddarnes** [comment]
That's awesome, thanks for contributing. However you should be working off the 0.10-dev branch, as stated in the contributing.md file.

**Comment by teamcreed** [comment]
Oops i'm sorry, my mistake. I will work off the 0.10-dev. So there is no need to fix this bug on the 0.9-dev branch?

**Comment by daviddarnes** [comment]
@teamcreed no problem. I'm not sure if the branch needs fixing, maybe other branches merge into in order to fix it? cc @CraigChilds94

**Comment by CraigChilds94** [comment]
@teamcreed You can continue to work of either branch as long as `0.10-dev` has the changes also. Though I'd recommend trying the `0.10-dev` branch. Purely because I fixed this issue in it.
