### ISSUE TITLE
Bug: Uncaught Exception when updating a page type

### ISSUE THREAD

**Issue by teamcreed** [anchorcms/anchor-cms#939]
Working on 0.10-dev branch.

Reproduce: Login into your CMS account with your user and password, go to "extend" menu and select "Site Page Types".
Create a new page type, save. Click on the page type you has just create, try to edit the information:

If you change just the "name" and update -> Uncaught Exception.
If you change just the "slug" and update -> Uncaught Exception.
If you don't change anything and update -> Uncaught Exception.
If you change both of the fields -> No problem but the system does nothing.

![bf1](https://cloud.githubusercontent.com/assets/14580377/11307387/f2ae9d98-8f89-11e5-93c6-f8848a3afd92.png)

![bf2](https://cloud.githubusercontent.com/assets/14580377/11307386/f229bef2-8f89-11e5-96b2-1c394341ab77.png)

![bf3](https://cloud.githubusercontent.com/assets/14580377/11307384/f2065994-8f89-11e5-9651-bd964b38fcd6.png)

**Comment by CraigChilds94** [comment]
@teamcreed Thanks for making me aware, I shall look into this ASAP.
