### ISSUE TITLE
Feature: uploading images on new pages.

### ISSUE THREAD

**Issue by teamcreed** [anchorcms/anchor-cms#940]
Working on 0.10-dev branch.

I would like to have the possibility to upload an image when creating a new page of my site, but apparently the system doesn't have that feature yet.

Possible bug:
When creating new post the image has to be dragged onto the field but at the end it doesn't get anything upload.

![ft1](https://cloud.githubusercontent.com/assets/14580377/11307507/d601f50e-8f8a-11e5-938e-1950159696d8.png)

**Comment by CraigChilds94** [comment]
@teamcreed We've had a lot of issues with file uploads in the past, maybe something has been removed. Thanks for picking up on it; I shall check it out! :D

**Comment by teamcreed** [comment]
@CraigChilds94 no problem, I will try to contribute to fix this issue and also the 939 as well if I can.

**Comment by 2green2freak** [comment]
(First of all I've to say sorry, I've never used GitHub before, so please don't flame if it's my own fault)

I've just cloned the latest version and if I try to upload pictures, it indeed work, but the path to the image is wrong, like in the screenshot of the OP (a slash is missing between "anchor-cms" and "content". If I manually add the slash, it works perfectly. I'm quiet new to webdesign, php and all. I don't know how to fix that.

**Comment by CraigChilds94** [comment]
Images are now able to be uploaded in `pre-1.0-develop`
