### ISSUE TITLE
Bug: RSS Feed broken

### ISSUE THREAD

**Issue by heubergen** [anchorcms/anchor-cms#941]
Hi, I use Anchor 0.10 and I experience the following error with my rss feed.

I use PHP 5.6.12 and apache 2.2.15:
{"date":"2015-11-21 22:51:18","message":"Call to a member function take() on string","trace":[{"function":"shutdown","class":"System\\Error","type":"::","args":[]}],"line":204,"file":"\/var\/www\/virtual\/jm3\/blog.z33.ch\/anchor\/routes\/site.php"}

You can find the rss feed under the follow address: https://blog.z33.ch/index.php/feeds/rss

**Comment by daviddarnes** [comment]
Hi @heubergen. Just to clarify, are you using this for a project or are you wanting to contribute to Anchor?

**Comment by heubergen** [comment]
Hi @daviddarnes I'm running this project under my domain and I'm a user, not a developer.
Because I think it's a bug, I create this issue so maybe a dev can see and fix it (if it's really a bug)

**Comment by daviddarnes** [comment]
I see, well if you're using for a live project you might be better off using the master branch version or downloading the version from the website http://anchorcms.com

**Comment by heubergen** [comment]
Okay, thanks for the info.

But I think it's a real bug and I guess @CraigChilds94 will try to fix it, right?
I've no problem with some bugs in live system :)

**Comment by CraigChilds94** [comment]
@heubergen I'm using `0.10-dev` are you able to send me a dump of the database? I think there may be an issue with the query.

**Comment by heubergen** [comment]
@CraigChilds94 I could not attach the file original so I upload it to my dropbox:
https://www.dropbox.com/s/x1thitypgf276ck/2015-11-26-database.sql?dl=0

**Comment by beli3ver** [comment]
Is there a fix for that problem?
I have same error

**Comment by beli3ver** [comment]
Ok, I find the problem, the problem is this:
```php
$query = Post::where('status', '=', 'published');->sort(Base::table('posts.created')->take(25), 'desc');
```
When you cut this and only use this one:
```php
$query = Post::where('status', '=', 'published');->sort(Base::table('posts.created'), 'desc');
```
it works.
So the take(25) is here the problem.

**Comment by limenet** [comment]
I have the same bug as @heubergen running Anchor on commit a7d3f3e1f177cb0cac97adb05f4d667a23885a40 (latest master branch at the time of writing). The fix from @beli3ver works, thanks!

To still be able to limit the number of posts, `take(25)` has to go *after* the call to `sort()` (since `Base::table()` returns a string and you cannot call a method on a string):

```php
$query = Post::where('status', '=', 'published');->sort(Base::table('posts.created'), 'desc')->take(25);
```

Do you want me or @beli3ver to send a PR? If so, against what branch?

/cc @CraigChilds94

**Comment by beli3ver** [comment]
I will push the fix :dancer:

**Comment by limenet** [comment]
:+1:
