### ISSUE TITLE
Installer's default site_path in Windows causes parse errors

### ISSUE THREAD

**Issue by ehassler** [anchorcms/anchor-cms#943]
When anchor is the web root the default site_path in install/routes.php on Windows evaluates to `\`.  If the user accepts this then two errors occur.  First, the .htaccess file gets a `RewriteBase \`  which causes a server error.  Second, the anchor/config/app.php file is written as
```php
return array(
	'url' => '\',
	'index' => '',
	'timezone' => 'America/Tijuana',
	'key' => 'XYHAPWix6hwpg5ZkCatmpBW9Sm6S9u3E',
	'language' => 'en_GB',
	'encoding' => 'UTF-8'
);
```
which causes a parse error as `'\'` is an unclosed string starting with character `'`.  

Apologies, as I'm just learning git.  One solution seems to be altering install/routes.php line 132 to be
```php
$vars['site_path'] = str_replace('\\','/',dirname(dirname($_SERVER['SCRIPT_NAME'])));
```
I've made this edit and re-ran the installation process getting an appropriate default site_path.

**Comment by idiot** [comment]
Yep, looks good. Thanks! Fixed it in 8bb503f2224154623b45828c6745708bd02a5ba4 for you :smile:
