### ISSUE TITLE
How to create child pages loop in a page? label:Discussion 

### ISSUE THREAD

**Issue by rogerrogeranchor** [anchorcms/anchor-cms#944]
Hi,

I have a page that I named as "portfolio" and I created a php file as "page-portfolio.php" so I'm able to modify only this page's style or something, but I want to list all the child pages that I'm going to write in the future, something similar to "posts" page.

I'm thinking that I am not able to use posts because I'll use it to post blog a news only.

Thanks for your help :)

**Comment by idiot** [comment]
Can't think of an elegant way of doing it with the old theme functions, but this will work, as long as you use `$page` in the loop instead of the functions.

```php
<?php foreach(Page::where('parent', '=', page_slug())->get() as $page): ?>
	My page is <?php echo $page->name; ?>
<?php endforeach; ?>
```

**Comment by rogerrogeranchor** [comment]
Thanks for your reply @idiot. So, I need to put that code in my page-portfolio.php? Sorry, but I'm not a developer, I'm photographer he, he.

**Comment by idiot** [comment]
Yep, inside any page template should work. So the bit starting at

    <?php foreach(Page::where('parent', '=', page_slug())->get() as $page): ?>

Is the start of the loop for your child pages, so anything you want to display goes after this. To see what you can use, you can do `<?php var_dump($page); ?>` and anything in there you can call like `<?php echo $page->whatever; ?>`.

    <?php endforeach; ?>

Anything in between those two foreach lines gets done for every child page.
