### ISSUE TITLE
Docs out of date with article_html()?

### ISSUE THREAD

**Issue by k4kfh** [anchorcms/anchor-cms#946]
I am trying to build a custom Anchor theme and for some reason:

<?php echo article_html(); ?>

Does not convert markdown to html, it just returns the markdown as a string.

EDIT: upon looking at some other themes, I found that article_markdown is the correct function. However that did not appear to be anywhere in the docs, so that's a problem.

**Comment by idiot** [comment]
Ooops! Yeah you're right, the docs are woefully out of date. We're [working on it](/anchorcms/anchor-docs), though!
