### ISSUE TITLE
Feature: custom user attributes?

### ISSUE THREAD

**Issue by k4kfh** [anchorcms/anchor-cms#947]
Could we add a custom attributes section for individual users, with a php function to grab them? I want to have a "profile image" for authors on my site, but I can't figure out a good way to do it.

**Comment by daviddarnes** [comment]
Nice idea! Could work really well as a "custom profile pages" plugin :)

**Comment by CraigChilds94** [comment]
http://feathub.com/anchorcms/anchor-cms/+11
