### ISSUE TITLE
Feature: menu triggering

### ISSUE THREAD

**Issue by danoxide** [anchorcms/anchor-cms#948]
What do you think about create a menu in admin panel and trigger it wherever you want in a theme? For example, you have a footer where you have a community section that contains a few urls (facebook, twitter, etc.), but what if you want to edit it? You must edit footer.php. The solution is a menu triggering system.

1. Create a new menu called "Community"
2. Enter some URLs
3. Trigger in theme by `menu('community')`

**Comment by daviddarnes** [comment]
Sounds like you're wanting to have custom menus that are set in the theme. Very similar to how WordPress works with menus. It would be a good feature to add in, but 'Custom Menus' sounds like something we could bundle into a plugin?

The example you gave could be done with custom variables, either by making several of them or a markdown list with links in them.

**Comment by danoxide** [comment]
Yeah, "Custom Menus" can be a plugin like portfolio, gallery, etc.

Okay, but what about plugin API? How can I create a plugin without API? I wanted to build a website for my client powered by Anchor, but I can't because there aren't any plugins.

**Comment by daviddarnes** [comment]
@danoxide we're still working on how plugins work, I believe there is some progress on the dev branch but I can't be sure.

**Comment by k4kfh** [comment]
I don't necessarily need custom menus, but it would be nice to be able to specify the order in the main menu. Even if each page just had "menu number" attribute on its edit page, and the items were arranged from least to greatest, that would allow more customization than what we have now.

@danoxide you could do this in pure HTML by using a custom site-wide variable. It would be a little messy, but would allow easy reusing of the same HTML in places across the whole site. I suspect it would get the job done until plugins can.

**Comment by daviddarnes** [comment]
@k4kfh thanks for the response. Actually I think menu reordering is coming in v1.0, a simple drag and drop reordering technique will allow you to do it.

**Comment by danoxide** [comment]
@daviddarnes, so how would you see the solution of plugins?

**Comment by TheBrenny** [comment]
Use menu items and children, but don't show them menu in the menu list?

From there you can edit the footer to shoe specifically that menu item and its children.

This is *A* workaround. Not the best, but something.

**Comment by daviddarnes** [comment]
@danoxide sorry but I'm not the best person to ask about how plugins is being implemented. Maybe @kieronwilson can explain better?

**Comment by CraigChilds94** [comment]
http://feathub.com/anchorcms/anchor-cms/+10
