### ISSUE TITLE
More options for pagination buttons HTML?

### ISSUE THREAD

**Issue by k4kfh** [anchorcms/anchor-cms#950]
I know there are "canned" pagination buttons with ``posts_next()`` and ``posts_prev()``, but if I don't want to use that text/styling can I change that? What if I want to have different class attributes on that ``<a>`` element?

**Comment by idiot** [comment]
OK - just updated the master branch just now. If you update to the latest-master version you can now call like so:

```php
<?php echo posts_prev('Previous page', '', array('class' => 'my-prev-class', 'title' => 'my awesome title')); ?>
```
