### ISSUE TITLE
Failed to change sitename in metadata

### ISSUE THREAD

**Issue by Canibus** [anchorcms/anchor-cms#951]
Help me please ! When i try to change sitename or other constant in admin interface i got this error:

Uncaught Exception

require(/home/admin/web/example/public_html/themes//posts.php): failed to open stream: No such file or directory

Origin

system/view.php on line 87

Trace

#0 /home/admin/web/example/public_html/system/view.php(87): System\Error::native(2, 'require(/home/a...', '/home/admin/web...', 87, Array)
#1 /home/admin/web/example/public_html/system/view.php(87): System\View::render()
#2 /home/admin/web/example/public_html/system/route.php(160): System\View->render()
#3 /home/admin/web/example/public_html/system/router.php(152): System\Route->run()
#4 /home/admin/web/example/public_html/system/start.php(36): System\Router->dispatch()
#5 /home/admin/web/example/public_html/index.php(15): require('/home/admin/web...')
#6 {main}

**Comment by daviddarnes** [comment]
@Canibus hi, which version of Anchor are you using and where did you download it from?

**Comment by Canibus** [comment]
@daviddarnes 0.9.2 . Downloaded from anchorcms.com

**Comment by Canibus** [comment]
by the way, i cant restore my backup from my Vesta panel. 
this is error: restore failed -> Database connection to MySQL host localhost failed

**Comment by daviddarnes** [comment]
@Canibus thanks for the info.

@CraigChilds94 are you able to help with this issue at all?

**Comment by idiot** [comment]
Can you access the database in PHPMyAdmin or something like that and dump out the `anchor_meta` table?

**Comment by Canibus** [comment]
@idiot i can connect and check anchor_meta table only from root user . <img src="http://s018.radikal.ru/i514/1512/96/68c6da5ef219.png">

**Comment by idiot** [comment]
Why is everything blank? That's odd. To fix the 

    require(/home/admin/web/example/public_html/themes//posts.php): failed to open stream: No such file or directory

error, you can click "edit" on the theme row (2nd from bottom) and enter `default` as the value.

**Comment by Canibus** [comment]
OH MY GOSH!!! You are awesome guys) 
Thank you very much !

**Comment by Canibus** [comment]
hey guys, i find a bug . Everytime when i change sitename or auto-allow comments i got empty theme value in my table

**Comment by Canibus** [comment]
by the way, my Vesta panel still trying to restore database

**Comment by Canibus** [comment]
ok, i have found the issue. i just change root ( MySql ) password same like in Vesta panel root user and restore has been succesful complete

**Comment by daviddarnes** [comment]
@Canibus has that resolved all your issues?

**Comment by Canibus** [comment]
@daviddarnes  yup, thank you :)
