### ISSUE TITLE
Bug: Admin panel buttons broken

### ISSUE THREAD

**Issue by alexbagirov** [anchorcms/anchor-cms#954]
That's what I have.

https://static.suave.it/203717a3/55209839/8623008b.png

My browser is Chrome 47.0.2526.106 m

**Comment by alexbagirov** [comment]
Ah, it seems to be caused by the button's text length. My latest PR to Russian tranlation will fix it.

**Comment by daviddarnes** [comment]
@alexbagirov could you reference the PR? Have you changed the wording so it fits better? As long as it doesn't change it's meaning then great.

**Comment by alexbagirov** [comment]
@devinhalladay I will mention you in translations repository.
