### ISSUE TITLE
Bug: Uncaught Exception with "intl"

### ISSUE THREAD

**Issue by ghost** [anchorcms/anchor-cms#957]
On several occasions, an error with "intl" is generated. 

This error is present on the frontend and / or backend. This error happens very often when I browse the site (frontend) or when I add / modify content (backend) .

![capture d ecran 2015-12-29 a 16 11 40](https://cloud.githubusercontent.com/assets/16477959/12036609/e9539532-ae47-11e5-8656-776450f14410.png)

![capture d ecran 2015-12-29 a 16 22 42](https://cloud.githubusercontent.com/assets/16477959/12036679/750a9b7a-ae48-11e5-9170-1361f7c3cb6f.png)

Bye.

**Comment by daviddarnes** [comment]
Which version are you using? Did you download it from the site or on GitHub?

**Comment by hocktor** [comment]
As shown in the screenshot, it is version 0.9.2 downloaded from the site anchorcms.com.

Bye.

**Comment by daviddarnes** [comment]
@hocktor sorry, but I needed to clarify that it was downloaded in the normal fashion.

**Comment by hocktor** [comment]
No problem. My version of PHP is PHP Version 5.6.10 (via MAMP). If you need more information, don't hesitate !

**Comment by CraigChilds94** [comment]
This appears to be an issue with the server configuration. I think one of the modules is trying to be loaded more than once.
