### ISSUE TITLE
 Why "Post" page?

### ISSUE THREAD

**Issue by hocktor** [anchorcms/anchor-cms#958]
I don't understand the interest of the "post" page in the backend. I tried to change it (add text) ... but no change on the frontend.

I suppose this page is very important to view all posts ... but I find there is an ambiguity to have such a page directly into the backend ... especially if it can manage posts (this isn't really a "page" in itself !)

What do you think ?

Bye.

**Comment by daviddarnes** [comment]
It does have weird properties, but it should still exist. Users would still want to change the name, reorder it in the menu and hide it if they so wish.

The only change I'd suggest is that the content of posts page should be outputted to the front-end, but that's something for the theme to sort.
