### ISSUE TITLE
Feature: Improving the display of pages and sub-pages in the backend

### ISSUE THREAD

**Issue by ghost** [anchorcms/anchor-cms#959]
In the backend, under "Pages", all pages are displayed below each other. It's not clear.

Here's what I propose :

![capture d ecran 2015-12-30 a 08 39 05](https://cloud.githubusercontent.com/assets/16477959/12047743/0c143200-aed1-11e5-9fc0-8826822dbc25.png)

Ditto for the posts ?

Bye.

**Comment by daviddarnes** [comment]
Could you explain the changes you've made? I'm not sure how you can have sub-posts? :s

**Comment by hocktor** [comment]
The sub-pages are offset from the main-pages. You see the website structure.

It should add a class to the li elements. This class must be present depending on the depth of the child (data stored in the database).

**Comment by daviddarnes** [comment]
Good idea, I think this might be present in pages in v1.0. You might want to check out that version.

**Comment by TheBrenny** [comment]
Isn't this a working feature in 0.9-dev?

**Comment by daviddarnes** [comment]
@TheBrenny I believe so. Will close in this case.
