### ISSUE TITLE
More content per page in the backend

### ISSUE THREAD

**Issue by hocktor** [anchorcms/anchor-cms#960]
You can choose how many posts to display per page in the backend. However, this number is limited to 15 (via a gauge).

To change this, I connect to the database directly or via template (view).

It would be more interesting to let the administrator to choose, via a input text or select. 

Especially at present the gauge doesn't indicate the exact number of posts per page ...

![capture d ecran 2015-12-30 a 09 05 32](https://cloud.githubusercontent.com/assets/16477959/12047962/881c6626-aed4-11e5-848c-240e285be223.png)

Bye.

**Comment by daviddarnes** [comment]
I don't think having a text input would be a wise decision. Users might input a number that is too much of a strain on the server. If you really want to have more (e.g. 100) posts per page you can code it into the theme.

**Comment by hocktor** [comment]
Ok.

But why not increase the minimum threshold?

I think the best is to always leave the choice to user ... user who is supposed to know the advantages and disadvantages to a high number.

Wordpress lets the user choose.

Bye.

**Comment by daviddarnes** [comment]
That's a good idea, and I believe it has been discussed for v1.0. Also, you'd be surprised what the user doesn't know about server load.
