### ISSUE TITLE
Bug: Some pages is problematic (slug ?)

### ISSUE THREAD

**Issue by ghost** [anchorcms/anchor-cms#961]
I want to use "Anchor CMS" in a specific part ... the creation of a documentation for CSS FrameWork.

I have a section that must be named "System". So I created a page with this name and slug.

When I try to access this page via the link in the menu or by going directly to the URL, I have an error page 403 - Forbidden.

However, when I parameter page "System" as the default page ... well I can play content (I'm not redirected to an error page ... but only in this case !) .

Version : 0.9.2

Bye.

**Comment by daviddarnes** [comment]
There is an issue when naming pages the same as directories within the CMS. The slug comes from the name of the page and that slug conflicts with directory in the anchor install. We'll take a look at this.

P.S. @hocktor could you please follow our [contributing guidelines when creating an issue](https://github.com/anchorcms/anchor-cms/blob/master/contributing.md#how-to-submit-issues). Thanks.

**Comment by TheBrenny** [comment]
We could have Anchor detect directories and make specialised slugs for pages with the same name as a found directory?

**Comment by daviddarnes** [comment]
@TheBrenny does that mean that nobody can have the slug "system"? I've had the same issue when creating a page called "themes". Maybe we should be prefixing those directories? Or finding a work around.

**Comment by TheBrenny** [comment]
But if we prefix the directories, maybe someone wants "anchor-themes" as their prefix? :/

I can only assume a workaround be put in the htaccess, but I don't know enough of that to understand it...

**Comment by daviddarnes** [comment]
@TheBrenny ha, I thought that problem too. Maybe just a "an" prefix? "an-themes", "an-system" and so on. Far less likely to be used.

**Comment by TheBrenny** [comment]
Less likely maybe, but *what if* ( ;) ) in the slightest chance, our admin
makes "an-install" (and maybe the install dir isn't deleted) or "an-app" in
the case of 1.0?

I think in my very complex mind of things its actually the slug that may
need to be prefixed/suffixed on detection.

Because that's probably the best way we can go about this issue? :/

**Comment by daviddarnes** [comment]
@TheBrenny I'd rather provide the user with better slugs than force them to change them. Wordpress does something similar with 'wp-' prefixing. Is there not a way to alias slugs, so we get the best of both worlds?

**Comment by rwarasaurus** [comment]
@ghost could you share your apache/nginx config?
