### ISSUE TITLE
Giving the ability to disable certain modules ?

### ISSUE THREAD

**Issue by hocktor** [anchorcms/anchor-cms#962]
I think it would be interesting to give the ability to disable certain modules in the backend.

For example, if you don't wish to use the "blog", you should be able to disable it. This part is no longer visible in the backend while being sure it's not a problem with frontend (technically, SEO, etc ...)

Version : 0.9.2

Bye.

**Comment by daviddarnes** [comment]
The blogging aspect is quite important to Anchor, most people use it as a blogging platform. I don't think hiding it in the backend is that important. You can just hide the blog page on the site though.
