### ISSUE TITLE
Feature: Share posts to Facebook

### ISSUE THREAD

**Issue by axelniklasson** [anchorcms/anchor-cms#965]
It would be neat to be able to connect one's Facebook account to Anchor and enable sharing functionality for posts.

**Comment by daviddarnes** [comment]
@axelniklasson so it posts the article to Facebook when you post it live?

**Comment by axelniklasson** [comment]
@daviddarnes Exactly. Like an "auto-share" function.

**Comment by daviddarnes** [comment]
@axelniklasson sounds good! Though I'd personally like to do it manually so I can customise the post or make sure I don't inherit an error from the main article.

**Comment by axelniklasson** [comment]
@daviddarnes There are lots of features that could be implemented - my use case is to simply post a link to the published post, i.e. "Axel Niklasson" has shared ... " and when someone clicks on the link in the Facebook feed, the user is directed to the blog linked post.

However, a full-featured plugin would be insanely awesome!

**Comment by 2xAA** [comment]
I think a number of social networks would be great, such as Tumblr and Twitter for example.

**Comment by TheBrenny** [comment]
Sort of how it shares something from other websites (like soundcloud) where you can click on the track and it takes you right there?

That would be pretty neato, but I guess this is where the line needs to be drawn between plugin and feature...

**Comment by daviddarnes** [comment]
I'd say this is a feature for plugins.

**Comment by CraigChilds94** [comment]
http://feathub.com/anchorcms/anchor-cms/+9
