### ISSUE TITLE
Deleting default post page throw an uncaught exception

### ISSUE THREAD

**Issue by FerrazzzZ** [anchorcms/anchor-cms#971]
Hi Guys,

I've noticed if you delete the post page the throws an uncaught exception. This happens even if you have other pages.
Heres there trace
#0 /Volumes/Sandbox/sites/wordpress/anchor/routes/site.php(12): System\Error::native(8, 'Trying to get p...', '/Volumes/Sandbo...', 12, Array)
#1 /Volumes/Sandbox/sites/wordpress/anchor/run.php(56): require('/Volumes/Sandbo...')
#2 /Volumes/Sandbox/sites/wordpress/system/start.php(21): require('/Volumes/Sandbo...')
#3 /Volumes/Sandbox/sites/wordpress/index.php(33): require('/Volumes/Sandbo...')
#4 {main}

**Comment by daviddarnes** [comment]
@FerrazzzZ did you set another page as the post page?

**Comment by FerrazzzZ** [comment]
@daviddarnes Well I've noticed it will start working in you set the id of another page to 1 on the db. Further investigation the it seems like the default page as the id of always one. Its really not a problem to me, just wanted to make you guys aware :+1:

**Comment by TheBrenny** [comment]
@daviddarnes We should probably add something in [this route][https://github.com/anchorcms/anchor-cms/blob/master/anchor/routes/pages.php#L220] to make the default posts page a different page. :dizzy_face:

**Comment by daviddarnes** [comment]
@TheBrenny we just need a stopper in place to stop users deleting the posts page, unless they move the posts page to another page.

**Comment by cxdy** [comment]
Attempted a fix, won't be able to test until I'm home though. Probably won't work.

**Comment by CraigChilds94** [comment]
@TheBrenny @FerrazzzZ You can't delete the posts/home page in the version of Anchor that is present in `pre-1.0-develop` which will hopefully soon be released. So this HAS been fixed for a while, just not released.
