### ISSUE TITLE
Feature: Tags

### ISSUE THREAD

**Issue by FerrazzzZ** [anchorcms/anchor-cms#972]
I think it would be a good idea to implement a tagging system for the posts. Because reader may want to read things on the same family of a specific post. I know you have categories but you can only assign one category per post. So tags would make a better job.

**Comment by FerrazzzZ** [comment]
Ups i guess thats what custom fields were made for?

**Comment by TheBrenny** [comment]
This has already been mentioned at #537.

It even has a solution: [here][https://github.com/anchorcms/anchor-cms/issues/537#issuecomment-110842503]
