### ISSUE TITLE
Site Metadata post per page affects admin page.

### ISSUE THREAD

**Issue by FerrazzzZ** [anchorcms/anchor-cms#973]
Hi Guys, I guess you will get used to me soon. Ive noticed when setting the posts per page it also affects the admin posts per page, I think that is an issue? Correct me if am wrong

**Comment by daviddarnes** [comment]
@FerrazzzZ you're right, it is sort of. Do we have that sorted in v1.0? cc @kieronwilson

**Comment by CraigChilds94** [comment]
This is fixed. The admin no longer uses the same config value.
