### ISSUE TITLE
Code phraser error

### ISSUE THREAD

**Issue by beli3ver** [anchorcms/anchor-cms#982]
Hi,

when I try to write a code block over more then one line, like this
cd /opt
mkdir test
then i must make it so
> \`cd /opt\`\<br >
> \`mkdir test\` 

because when I make it so

> \`cd /opt mkdir test\` 

the whole code is in one line
and so

> \`cd /opt 
>
> mkdir test\` `

the phraser didn't realize that this is code.

**Comment by mrmlnc** [comment]
A block code is written in four-space.

```
    cd /opt
    mkdir test
```

![image](https://cloud.githubusercontent.com/assets/7034281/12376794/c80e15b8-bd16-11e5-9256-2ea45185bb56.png)
![image](https://cloud.githubusercontent.com/assets/7034281/12376795/ce7f3544-bd16-11e5-87cd-8bf6860385eb.png)

**Comment by beli3ver** [comment]
it is not working on my site,
when i make 4 spaces, it looks like normal text no phrasing

**Comment by mrmlnc** [comment]
Sorry, but "phrasing" is quote? If so, then:
```md
> cd /opt
>
> mkdir test
```

This construct expands to:
```html
<blockquote>
  <p>cd /opt</p>
  
  <p>mkdir test</p>
</blockquote>
```

**Comment by beli3ver** [comment]
No I mean it is code

Am 17. Januar 2016 10:54:20 MEZ, schrieb Denis Malinochkin <notifications@github.com>:
>Sorry, but "phrasing" is quote? If so, then:
>```md
>> cd /opt
>>
>> mkdir test
>```
>
>This construct expands to:
>```html
><blockquote>
>  <p>cd /opt</p>
>  
>  <p>mkdir test</p>
></blockquote>
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/anchorcms/anchor-cms/issues/982#issuecomment-172306716

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mrmlnc** [comment]
You can use HTML to do this directly in the Editor:
```html
Text text text

<code>cd /opt<br>mkdir test</code>

More
```
This construct expands to:
```html
<p>Text text text</p>
<p><code>cd /opt<br>mkdir test</code></p>
<p>More</p>
```

**Comment by beli3ver** [comment]
OK that is a workaround
But i want to use markdown 

Am 17. Januar 2016 11:01:37 MEZ, schrieb Denis Malinochkin <notifications@github.com>:
>You can use HTML to do this directly in the Editor:
>```html
>Text text text
>
><code>cd /opt<br>mkdir test</code>
>
>More
>```
>This construct expands to:
>```html
><p>Text text text</p>
><p><code>cd /opt<br>mkdir test</code></p>
><p>More</p>
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/anchorcms/anchor-cms/issues/982#issuecomment-172307469

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mrmlnc** [comment]
Are you sure that Markdown supports this syntax?

**Comment by beli3ver** [comment]
Yes


Am 17. Januar 2016 11:49:40 MEZ, schrieb Denis Malinochkin <notifications@github.com>:
>Are you sure that Markdown supports this syntax? 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/anchorcms/anchor-cms/issues/982#issuecomment-172313106

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by elafarge** [comment]
Mmmh, this feature might just be a recent addition to MarkDown or something specific to Github flavored markdown.

Anyway, I had the same problem (since I'm writing a tech blog with lots of code sample that was kind of a problem for me :) ) so I forked anchor to make it use the PHP library Parsedown instead of Markdown (which in addition to that, was an old version of Markdown) to parse Markdown and it works like a charm.

I made a PR against this repository here : https://github.com/anchorcms/anchor-cms/pull/976 , it should solve the issue if it gets merged. Meanwhile if you were using the latest `master` version of Anchor CMS you should be able to use my fork here: https://github.com/elafarge/anchor-cms/commits/master .

Cheers ! 

Etienne

**Comment by beli3ver** [comment]
Ok, I will check it.
