### ISSUE TITLE
Feature: Customs "themes" for admin panel.

### ISSUE THREAD

**Issue by moje-s** [anchorcms/anchor-cms#992]
Can you add ability to use an own theme for admin site by creating folder view-{own} (with required files)?  
This will allow to develop an own admin panels. 
It do not requires an own settings in global configuration (extend/metadata). The change of this setting can by done manually in app.php.

**Comment by CraigChilds94** [comment]
On Feathub, http://feathub.com/anchorcms/anchor-cms/+4
