### ISSUE TITLE
Bug: incorrect favicon file extension.

### ISSUE THREAD

**Issue by moje-s** [anchorcms/anchor-cms#993]
My graphics program showed me the message about incorrect file extension and changed it into .png.

**Comment by daviddarnes** [comment]
Could you explain the steps to recreate this bug?

**Comment by moje-s** [comment]
I was wondering why there is no favicon for admin panel. 
Apart from the missing the meta tag for favicon, I checked is there a required file. When I opened this file in the IrfanView, it showed me the message and changed file extension into .png.

**Comment by daviddarnes** [comment]
Hmm, seems weird. Which browser are you using?

**Comment by moje-s** [comment]
Mostly firefox. 

All file was pulled from git hub. 

There is no meta tag for favicon:
https://github.com/anchorcms/anchor-cms/blob/master/anchor/views/partials/header.php
