### ISSUE TITLE
Bug: redirect of page.

### ISSUE THREAD

**Issue by moje-s** [anchorcms/anchor-cms#994]
Input in form for redirect should allow to ser url even if there was no http:// or https:// prefix. 
At the front-site the redirection should open a website in the new window or the new tab.

**Comment by daviddarnes** [comment]
I agree that urls shouldn't have to have a protocol, but opening in a new tab is dependant on each case.

**Comment by moje-s** [comment]
So there should be the additional option to set it. Or better, divide the pages and the redirects into two different forms (at two sparated sites).

**Comment by TheBrenny** [comment]
I don't quite understand the bug that is being presented? `CTRL` clicking a link will open it up in a new tab under Chrome. This could be based on how the user has set up their browser - I force almost all links to open as new tabs (gotta love chrome extensions! :stuck_out_tongue_winking_eye:)

**Comment by daviddarnes** [comment]
After reading this again I think it's more of a "per case" option. Also the http(s) should probably be dealt with on the site you're directing to.
