### ISSUE TITLE
Feature: Category as the page. 

### ISSUE THREAD

**Issue by moje-s** [anchorcms/anchor-cms#996]
Ability to use single category as a page in menu, to display posts only from one category or a category and all subcategories. 
One menu not two - one with pages and second with categories. 

Also add option i global setting (metadata) to choose displaying or hiding category name in post.

**Comment by daviddarnes** [comment]
Could you not add a page with a redirect url to the category page?

Hiding the category name is something you can do in the theme, by removing it or commenting it out.

**Comment by moje-s** [comment]
The goal is to habe post from one catego at one page (website.com/page-x) not a redirect category page (website.com/category/single-category-slug). 
Posts should be displayed as from this ona page (website.com/page-x/single-post-slug) not at all posts page (website.com/page-x/single-post-slug). 

Also if there is only one category, a single post should not contain a "post/" in  url (website.com/single-post-slug). For more than one category, a single post should contain category name in url (website.com/single-category-slug/single-post-slug) or categories (website.com/single-category-slug/single-subcategory-slug/single-post-slug).

**Comment by daviddarnes** [comment]
You could achieve this with a custom page template that loops through posts and checks their category.

I think you're adding way too much complexity into how category slugs work. Users might want their slugs different to how you think, also if any of the categories are renamed or change on a post then you'll get a 404 on that url. Using `post/name-of-post-as-slug` means this is way less likely to happen.

**Comment by moje-s** [comment]
When an user change/rename category, the url should be changed/renamed automatically from website.com/single-category-slug/single-post-slug to website.com/new-single-category-slug/single-post-slug. 
Also the url should be redirected from the old category's url to the new category's url in automatic way or in manual way by user (yes/no option).

**Comment by daviddarnes** [comment]
@moje-s this seems far too complex for such a simple feature. I'm guessing slugs will be constructed slightly different in v1.0, with the ability to change `post/` to whatever you like. But having custom category pages seems like something that should be dealt with in the template.

**Comment by moje-s** [comment]
In my opinion it should be easy in use for an users who are not a programmers. 
I know that post from back-end is not only posts manager but it is related with front-end structure of website. Front-end structure of website be related only with categories, menu items. So back-end post will be only a posts manager but not a part of front-end structure.

**Comment by daviddarnes** [comment]
@moje-s I fully agree, however we can't expose every single piece of control to the user. It's the same reason why drivers can't control how much fuel they use. We want to give users good control that isn't overwhelming.

**Comment by moje-s** [comment]
Alternative solution: Change url of categories from websitte.com/categories/single-category-slug to websitte.com/single-category-slug. And addition option for menu, another redirection but this time to category. Two inputs, for the name of menu's item and second with the dropdown list of categories.

**Comment by daviddarnes** [comment]
@kieronwilson @CraigChilds94 do we know how slugs will work in Anchor 1.0?

**Comment by TheBrenny** [comment]
@moje-s I agree with David, you're trying to make everything way too complex. :L Also, format your URLs and code using backticks(`) please. It's so much more appealing for my eyes! :')

@daviddarnes, Perhaps a less complicated, but still far too crazy idea could be to implement a customiser to the CMS Admin, to add custom routing. Detect the custom routing the same way themes are detected - but even that idea is crazy. Everything that's been mentioned could be done with a little bit of tweaking to the `routes.php`, and editing of the theme that will be used.

**Comment by daviddarnes** [comment]
@TheBrenny that seems fair. I'm completely fine with how everything works right now, all except for how urls clash with folder names in the the actual install. I think there's another issue that mentions the idea of prefixing them, so they become a little more obscure.

**Comment by TheBrenny** [comment]
@daviddarnes Tough decisions are tough! :stuck_out_tongue_winking_eye:

**Comment by daviddarnes** [comment]
@TheBrenny we'll discuss further.

**Comment by saucytomato** [comment]
Just one idea: shouldn't features go under the feathub, separate from the issues?

**Comment by daviddarnes** [comment]
@saucytomato I guess you're right! However it doesn't stop people from posting them here :(

**Comment by CraigChilds94** [comment]
@daviddarnes @saucytomato I'm planning on putting them all on there and closing them here.  Keeping a reference of their number of course.

I guess we'll just have to do it periodically

**Comment by CraigChilds94** [comment]
Migrated to feathub. http://feathub.com/anchorcms/anchor-cms/+5
